### ISSUE TITLE
idea 2017版一直报错不知道为什么

### ISSUE THREAD

**Issue by XeonMic** [YiiGuxing/TranslationPlugin#105]
Event Log 如下:

secret_password_lookup_sync error code 32597, error message null
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.credentialStore.SecretCredentialStore.get(linuxSecretLibrary.kt:147)
	at com.intellij.credentialStore.CredentialStoreWrapper.get(CredentialStoreWrapper.kt:52)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.get(PasswordSafeImpl.kt:53)
	at com.intellij.credentialStore.CredentialStore.getPassword(CredentialStore.java:30)
	at com.intellij.ide.passwordSafe.PasswordStorage.getPassword(PasswordStorage.java:30)
	at cn.yiiguxing.plugin.translate.compat.PasswordSafeCompat.getPassword(PasswordSafeCompat.java:31)
	at cn.yiiguxing.plugin.translate.Settings.getAppPrivateKey(Settings.java:151)
	at cn.yiiguxing.plugin.translate.Translator.getQueryUrl(Translator.java:90)
	at cn.yiiguxing.plugin.translate.Translator.access$000(Translator.java:20)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by YiiGuxing** [comment]
请问是2017哪一版？

**Comment by XeonMic** [comment]
2017.2.5

**Comment by XeonMic** [comment]
刚试了下2017.2.5可以，之前用的.1.x  .2.3左右的时候报的

**Comment by YiiGuxing** [comment]
合并到 #115

**Comment by YiiGuxing** [comment]
可以从 #115 获取更多信息和暂时解决方案。
