### ISSUE TITLE
JetBrains WebStorm 2017.2.5 x64 下问题

### ISSUE THREAD

**Issue by tianxz** [YiiGuxing/TranslationPlugin#114]
密钥已经给了, 但是报 Connection reset 的错误

**Comment by tianxz** [comment]
使用1.3.4没有这个异常

**Comment by YiiGuxing** [comment]
是插件崩溃还是插件的错误提示？如果是崩溃能否提供崩溃信息？如果是插件的错误提示，可以打开IDE的Log文件，搜索`query url`找到相应URL，然后在浏览上访问该URL，以确认你的密钥是否正确。
找到Log文件：`help -> show log in ...`

**Comment by tianxz** [comment]
浏览器可以打开, 但是还是报了警告:
2017-11-27 16:09:53,649 [  34107]   WARN - ng.plugin.translate.Translator - Connection reset 
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:505)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:288)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:423)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:346)
	at com.intellij.util.io.RequestBuilder.lambda$readString$3(RequestBuilder.java:77)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:414)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:414)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:394)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:262)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:77)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:127)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-11-27 16:10:14,020 [  54478]   INFO - .script.IdeScriptEngineManager - javax.script.ScriptEngineManager initialized in 58 ms 
2017-11-27 16:10:15,071 [  55529]   WARN - ellij.openapi.ui.DialogWrapper - Stale listener: com.intellij.ide.ui.laf.LafManagerImpl$OurPopupFactory$1@11aaae76 
2017-11-27 16:10:20,104 [  60562]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1

**Comment by YiiGuxing** [comment]
会不会是IDE设置了代理什么的？重启IDE试试？这个并不是插件本身的问题，可能是网络环境的问题。是不是开始翻译到报错的过程是不是经过了10秒钟？

**Comment by tianxz** [comment]
IDEA没有设置代理, 今天才装的WebStorm;
1.不像是网络限制: 因为我在浏览器已经打开了;
2.如果开了代理才有你说的那种10秒左右的情况. 关闭代理直接就是 Connection reset;

**Comment by YiiGuxing** [comment]
那么当你使用浏览器打开URL时返回的是什么内容？

**Comment by tianxz** [comment]
我跟了一下代码, 直接用http, 不用https 就没问题了;
PS. 你代码太乱了... 有时间了重构下. 做最好的翻译插件.

**Comment by YiiGuxing** [comment]
是https的问题？一直都是使用https的，从未出现这样的问题啊，真是奇怪了。

还有我现在就正在做重构和接入Google翻译API的工作，很希望能得到相关的建议，还请不吝赐教。

**Comment by tianxz** [comment]
这个原理我一时想不清楚, 只是猜了一下, 然后就对了. 你可以考虑加个配置, 使用http或者https.

**Comment by YiiGuxing** [comment]
已修改为直接使用HTTP了
