### ISSUE TITLE
使用快捷键ALT+T翻译文本时报错

### ISSUE THREAD

**Issue by BailinSong** [YiiGuxing/TranslationPlugin#119]
# 使用快捷键`ALT`+`T`翻译文本时报错
* 出现频率随机，目前出过两次
* 出现不影响正常弹出和显示翻译结果
```java
InvocationTargetException: java.nio.channels.ClosedByInterruptException null
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.nio.channels.ClosedByInterruptException null
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:110)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
	at com.intellij.ide.passwordSafe.PasswordSafe.getInstance(PasswordSafe.java:28)
	at cn.yiiguxing.plugin.translate.compat.PasswordSafeCompat.getPassword(PasswordSafeCompat.java:31)
	at cn.yiiguxing.plugin.translate.Settings.getAppPrivateKey(Settings.java:151)
	at cn.yiiguxing.plugin.translate.Translator.getQueryUrl(Translator.java:90)
	at cn.yiiguxing.plugin.translate.Translator.access$000(Translator.java:20)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
	at java.nio.file.Files.readAllBytes(Files.java:3154)
	at com.intellij.util.io.PathKt.readBytes(path.kt:138)
	at com.intellij.credentialStore.MasterKeyFileStorage.get(KeePassCredentialStore.kt:247)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:70)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:44)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.computeProvider(PasswordSafeImpl.kt:38)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt:46)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	... 19 more
Caused by:

java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
	at java.nio.file.Files.readAllBytes(Files.java:3154)
	at com.intellij.util.io.PathKt.readBytes(path.kt:138)
	at com.intellij.credentialStore.MasterKeyFileStorage.get(KeePassCredentialStore.kt:247)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:70)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:44)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.computeProvider(PasswordSafeImpl.kt:38)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt:46)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
	at com.intellij.ide.passwordSafe.PasswordSafe.getInstance(PasswordSafe.java:28)
	at cn.yiiguxing.plugin.translate.compat.PasswordSafeCompat.getPassword(PasswordSafeCompat.java:31)
	at cn.yiiguxing.plugin.translate.Settings.getAppPrivateKey(Settings.java:151)
	at cn.yiiguxing.plugin.translate.Translator.getQueryUrl(Translator.java:90)
	at cn.yiiguxing.plugin.translate.Translator.access$000(Translator.java:20)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by YiiGuxing** [comment]
感谢反馈，但这个问题我无法在插件内修复。已向JetBrains反馈这个问题。
