### ISSUE TITLE
翻译redis时，报错

### ISSUE THREAD

**Issue by sd4324530** [YiiGuxing/TranslationPlugin#123]
Plugin v2.0
IntelliJ IDEA 2017.3.2
Build #IU-173.4127.27, built on December 26, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS: Windows 10 10.0
========================================

cn.yiiguxing.plugin.translate.trans.TranslateException: 翻译失败：未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:157)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unknown language code:ru-Latn
	at cn.yiiguxing.plugin.translate.trans.Lang$Companion.valueOfCode(Lang.kt:117)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator$LangDeserializer.deserialize(GoogleTranslator.kt:73)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator$LangDeserializer.deserialize(GoogleTranslator.kt:71)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at com.google.gson.Gson.fromJson(Gson.java:774)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:66)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:41)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:14)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:40)
	... 7 more

**Comment by sd4324530** [comment]
刚更新完，配置应该都是默认的，没改过

**Comment by YiiGuxing** [comment]
请问你翻译的是什么内容，又是以什么语言翻译的？

**Comment by sd4324530** [comment]
翻译的内容就是`redis`，英文哇

**Comment by YiiGuxing** [comment]
好的，已经重现，谢谢反馈！
