### ISSUE TITLE
翻译失败：未知错误

### ISSUE THREAD

**Issue by heshunwq** [YiiGuxing/TranslationPlugin#129]
2.0之后，不管是有道还是google都提示“翻译失败：未知错误”，我的idea版本是：2017.3.2

**Comment by YiiGuxing** [comment]
请按[这个问答](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)的描述提供一下错误信息，谢谢。

**Comment by heshunwq** [comment]
@YiiGuxing 我把shadowsocks关了依然还是报这个错
Plugin v2.0
IntelliJ IDEA 2017.3.2
Build #IU-173.4127.27, built on December 26, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS: Mac OS X 10.13.2
========================================

cn.yiiguxing.plugin.translate.trans.TranslateException: 翻译失败：未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:157)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection refused (Connection refused)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:435)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:292)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:427)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:41)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:14)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:40)
	... 7 more

**Comment by YiiGuxing** [comment]
这应该是网络问题，请检查一下你的网络环境。

**Comment by heshunwq** [comment]
@YiiGuxing 确实是的我的问题，我之前diea的代理设置错了。

**Comment by JerxLuo** [comment]
1. 开着 shadowsocksr 时 idea 的代理设置为 socks 协议，Check Connection 是成功的，使用谷歌翻译但是显示 
>Plugin v2.2  
>IntelliJ IDEA 2018.2.1  
>Build #IU-182.3911.36, built on August 6, 2018  
>JRE: 1.8.0_152-release-1248-b8 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1488)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3018)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:558)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:329)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:338)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:394)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.android.tools.idea.updater.AndroidSdkUpdaterPlugin$AndroidAuthenticator.getPasswordAuthentication(AndroidSdkUpdaterPlugin.java:97)
	at com.intellij.util.proxy.CommonProxy$CommonAuthenticator.getPasswordAuthentication(CommonProxy.java:275)
	at java.net.Authenticator.requestPasswordAuthentication(Authenticator.java:248)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:162)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.SocksSocketImpl.authenticate(SocksSocketImpl.java:159)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:472)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 20 more
```

2. 关了 shadowsocksr 并且把 idea 代理设置删除后，使用百度翻译，但是也是显示
>Plugin v2.2  
>IntelliJ IDEA 2018.2.1  
>Build #IU-182.3911.36, built on August 6, 2018  
>JRE: 1.8.0_152-release-1248-b8 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate > 错误[52,003]: 无效账号 - <a href="#SETTINGS">设置</a>
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Translate failed: 52003
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:95)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by JerxLuo** [comment]
@YiiGuxing 
1.开着 shadowsocksr 时 idea 的代理设置为 socks 协议，Check Connection 是成功的，使用谷歌翻译但是显示
Plugin v2.2
IntelliJ IDEA 2018.2.1
Build #IU-182.3911.36, built on August 6, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS: Windows 10 10.0

cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1488)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3018)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:558)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:329)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:338)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:394)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.android.tools.idea.updater.AndroidSdkUpdaterPlugin$AndroidAuthenticator.getPasswordAuthentication(AndroidSdkUpdaterPlugin.java:97)
	at com.intellij.util.proxy.CommonProxy$CommonAuthenticator.getPasswordAuthentication(CommonProxy.java:275)
	at java.net.Authenticator.requestPasswordAuthentication(Authenticator.java:248)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:162)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.SocksSocketImpl.authenticate(SocksSocketImpl.java:159)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:472)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 20 more
关了 shadowsocksr 并且把 idea 代理设置删除后，使用百度翻译，但是也是显示
Plugin v2.2
IntelliJ IDEA 2018.2.1
Build #IU-182.3911.36, built on August 6, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OS: Windows 10 10.0

cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate > 错误[52,003]: 无效账号 - <a href="#SETTINGS">设置</a>
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Translate failed: 52003
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:95)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more

**Comment by Ju-ch** [comment]
>Plugin v2.3.2  
>IntelliJ IDEA 2019.1.1  
>Build #IU-191.6707.61, built on April 16, 2019  
>JRE: 1.8.0_202-release-1483-b44 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 429. Status=429, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=en&hl=zh-CN&tk=196347.288481&q=%22%E6%8E%A5%E5%8F%97%E7%94%A8%E6%88%B7%E9%93%BE%E6%8E%A5%E7%BA%BF%E7%A8%8B%22
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:649)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```
