### ISSUE TITLE
文档翻译不了，可以选中翻译

### ISSUE THREAD

**Issue by xuMingHai1** [YiiGuxing/TranslationPlugin#1324]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

方法上的注释文档不能翻译，提示说未知错误，但是可以选中翻译文字

### 环境 & 错误日志
- 插件版本:  3.3-patch.1
- IDE版本:  IntelliJ IDEA 2022.1 (Ultimate Edition)
- 操作系统版本:   Windows 10 

- 错误日志:
```
2022-04-19 14:11:45,884 [17552367]   INFO - STDOUT - INFO - Translate url: https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=468993.120511
2022-04-19 14:11:45,884 [17552367]   INFO - #c.y.p.t.t.g.GoogleTranslator - Translate url: https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=468993.120511
2022-04-19 14:11:45,884 [17552367]   INFO - STDOUT - DEBUG - POST ==> https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=468993.120511
2022-04-19 14:11:45,884 [17552367]   INFO - STDOUT - 	|==> q=%3Cdiv+class%3D%22content%22%3E%0A++Token+reader+%28parser%29+features+specific+to+JSON+backend.+Eventual+replacement+for+JSON-specific+%3Ca+href%3D%22psi_element%3A%2F%2Fcom.fasterxml.jackson.core.JsonParser.Feature%22%3E%3Ccode+style%3D%22font-size%3A90%25%3B%22%3EJsonParser.Feature%3C%2Fcode%3E%3C%2Fa%3Es.+%0A%3C%2Fdiv%3E%0A%3Ctable+class%3D%22sections%22%3E%0A+%3Ctbody%3E%0A++%3Ctr%3E%0A+++%3Ctd+valign%3D%22top%22+class%3D%22section%22%3E%3Cp%3E%E8%87%AA%3A%3C%2Fp%3E%3C%2Ftd%3E%0A+++%3Ctd+valign%3D%22top%22%3E%3Cp%3E+2.10%3C%2Fp%3E%3C%2Ftd%3E%0A++%3C%2Ftr%3E%0A+%3C%2Ftbody%3E%0A%3C%2Ftable%3E
2022-04-19 14:11:46,104 [17552587]   INFO - STDOUT - INFO - Translate result: [["<div class=\"content\">特定于 JSON 后端的令牌读取器（解析器）功能。最终替换 JSON 特定的<a href=\"psi_element://com.fasterxml.jackson.core.JsonParser.Feature\"><code style=\"font-size:90%;\">JsonParser.Feature</code></a> 。</div><table class=\"sections\"><tbody><tr><td valign=\"top\" class=\"section\"><p>自：</p></td><td valign=\"top\"><p> 2.10</p></td></tr></tbody></table>","en"]]
2022-04-19 14:11:46,105 [17552588]   INFO - #c.y.p.t.t.g.GoogleTranslator - Translate result: [["<div class=\"content\">特定于 JSON 后端的令牌读取器（解析器）功能。最终替换 JSON 特定的<a href=\"psi_element://com.fasterxml.jackson.core.JsonParser.Feature\"><code style=\"font-size:90%;\">JsonParser.Feature</code></a> 。</div><table class=\"sections\"><tbody><tr><td valign=\"top\" class=\"section\"><p>自：</p></td><td valign=\"top\"><p> 2.10</p></td></tr></tbody></table>","en"]]
2022-04-19 14:11:46,105 [17552588]   INFO - STDOUT - WARN - java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,105 [17552588]   INFO - STDERR - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,105 [17552588]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:975)
2022-04-19 14:11:46,106 [17552589]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:928)
2022-04-19 14:11:46,106 [17552589]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:877)
2022-04-19 14:11:46,106 [17552589]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:848)
2022-04-19 14:11:46,106 [17552589]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:170)
2022-04-19 14:11:46,106 [17552589]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:19)
2022-04-19 14:11:46,106 [17552589]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,107 [17552590]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,107 [17552590]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
2022-04-19 14:11:46,107 [17552590]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
2022-04-19 14:11:46,107 [17552590]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:109)
2022-04-19 14:11:46,107 [17552590]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:72)
2022-04-19 14:11:46,107 [17552590]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:104)
2022-04-19 14:11:46,108 [17552591]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:38)
2022-04-19 14:11:46,108 [17552591]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
2022-04-19 14:11:46,108 [17552591]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-19 14:11:46,108 [17552591]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-19 14:11:46,108 [17552591]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
2022-04-19 14:11:46,108 [17552591]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
2022-04-19 14:11:46,109 [17552592]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2022-04-19 14:11:46,109 [17552592]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
2022-04-19 14:11:46,109 [17552592]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-19 14:11:46,109 [17552592]   INFO - STDERR - Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,109 [17552592]   INFO - STDERR - 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2022-04-19 14:11:46,109 [17552592]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:380)
2022-04-19 14:11:46,110 [17552593]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:368)
2022-04-19 14:11:46,110 [17552593]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
2022-04-19 14:11:46,110 [17552593]   INFO - STDERR - 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
2022-04-19 14:11:46,110 [17552593]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:963)
2022-04-19 14:11:46,110 [17552593]   INFO - STDERR - 	... 21 more
2022-04-19 14:11:46,111 [17552594]   INFO - STDOUT - ERROR - Translation error
2022-04-19 14:11:46,111 [17552594]   INFO - STDERR - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,112 [17552595]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:975)
2022-04-19 14:11:46,112 [17552595]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:928)
2022-04-19 14:11:46,112 [17552595]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:877)
2022-04-19 14:11:46,112 [17552595]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:848)
2022-04-19 14:11:46,112 [17552595]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:170)
2022-04-19 14:11:46,112 [17552595]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:19)
2022-04-19 14:11:46,113 [17552596]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,113 [17552596]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,113 [17552596]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
2022-04-19 14:11:46,113 [17552596]   INFO - STDOUT - INFO - Translate url: https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=496396.93618
2022-04-19 14:11:46,113 [17552596]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
2022-04-19 14:11:46,113 [17552596]   INFO - #c.y.p.t.t.g.GoogleTranslator - Translate url: https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=496396.93618
2022-04-19 14:11:46,113 [17552596]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:109)
2022-04-19 14:11:46,114 [17552597]   INFO - STDOUT - DEBUG - POST ==> https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=496396.93618
2022-04-19 14:11:46,114 [17552597]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:72)
2022-04-19 14:11:46,114 [17552597]   INFO - STDOUT - 	|==> q=%3Cdiv+class%3D%22content%22%3E%0A++Feature+that+determines+whether+parser+will+allow+use+of+Java%2FC%2FC%2B%2B+style+comments+%28both+%27%2F%27%2B%27*%27+and+%27%2F%2F%27+varieties%29+within+parsed+content+or+not.+%0A+%3Cp%3E+Since+JSON+specification+does+not+mention+comments+as+legal+construct%2C+this+is+a+non-standard+feature%3B+however%2C+in+the+wild+this+is+extensively+used.+As+such%2C+feature+is+%3Cstrong%3Edisabled+by+default%3C%2Fstrong%3E+for+parsers+and+must+be+explicitly+enabled.+%3C%2Fp%3E%0A%3C%2Fdiv%3E%0A%3Ctable+class%3D%22sections%22%3E%3C%2Ftable%3E
2022-04-19 14:11:46,114 [17552597]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:104)
2022-04-19 14:11:46,114 [17552597]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:38)
2022-04-19 14:11:46,114 [17552597]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
2022-04-19 14:11:46,114 [17552597]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-19 14:11:46,115 [17552598]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-19 14:11:46,115 [17552598]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
2022-04-19 14:11:46,115 [17552598]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
2022-04-19 14:11:46,115 [17552598]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2022-04-19 14:11:46,115 [17552598]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
2022-04-19 14:11:46,115 [17552598]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-19 14:11:46,115 [17552598]   INFO - STDERR - Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,116 [17552599]   INFO - STDERR - 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2022-04-19 14:11:46,116 [17552599]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:380)
2022-04-19 14:11:46,116 [17552599]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:368)
2022-04-19 14:11:46,116 [17552599]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
2022-04-19 14:11:46,116 [17552599]   INFO - STDERR - 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
2022-04-19 14:11:46,117 [17552600]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:963)
2022-04-19 14:11:46,117 [17552600]   INFO - STDERR - 	... 21 more
2022-04-19 14:11:46,339 [17552822]   INFO - STDOUT - INFO - Translate result: [["<div class=\"content\">确定解析器是否允许在解析的内容中使用 Java/C/C++ 样式注释（&#39;/&#39;+&#39;*&#39; 和 &#39;//&#39; 变体）的功能。<p>由于 JSON 规范没有将注释作为合法结构提及，因此这是一个非标准特性；然而，在野外，这被广泛使用。因此，解析器<strong>默认禁用</strong>功能，必须显式启用。</p></div><table class=\"sections\"></table>","en"]]
2022-04-19 14:11:46,339 [17552822]   INFO - #c.y.p.t.t.g.GoogleTranslator - Translate result: [["<div class=\"content\">确定解析器是否允许在解析的内容中使用 Java/C/C++ 样式注释（&#39;/&#39;+&#39;*&#39; 和 &#39;//&#39; 变体）的功能。<p>由于 JSON 规范没有将注释作为合法结构提及，因此这是一个非标准特性；然而，在野外，这被广泛使用。因此，解析器<strong>默认禁用</strong>功能，必须显式启用。</p></div><table class=\"sections\"></table>","en"]]
2022-04-19 14:11:46,339 [17552822]   INFO - STDOUT - WARN - java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,340 [17552823]   INFO - STDERR - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,340 [17552823]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:975)
2022-04-19 14:11:46,340 [17552823]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:928)
2022-04-19 14:11:46,340 [17552823]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:877)
2022-04-19 14:11:46,340 [17552823]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:848)
2022-04-19 14:11:46,341 [17552824]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:170)
2022-04-19 14:11:46,341 [17552824]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:19)
2022-04-19 14:11:46,341 [17552824]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,341 [17552824]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,341 [17552824]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
2022-04-19 14:11:46,342 [17552825]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
2022-04-19 14:11:46,342 [17552825]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:109)
2022-04-19 14:11:46,342 [17552825]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:72)
2022-04-19 14:11:46,342 [17552825]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:104)
2022-04-19 14:11:46,342 [17552825]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:38)
2022-04-19 14:11:46,342 [17552825]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
2022-04-19 14:11:46,343 [17552826]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-19 14:11:46,343 [17552826]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-19 14:11:46,343 [17552826]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
2022-04-19 14:11:46,343 [17552826]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
2022-04-19 14:11:46,343 [17552826]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2022-04-19 14:11:46,343 [17552826]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
2022-04-19 14:11:46,344 [17552827]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-19 14:11:46,344 [17552827]   INFO - STDERR - Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,344 [17552827]   INFO - STDERR - 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2022-04-19 14:11:46,344 [17552827]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:380)
2022-04-19 14:11:46,344 [17552827]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:368)
2022-04-19 14:11:46,344 [17552827]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
2022-04-19 14:11:46,345 [17552828]   INFO - STDERR - 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
2022-04-19 14:11:46,345 [17552828]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:963)
2022-04-19 14:11:46,345 [17552828]   INFO - STDERR - 	... 21 more
2022-04-19 14:11:46,464 [17552947]   INFO - STDOUT - ERROR - Translation error
2022-04-19 14:11:46,465 [17552948]   INFO - STDERR - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,465 [17552948]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:975)
2022-04-19 14:11:46,465 [17552948]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:928)
2022-04-19 14:11:46,465 [17552948]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:877)
2022-04-19 14:11:46,465 [17552948]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:848)
2022-04-19 14:11:46,466 [17552949]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:170)
2022-04-19 14:11:46,466 [17552949]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:19)
2022-04-19 14:11:46,466 [17552949]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,466 [17552949]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
2022-04-19 14:11:46,466 [17552949]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
2022-04-19 14:11:46,466 [17552949]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
2022-04-19 14:11:46,467 [17552950]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:109)
2022-04-19 14:11:46,467 [17552950]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:72)
2022-04-19 14:11:46,467 [17552950]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:104)
2022-04-19 14:11:46,467 [17552950]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:38)
2022-04-19 14:11:46,467 [17552950]   INFO - STDERR - 	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
2022-04-19 14:11:46,468 [17552951]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-04-19 14:11:46,468 [17552951]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-04-19 14:11:46,468 [17552951]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
2022-04-19 14:11:46,468 [17552951]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
2022-04-19 14:11:46,468 [17552951]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2022-04-19 14:11:46,468 [17552951]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
2022-04-19 14:11:46,469 [17552952]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:829)
2022-04-19 14:11:46,469 [17552952]   INFO - STDERR - Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
2022-04-19 14:11:46,469 [17552952]   INFO - STDERR - 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
2022-04-19 14:11:46,469 [17552952]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:380)
2022-04-19 14:11:46,469 [17552952]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:368)
2022-04-19 14:11:46,469 [17552952]   INFO - STDERR - 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
2022-04-19 14:11:46,469 [17552952]   INFO - STDERR - 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
2022-04-19 14:11:46,470 [17552953]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:963)
2022-04-19 14:11:46,470 [17552953]   INFO - STDERR - 	... 21 more
```

**Comment by YiiGuxing** [comment]
Duplicate of #1318

正在紧急伯修复中，晚些时候发布修复版本。
