### ISSUE TITLE
[Auto Generated]Plugin error occurred: Google 翻译[translate.google] :: Bad Gateway

### ISSUE THREAD

**Issue by xuMingHai1** [YiiGuxing/TranslationPlugin#1339]
:warning:_`[Auto Generated Report]-=E093490A9023464BF8A76BD8F3EF4216=-`_

## Description

Google 翻译[translate.google] :: Bad Gateway

### Additional Information
鼠标放在类上，弹窗翻译出现的。

## Environments
> **Plugin version: 3.3.1**

IntelliJ IDEA 2022.1 (Ultimate Edition)
Build #IU-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Operating system: Windows 10 10.0
Last action id: null

## Stack Trace
```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译[translate.google] :: Bad Gateway
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:51)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:250)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:38)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 502. Status=502, Url=https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=361867.228190
	at cn.yiiguxing.plugin.translate.util.Http.checkResponseCode(Http.kt:98)
	at cn.yiiguxing.plugin.translate.util.Http.post$lambda-0(Http.kt:87)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:85)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:55)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:44)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:145)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:21)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$1.invoke(GoogleTranslator.kt:108)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$1.invoke(GoogleTranslator.kt:106)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:112)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:75)
	... 10 more
```

**Comment by YiiGuxing** [comment]
谷歌服务的问题。。。。

**Comment by xuMingHai1** [comment]
新功能很好用，有点蒙，字都打错了 :laughing:
