### ISSUE TITLE
开启代理后 翻译失败

### ISSUE THREAD

**Issue by sh1tge** [YiiGuxing/TranslationPlugin#142]
## Description
Android Studio 3.0.1开启SOCKS代理会导致翻译失败
勾选No proxy则正常

ps: 感觉好像可能貌似是intellij的问题..设置了代理check for updates 也会有问题~

## Environment & Stack Trace

>Plugin v2.0.2
>Android Studio 3.0.1
>Build #AI-171.4443003, built on November 10, 2017
>JRE: 1.8.0_152-release-915-b01 amd64
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
>Windows 7 6.1

```java
cn.yiiguxing.plugin.translate.trans.TranslateException: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:166)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1488)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3018)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:511)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:289)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:429)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:347)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:420)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:420)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:395)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:263)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.android.tools.idea.updater.AndroidSdkUpdaterPlugin$AndroidAuthenticator.getPasswordAuthentication(AndroidSdkUpdaterPlugin.java:102)
	at com.intellij.util.proxy.CommonProxy$CommonAuthenticator.getPasswordAuthentication(CommonProxy.java:286)
	at java.net.Authenticator.requestPasswordAuthentication(Authenticator.java:248)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:162)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.SocksSocketImpl.authenticate(SocksSocketImpl.java:159)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:472)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 23 more
```

**Comment by YiiGuxing** [comment]
IDE代理会影响翻译的HTTP请求。从异常栈中可以看出是android插件的问题，与本插件无关
