### ISSUE TITLE
报签名无效,之前是好,打开设置填写后,重新打开设置,key一栏是空白的

### ISSUE THREAD

**Issue by SunLangzi** [YiiGuxing/TranslationPlugin#143]
设置了app id 与app key 在翻译时报,签名无效,上次设置都是有效的,
重新打开设置时,key一栏是空白的
>Plugin v2.0.2  
>IntelliJ IDEA 2017.3.4  
>Build #IC-173.4548.28, built on January 30, 2018  
>JRE: 1.8.0_152-release-1024-b11 x86_64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Mac OS X 10.13.3

cn.yiiguxing.plugin.translate.trans.TranslateException: ERROR[202]: Invalid signature - <a href="#SETTINGS">Settings</a>
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:166)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cn.yiiguxing.plugin.translate.trans.YoudaoTranslator$YoudaoTranslateException: Translate failed: 202
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:74)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more

**Comment by YiiGuxing** [comment]
见 #116

**Comment by SunLangzi** [comment]
谢谢!
