### ISSUE TITLE
[Auto Generated]Plugin error occurred: Translation error[translate.google]: null

### ISSUE THREAD

**Issue by xuMingHai1** [YiiGuxing/TranslationPlugin#1557]
:warning:_`[Auto Generated Report]-=74692BB5FE756F8D6CA63A47E8BE133B=-`_

## Description

Translation error[translate.google]: null

## Environments
> **Plugin version: 3.3.2**

IntelliJ IDEA 2022.1.1 (Ultimate Edition)
Build #IU-221.5591.52, built on May 11, 2022
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Operating system: Windows 10 10.0
Last action id: null

## Stack Trace
```
java.util.NoSuchElementException
	at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2102)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:195)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:115)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:109)
	at cn.yiiguxing.plugin.translate.util.Http.post$lambda-0(Http.kt:86)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:85)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:55)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:44)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:145)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:21)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:67)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:69)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:69)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:20)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

## Attachments
<details>
<summary>request.txt</summary>

```Plain text
Translator: translate.google
Source language: 检测语言(auto)
Target language: 中文(简体)(zh-CN)
================ Request Text ================
https://www.google.com
==============================================
```

</details>

**Comment by YiiGuxing** [comment]
@xuMingHai1 请问这个问题可以重现吗？我这边无法重现。

**Comment by xuMingHai1** [comment]
> @xuMingHai1我这个问题不能复现吗？

我这里已经找不到更多日志了，等下次再出现看看怎么回事吧。我觉得这个自动提交日志可以提交多点

**Comment by YiiGuxing** [comment]
刚刚分析了一下，猜测应该当时你翻译的时候，翻译服务的状态可能是有什么问题，导致的这个异常，异常是出现在HTTP连接层上的，不在插件层面上，在插件上应该是无法解决的。所以这个问题就暂时关闭了。

**Comment by xuMingHai1** [comment]
> 刚刚分析了一下，猜测应该当时你翻译的时候，翻译服务的状态可能是有什么问题，导致的这个异常，异常是出现在HTTP连接层上的，不在插件层面上，在插件上应该是无法解决的。所以这个问题就暂时关闭了。

好的
