### ISSUE TITLE
解析google返回的内容失败

### ISSUE THREAD

**Issue by sbdx** [YiiGuxing/TranslationPlugin#1598]
## 检查清单
*请确保通过将 `[ ]` 替换为 `[x]` 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
打开JDK文档，右键，翻译文档，报错：翻译文档失败: 未知错误。

"翻译选中的文本"可以正确显示翻译结果。

通过抓包，已经返回了翻译结果。

### 环境 & 错误日志
- 插件版本: 3.3-203u212.patch.1
- IDE版本: IntelliJ IDEA 2021.2.2 #IU-212.5284.40
- 操作系统版本: Windows 10
 (版本崩溃时请提供)
- 错误日志:
```
Translation error

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:170)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:19)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$client$2.invoke(GoogleTranslator.kt:106)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:109)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:72)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:38)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 21 more
```

Req:
```
POST https://translate.googleapis.com/translate_a/single?sl=auto&tl=zh-CN&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dt=ex&dj=1&ie=UTF-8&oe=UTF-8&hl=zh-CN&tk=750261.815375 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62
Accept-Encoding: gzip
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Referer: https://translate.google.com/
Cache-Control: no-cache
Pragma: no-cache
Host: translate.googleapis.com
Connection: keep-alive
Content-Length: 218

q=Prints+an+Object+and+then+terminate+the+line.+This+method+calls+at+first+String.valueOf%28x%29+to+get+the+printed+object%27s+string+value%2C+then+behaves+as+though+it+invokes+print%28String%29+and+then+println%28%29.
```

Resp:
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Sat, 11 Jun 2022 10:58:47 GMT
Content-Disposition: attachment; filename="json.txt"; filename*=UTF-8''json.txt
Accept-CH: Sec-CH-UA-Arch, Sec-CH-UA-Bitness, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Model, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version
Cross-Origin-Opener-Policy: same-origin
Content-Security-Policy: require-trusted-types-for 'script';report-uri /_/TranslateApiHttp/cspreport
Content-Security-Policy: script-src 'report-sample' 'nonce-lOvx-E7YcjAbQYXH7aJpcA' 'unsafe-inline';object-src 'none';base-uri 'self';report-uri /_/TranslateApiHttp/cspreport;worker-src 'self'
Cross-Origin-Resource-Policy: cross-origin
Permissions-Policy: ch-ua-arch=*, ch-ua-bitness=*, ch-ua-full-version=*, ch-ua-full-version-list=*, ch-ua-model=*, ch-ua-platform=*, ch-ua-platform-version=*
Access-Control-Allow-Origin: *
Server: ESF
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Content-Length: 1815

{"sentences":[{"trans":"打印一个对象，然后终止该行。","orig":"Prints an Object and then terminate the line.","backend":3,"model_specification":[{}],"translation_engine_debug_info":[{"model_tracking":{"checkpoint_md5":"041e86f75565b6341f86f9972f755ac9","launch_doc":"en_zh_2021q4.md"}}]},{"trans":"此方法首先调用 String.valueOf(x) 以获取打印对象的字符串值，然后表现得好像它调用 print(String) 然后调用 println()。","orig":"This method calls at first String.valueOf(x) to get the printed object\u0027s string value, then behaves as though it invokes print(String) and then println().","backend":3,"model_specification":[{}],"translation_engine_debug_info":[{"model_tracking":{"checkpoint_md5":"041e86f75565b6341f86f9972f755ac9","launch_doc":"en_zh_2021q4.md"}}]},{"translit":"Dǎyìn yīgè duìxiàng, ránhòu zhōngzhǐ gāi xíng. Cǐ fāngfǎ shǒuxiān diàoyòng String.ValueOf(x) yǐ huòqǔ dǎyìn duìxiàng de zìfú chuàn zhí, ránhòu biǎoxiàn dé hǎoxiàng tā diàoyòng print(String) ránhòu diàoyòng println()."}],"src":"en","confidence":1.0,"spell":{"spell_html_res":"Prints an Object and then terminate the line. This method calls at first String.\u003cb\u003e\u003ci\u003evalue Of\u003c/i\u003e\u003c/b\u003e(x) to get the printed object\u0026#39;s string value, then behaves as though it invokes \u003cb\u003e\u003ci\u003eprintln\u003c/i\u003e\u003c/b\u003e(String) and then println().","spell_res":"Prints an Object and then terminate the line. This method calls at first String.value Of(x) to get the printed object\u0027s string value, then behaves as though it invokes println(String) and then println().","correction_type":[1],"confident":false},"ld_result":{"srclangs":["en"],"srclangs_confidences":[1.0],"extended_srclangs":["en"]}}
```

**Comment by YiiGuxing** [comment]
问题已经修复，请升级插件。
