### ISSUE TITLE
Mac 快捷键使用force touch有bug

### ISSUE THREAD

**Issue by ZuRun** [YiiGuxing/TranslationPlugin#160]
我设置的是translate快捷方式是长按触摸板

实际使用的时候 出现的是dialog

之前版本是正常的,idea是2018.1.2,插件是最新的翻译插件

- 设置页面
![image](https://user-images.githubusercontent.com/22558606/39674524-d2033670-517f-11e8-9e5c-a1e0340907bb.png)

- 实际使用效果
![image](https://user-images.githubusercontent.com/22558606/39674539-fdf5a290-517f-11e8-97bf-a1fc94199602.png)

**Comment by ZuRun** [comment]
是很奇怪,用右键菜单和快捷键都没问题,就长按触摸板显示有问题,而且dialog显示的还在屏幕中间.

插件卸载了重装还是有这个问题😂

**Comment by ZuRun** [comment]
有报错信息,贴给你看看
```
Argument for @NotNull parameter 'tracker' of cn/yiiguxing/plugin/translate/ui/balloon/BalloonImpl.revalidate must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'tracker' of cn/yiiguxing/plugin/translate/ui/balloon/BalloonImpl.revalidate must not be null
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.$$$reportNull$$$0(BalloonImpl.java)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.revalidate(BalloonImpl.java)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.revalidate(BalloonImpl.java:769)
	at cn.yiiguxing.plugin.translate.ui.TranslationBalloon$showCard$$inlined$invokeLater$1.run(Applications.kt:168)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by YiiGuxing** [comment]
插件是哪个版本，贴一下版本号

**Comment by YiiGuxing** [comment]
请使用这个包试一试：
[TranslationPlugin-2.0.4-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1978317/TranslationPlugin-2.0.4-SNAPSHOT.zip)

**Comment by YiiGuxing** [comment]
重复：#155

**Comment by ZuRun** [comment]
用了你发的包试了下,还是不行,报错信息还是那个

**Comment by YiiGuxing** [comment]
麻烦使用这个包再试一下，然后将错误信息反馈给我（强制报错）：
[TranslationPlugin-2.0.4-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1990180/TranslationPlugin-2.0.4-SNAPSHOT.zip)
谢谢！

**Comment by ZuRun** [comment]
Argument for @NotNull parameter 'tracker' of cn/yiiguxing/plugin/translate/ui/balloon/BalloonImpl.revalidate must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'tracker' of cn/yiiguxing/plugin/translate/ui/balloon/BalloonImpl.revalidate must not be null
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.$$$reportNull$$$0(BalloonImpl.java)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.revalidate(BalloonImpl.java)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.revalidate(BalloonImpl.java:769)
	at cn.yiiguxing.plugin.translate.ui.TranslationBalloon$showCard$$inlined$invokeLater$1.run(Applications.kt:169)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by YiiGuxing** [comment]
这回应该不会报错了吧:scream::scream::scream:：
[TranslationPlugin-2.0.4-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1990199/TranslationPlugin-2.0.4-SNAPSHOT.zip)

**Comment by ZuRun** [comment]
还是这个报错信息啊,难道是我姿势错了?

![image](https://user-images.githubusercontent.com/22558606/39850067-0c39cce0-5442-11e8-88c3-0bc3c5a5cdf7.png)
install plugin from disk,然后选择这个jar是嘛

**Comment by YiiGuxing** [comment]
。。。不是选择jar包，而是选择zip包啊。。。不要解压zip包

**Comment by YiiGuxing** [comment]
不过解包安装和这个错误关系不大，解包安装只会无法使用TTS功能。

**Comment by ZuRun** [comment]
额,选择了zip  也是一样,最后发给我的 不报错了,但是功能还是有问题.使用force touch触发的是dialog

**Comment by YiiGuxing** [comment]
那我知道是为什么了，只要不报错就行了。原因是这样的：使用touch触发其实是已经显示了气泡的，但是touch事件是持续触发的，所以气泡又被关闭了。。。因为气泡在触发编辑器的一些事件时会关闭，所以最好还不是要使用这个快捷键方式。

**Comment by ZuRun** [comment]
我是半年内用这个插件的,当时只有网易字典的,
但我不记得有没有自动更新,应该是4个月之内的版本

**Comment by YiiGuxing** [comment]
那再麻烦你使用这个包在使用force touch触发的情况下使用一次，然后将错误信息反馈给我，我看看force touch触发的时候到底发生了什么：
[TranslationPlugin-2.0.4-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1990267/TranslationPlugin-2.0.4-SNAPSHOT.zip)

**Comment by ZuRun** [comment]
错误信息:
```
test
java.lang.RuntimeException: test
	at cn.yiiguxing.plugin.translate.TranslationUIManager.showDialog(TranslationUIManager.kt:60)
	at cn.yiiguxing.plugin.translate.action.TranslateTextComponentAction$Handler.doExecute(TranslateTextComponentAction.kt:40)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:207)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:110)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.intellij.ui.mac.MacGestureSupportForEditor.handleMouseShortcut(MacGestureSupportForEditor.java:76)
	at com.intellij.ui.mac.MacGestureSupportForEditor.access$000(MacGestureSupportForEditor.java:40)
	at com.intellij.ui.mac.MacGestureSupportForEditor$1.lambda$pressure$0(MacGestureSupportForEditor.java:50)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.mac.MacGestureSupportForEditor$1.pressure(MacGestureSupportForEditor.java:49)
	at com.apple.eawt.event.GestureHandler$PerComponentNotifier.recursivelyHandlePressure(GestureHandler.java:180)
	at com.apple.eawt.event.GestureHandler$1.run(GestureHandler.java:102)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ZuRun** [comment]
控制台中功能是正常的

![image](https://user-images.githubusercontent.com/22558606/39851301-aa982944-5448-11e8-8b52-cc7f4555860d.png)

**Comment by YiiGuxing** [comment]
已经找到原因了：一般的快捷键在被第一次使用后就会被消耗掉，不会再传递了，但是不知道为什么force touch事件好像不会被消耗掉，在触发了气泡显示后，它仍然在传递（猜测，也可能是新的事件），导致它再一次触发另一个Action，这个Action打开了Dialog。
这样的话就不好处理了，因为我无法拦截force touch事件。只能规避，但这样的话就必须解绑几个Action的快捷键了，这会导致其他的体验上的问题。所以我还是建议不要使用这个快捷键方式。

**Comment by ZuRun** [comment]
这个包可以了,目前看没有问题了 😊

**Comment by YiiGuxing** [comment]
但是只会有这个包可以这样使用，在正式包上不会有相应的处理，也是无法使用的。所以如果你以后更新了的话也会无法使用的。

或许你可fork一下项目，然后应用以下补丁（需先解压）：
[force_touch.zip](https://github.com/YiiGuxing/TranslationPlugin/files/1990403/force_touch.zip)

然后自己编译打包。这样的话以后有新的功能什么的，从主项目合并过去再编译打包就行了。只不过这也麻烦了些。

**Comment by ZuRun** [comment]
好的,谢谢了 😄
