### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by lianyuteng** [YiiGuxing/TranslationPlugin#166]
## Description
![image](https://user-images.githubusercontent.com/20927567/40696577-f96f3c8c-63f8-11e8-8c94-4b25ec20b35e.png)
百度谷歌有道都是网络错误。

**Comment by lianyuteng** [comment]
电脑网络是没问题的

**Comment by YiiGuxing** [comment]
应该是网络环境的问题，你再检查一下，代理啊什么的。

请把错误信息贴出来我看看（点击图片中按钮，然后粘贴过来）：
![image](https://user-images.githubusercontent.com/10737066/40696707-7f3d970a-63f9-11e8-9b3f-ad8072489926.png)

**Comment by lianyuteng** [comment]
>Plugin v2.0.3  
>IntelliJ IDEA 2018.1.3  
>Build #IU-181.4892.42, built on May 8, 2018  
>JRE: 1.8.0_152-release-1136-b38 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Network error
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:278)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:412)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:336)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:403)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:335)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:403)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:252)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by lianyuteng** [comment]
我想应该是跟我IDEA的配置有关系，下载插件也是Unexpected end of file from server这个错误。麻烦您了，我再看下

**Comment by YiiGuxing** [comment]
这与插件无关的，应该是IDEA或者网络环境的问题。

**Comment by lianyuteng** [comment]
代理问题，抱歉。

**Comment by YiiGuxing** [comment]
说明：网络相关问题基本与插件无关，可以检查一下是不是代理的问题。

**Comment by lianyuteng** [comment]
![image](https://user-images.githubusercontent.com/20927567/44440169-9c265e00-a5f9-11e8-8c09-7d914071d6fc.png)
