### ISSUE TITLE
咋用不了了啊

### ISSUE THREAD

**Issue by djh2717** [YiiGuxing/TranslationPlugin#168]
>Plugin v2.0.3  
>Android Studio 3.1.2  
>Build #AI-173.4720617, built on April 14, 2018  
>JRE: 1.8.0_152-release-1024-b02 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 网络连接超时，请检查网络连接
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:292)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:427)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
网络问题，检查一下网络环境。

**Comment by djh2717** [comment]
我电脑网络没问题啊,,上网什么的都可以,,现在就在这回复您呢,怎么会有网络问题呢

**Comment by YiiGuxing** [comment]
你的IDE无法访问翻译API，看看是不是设置了代理什么的。或者换一下其他翻译API看看能不能访问。

**Comment by djh2717** [comment]
如何关闭代理

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/40772381-63100f28-64f2-11e8-8167-38ac1012c51b.png)

**Comment by djh2717** [comment]
这样可以不?

**Comment by YiiGuxing** [comment]
嗯，还不行的话可以换另一个API服务试试。

**Comment by djh2717** [comment]
>Plugin v2.0.3  
>Android Studio 3.1.2  
>Build #AI-173.4720617, built on April 14, 2018  
>JRE: 1.8.0_152-release-1024-b02 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 网络异常
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:484)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:482)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:481)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:522)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:292)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:427)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
如果你使用的是谷歌的翻译服务的话，看一看这个选项是不是勾上了：
![image](https://user-images.githubusercontent.com/10737066/40772852-b373a9d8-64f3-11e8-8f93-4ca45b109e14.png)

勾上这个选项需要翻墙才能访问。

**Comment by djh2717** [comment]
![isqxq 3 w1t7rxv_jg us](https://user-images.githubusercontent.com/39793504/40772897-d74dbf2e-64f3-11e8-999f-1758166b78b1.png)

**Comment by djh2717** [comment]
很无奈,,前几天还能用,今天就出问题了

**Comment by djh2717** [comment]
怎么换api服务?

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/40772977-133de978-64f4-11e8-8d7a-2946af9ad409.png)

**Comment by djh2717** [comment]
百度和有道都要收费吧?
我注册了百度的,但是ip地址填好了还是不行

**Comment by YiiGuxing** [comment]
有免费使用的，注册后填上去就行了。

**Comment by djh2717** [comment]
我在郁闷的是,我昨天还能用,今天咋就不行了

**Comment by YiiGuxing** [comment]
你可以试一下使用浏览器访问一下这个网站：https://translate.google.cn  看看能不能访问。

**Comment by djh2717** [comment]
不能

**Comment by YiiGuxing** [comment]
网络这类问题是与插件无关的，我也不好排查，因为影响的因素太多了。

**Comment by djh2717** [comment]
这是谷歌翻译中国吧

**Comment by djh2717** [comment]
是不是这个网址可以访问就能翻译了?

**Comment by YiiGuxing** [comment]
是的。

**Comment by djh2717** [comment]
这个网址不要翻墙吧?

**Comment by YiiGuxing** [comment]
不需要。你的现在所在网络环境上是有问题的，它不能访问谷歌翻译的API。可以先试试有道和百度的。

**Comment by YiiGuxing** [comment]
我这边就可以访问：
![image](https://user-images.githubusercontent.com/10737066/40773410-6416887c-64f5-11e8-93bb-1195fd848150.png)

**Comment by djh2717** [comment]
谢谢您了,我手机上面可以访问,到电脑上面就访问不了,好奇葩,,我用手机开的热点

**Comment by rebyss** [comment]
$ >Build #IU-191.7141.44, built on May 7, 2019  
>JRE: 1.8.0_202-release-1483-b49 x86_64  

这个问题怎么解决

**Comment by rebyss** [comment]
>Plugin v2.3.8  
>IntelliJ IDEA 2019.1.2  
>Build #IU-191.7141.44, built on May 7, 2019  
>JRE: 1.8.0_202-release-1483-b49 x86_64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.12.6

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:174)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 429. Status=429, Url=https://translate.google.com/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=429907.11914&q=user+Template
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:649)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:47)
	... 7 more
```

**Comment by YiiGuxing** [comment]
@rebyss 请求次数太多，被限制了，请稍候再试

**Comment by rebyss** [comment]
谢谢！好的


Yii.Guxing <notifications@github.com>于2019年8月2日 周五17:29写道：

**Comment by xiaobu1994** [comment]
我的能访问  https://translate.google.cn/ 但是也提示网络异常 最新版

**Comment by YiiGuxing** [comment]
@xiaobu1994 这种很有可能是代理问题，贴出错误信息就知道了。

**Comment by xiaobu1994** [comment]
哦哦 我把那个勾选去掉就可以了。看错了我用的是.cn结尾的错误报的是.com结尾的

**Comment by yikexiaoyao** [comment]
> 嗯，还不行的话可以换另一个API服务试试。

请问为什么不能用上面一个auto选项，我用的是这个，报一样的错误

**Comment by YiiGuxing** [comment]
@yikexiaoyao ？？！

**Comment by JavaHomeFeng** [comment]
![image](https://user-images.githubusercontent.com/51303407/133756881-51eb47ea-7ea5-4891-92c0-8d567fc732ba.png)
我的电脑可以访问  translate.google.cn  
但是他爆链接超时。啥问题，我电脑网络好像重置过一次就这样了。然后重装idea，和tran 都不好使，

**Comment by JavaHomeFeng** [comment]
我注册了个百度的api 可以了，但是刚才那个问题还是不知道出在那，是我hosts 配置的问题吗
