### ISSUE TITLE
翻译失败: 未知错误

### ISSUE THREAD

**Issue by lelewolf** [YiiGuxing/TranslationPlugin#178]
mac 系统下更新了webstrom到最新版本2018.2，后发现翻译插件不能正常使用，显示翻译失败，未知错误，在idea下重新尝试也是这个问题；

## Environment & Stack Trace
>Plugin v2.0.3  
>WebStorm 2018.2  
>Build #WS-182.3684.70, built on July 20, 2018  
>JRE: 1.8.0_152-release-1248-b8 x86_64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.13.6

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: delight/rhinosandox/RhinoSandboxes
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:92)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:213)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:182)
	at com.intellij.util.net.HttpConfigurable.openConnection(HttpConfigurable.java:434)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:507)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:329)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:338)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:394)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
你的代理可能有问题，可以先试试不使用

**Comment by lelewolf** [comment]
好的，在http proxy 取消了代理之后可以正常使用了，但是添加的代理后，check connection也是可以的，不知道什么原因导致的；

**Comment by YiiGuxing** [comment]
我想可能是连接方式不同导致的测试无错而插件有错。但这并不受插件控制，这应该是IDE的问题。

**Comment by lelewolf** [comment]
好的，非常感谢您的回复
