### ISSUE TITLE
Translation query failed

### ISSUE THREAD

**Issue by AnswerZhao** [YiiGuxing/TranslationPlugin#182]
Update the lasted, always ERROR[302]: Translation query failed or ERROR[301]: Dictionary query failed .

**Comment by YiiGuxing** [comment]
我这边是好的啊，可能那会儿有道又挂了？

**Comment by maxam0128** [comment]
我也有这个问题，我是google翻译

**Comment by FlappyPumpkinPie** [comment]
我的也是，google翻译失败，显示未知错误

**Comment by YiiGuxing** [comment]
麻烦贴一下错误信息（获取错误信息方法见：http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb）

**Comment by FlappyPumpkinPie** [comment]
>Plugin v2.1.0  
>IntelliJ IDEA 2017.2.5  
>Build #IU-172.4343.14, built on September 26, 2017  
>JRE: 1.8.0_152-release-915-b12 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 网络连接超时，请检查网络连接
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:505)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:288)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:423)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:346)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:414)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:414)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:394)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:262)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
@FlappyPumpkinPie 你贴的这次是网络问题，网络问题与插件无关，如果是未知错误之类的非网络问题才可能是插件的问题。

**Comment by weilei131** [comment]
javazoom/jl/decoder/Bitstream
java.lang.NoClassDefFoundError: javazoom/jl/decoder/Bitstream
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$Companion.getAudioDuration(GoogleTTSPlayer.kt:224)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$Companion.access$getAudioDuration(GoogleTTSPlayer.kt:200)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.play(GoogleTTSPlayer.kt:141)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.access$play(GoogleTTSPlayer.kt:37)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$PlayTask.run(GoogleTTSPlayer.kt:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javazoom.jl.decoder.Bitstream PluginClassLoader[cn.yiiguxing.plugin.translate, 2.1.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

我是查询了单词想播放一下，就出现这个错误，但是我昨天在家里面试了都没有存在这个问题？

**Comment by YiiGuxing** [comment]
@weilei131 可能是你安装方式有问题，请尝试重新安装，在IDE内通过插件仓库安装。如果是自己下载安装包安装的话，不要解压下载的ZIP包，直接选择ZIP包安装。

**Comment by AnswerZhao** [comment]
通过右键「翻译」或者快捷键，出现错误301，每次必现。但是点击TooBar上的蓝色的翻译按钮，翻译正常。

>Plugin v2.1.0  
>Android Studio 3.1.3  
>Build #AI-173.4819257, built on June 5, 2018  
>JRE: 1.8.0_152-release-1024-b01 x86_64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Mac OS X 10.13.6

```
cn.yiiguxing.plugin.translate.trans.TranslateException: ERROR[301]: Dictionary query failed
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Translate failed: 301
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:78)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

翻译和替换功能，每次都报错：

>Plugin v2.1.0  
>Android Studio 3.1.3  
>Build #AI-173.4819257, built on June 5, 2018  
>JRE: 1.8.0_152-release-1024-b01 x86_64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Mac OS X 10.13.6

```
cn.yiiguxing.plugin.translate.trans.TranslateException: ERROR[302]: Translation query failed
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Translate failed: 302
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:78)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:418)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:418)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:63)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:266)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
@AnswerZhao 从未遇到过这种情况啊，不管是在哪个地方翻译逻辑都是完全一样的啊。能否提供一下翻译的请求URL？

**Comment by YiiGuxing** [comment]
@AnswerZhao 而且，这是有道返回的错误，插件逻辑应该是没有问题的。请问你翻译任意文本都是失败的？能否提供几个样本？

**Comment by summertravel** [comment]
google翻译显示网络链接超时，请检查网络连接，我用百度的可以，网页上也能用google翻译，今天突然这样了

**Comment by AnswerZhao** [comment]
基本定位到问题了，以查询pattern单词为例。当选择模式 detect language -> english 或者 English-> English，报错Error 301: Dictionary query failed，但是只要改为 English -> Chinese，就翻译成功了，之后再采用前两种翻译模式也可以了。
@YiiGuxing
