### ISSUE TITLE
有道小部分单词可以翻译，大部分单词不可翻译。谷歌都可以翻译。

### ISSUE THREAD

**Issue by codethereforam** [YiiGuxing/TranslationPlugin#189]
## Description
Please describe the problem in detail. Be sure to include:
- step:  ctrl + shift + y
- What happened: ERROR[301]: Dictionary query failed
- What you think the correct behavior should be: translating correctly

## Environment & Stack Trace
- Plugin version: 2.1.0
- IDE version: IDEA 2018.2.1
- Operating System and version: Ubuntu18.04
- log(I replace appKey to XX for security).e.g.`fair` can be translated, while `already` can not:
```log
2018-08-13 20:01:26,844 [ 587197]   INFO - anslate.trans.YoudaoTranslator - Translate url: http://openapi.youdao.com/api?appKey=xxxx&from=auto&to=en&salt=1534161686843&sign=CBB6B622637B336687221B2D6E4094C2&q=fair 
2018-08-13 20:01:26,898 [ 587251]   INFO - anslate.trans.YoudaoTranslator - Translate result: {"tSpeakUrl":"http://openapi.youdao.com/ttsapi?q=fair&langType=en&sign=79EC54DD0D8E6994FBD9DA7F499E34F3&salt=1534161686935&voice=4&format=mp3&appKey=7bf63ecc2470b1fe","web":[{"value":["公平","定期集市","一般","博览会"],"key":"Fair"},{"value":["名利场","浮华世界","名位利益场","浮华新世界"],"key":"Vanity Fair"},{"value":["公平竞赛","费厄泼赖","公平对待","公平竞争"],"key":"fair play"}],"query":"fair","translation":["fair"],"errorCode":"0","dict":{"url":"yddict://m.youdao.com/dict?le=eng&q=fair"},"webdict":{"url":"http://m.youdao.com/dict?le=eng&q=fair"},"basic":{"exam_type":["高中","IELTS","初中"],"us-phonetic":"fɛr","phonetic":"feə","uk-phonetic":"feə","uk-speech":"http://openapi.youdao.com/ttsapi?q=fair&langType=en&sign=79EC54DD0D8E6994FBD9DA7F499E34F3&salt=1534161686935&voice=5&format=mp3&appKey=7bf63ecc2470b1fe","explains":["adj. 公平的；美丽的，白皙的；[气象] 晴朗的","adv. 公平地；直接地；清楚地","vi. 转晴","n. 展览会；市集；美人","n. (Fair)人名；(英、芬)费尔"],"us-speech":"http://openapi.youdao.com/ttsapi?q=fair&langType=en&sign=79EC54DD0D8E6994FBD9DA7F499E34F3&salt=1534161686935&voice=6&format=mp3&appKey=7bf63ecc2470b1fe"},"l":"EN2en","speakUrl":"http://openapi.youdao.com/ttsapi?q=fair&langType=en&sign=79EC54DD0D8E6994FBD9DA7F499E34F3&salt=1534161686935&voice=4&format=mp3&appKey=7bf63ecc2470b1fe"} 
2018-08-13 20:04:16,352 [ 756705]   INFO - anslate.trans.YoudaoTranslator - Translate url: http://openapi.youdao.com/api?appKey=xxxx&from=auto&to=en&salt=1534161856351&sign=606D4DDE1F27D8A5FAA2CD00C1552FB3&q=already 
2018-08-13 20:04:16,416 [ 756769]   INFO - anslate.trans.YoudaoTranslator - Translate result: {"errorCode":"301","l":"EN2en"} 
2018-08-13 20:04:16,417 [ 756770]   WARN - anslate.trans.TranslateService - translate 
cn.yiiguxing.plugin.translate.trans.TranslateException: ERROR[301]: Dictionary query failed
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Translate failed: 301
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:78)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
这是有道的问题，不是插件的问题，可能是有道并不支持将英文翻译到英文。。。

**Comment by codethereforam** [comment]
把语言设成中文解决了，谢谢！
