### ISSUE TITLE
IDEA同时安装 Azure toolkit, Big Data Tools, Translation这3个插件时, 启动IDEA在加载界面卡死

### ISSUE THREAD

**Issue by SFlora** [YiiGuxing/TranslationPlugin#1903]
* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
IDEA同时安装 Azure toolkit, Big Data Tools, Translation这3个插件时, 启动IDEA在加载界面卡死
### 问题描述
1. 重现问题的步骤。
      IDEA同时安装 Azure toolkit, Big Data Tools, Translation这3个插件
2. 发生了什么。
      启动IDEA在加载界面卡死

这3个插件缺少任意一个, IDEA都能正常启动

![image](https://user-images.githubusercontent.com/11220892/185849759-addad281-0dff-4ad2-8e24-4439bedc26a6.png)
![image](https://user-images.githubusercontent.com/11220892/185850335-339f11f3-70a8-4dd7-9f11-327a04719fc3.png)

### 环境 & 错误日志
- 插件版本: 3.3.4
- IDE版本: IDEA 2022.2
- 操作系统版本: Windows 11
- 错误日志:
```
2022-08-22 14:09:11,586 [   1726] SEVERE - #c.i.e.ExecutorRegistryImpl - IntelliJ IDEA 2022.2.1  Build #IU-222.3739.54
2022-08-22 14:09:11,586 [   1726] SEVERE - #c.i.e.ExecutorRegistryImpl - JDK: 17.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-08-22 14:09:11,586 [   1726] SEVERE - #c.i.e.ExecutorRegistryImpl - OS: Windows 11
2022-08-22 14:09:11,586 [   1726] SEVERE - #c.i.e.ExecutorRegistryImpl - Plugin to blame: Translation version: 3.3.4
2022-08-22 14:09:11,633 [   1773]   WARN - c.m.a.t.l.c.o.OperationContext - default to NULL OperationContext, because operation or its action operation is null:null
2022-08-22 14:09:11,633 [   1773]   WARN - #c.i.o.a.AnAction - caught an error by messager
com.microsoft.azure.toolkit.lib.common.operation.OperationException: init plugin
        at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:88)
        at com.microsoft.azure.toolkit.lib.common.operation.AzureOperationAspect.afterThrowing(AzureOperationAspect.java:49)
        at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:175)
        at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
        at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
        at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
        at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
        at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
        at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
        at jdk.proxy2/jdk.proxy2.$Proxy38.appFrameCreated(Unknown Source)
        at com.intellij.idea.IdeStarter.openProjectIfNeeded(IdeStarter.kt:100)
        at com.intellij.idea.IdeStarter.main(IdeStarter.kt:80)
        at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt:185)
        at com.intellij.idea.ApplicationLoader$initApplication$4.accept(ApplicationLoader.kt)
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.actionSystem.AnAction.getTemplateText()" because "origin" is null
        at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.getAction(IntellijAzureActionManager.java:77)
        at com.microsoft.azure.toolkit.lib.common.action.AzureActionManager.registerHandler(AzureActionManager.java:53)
        at com.microsoft.azure.toolkit.ide.appservice.AppServiceActionsContributor.registerHandlers(AppServiceActionsContributor.java:69)
        at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.lambda$register$1(IntellijAzureActionManager.java:58)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at com.microsoft.azure.toolkit.intellij.common.action.IntellijAzureActionManager.register(IntellijAzureActionManager.java:58)
        at com.microsoft.intellij.AzureActionsListener.appFrameCreated(AzureActionsListener.java:136)
        ... 20 more


```

**Comment by YiiGuxing** [comment]
从日志上看，应该是Azure toolkit的问题，你试试先卸载它看看能不能启动，然后再重新安装试试

**Comment by SFlora** [comment]
> 从日志上看，应该是Azure工具包的问题，​​你试试先看看它不能启动，然后卸载再重新安装试试

idea干净卸载重装过，其中任意两个插件都能共存，但这三个在一起就无法启动

**Comment by YiiGuxing** [comment]
问题已反馈给IDEA开发者了。。。 😂😂😂

**Comment by YiiGuxing** [comment]
我这边我做了处理，其他插件的我就没办法了: ce2bdb1ae5ff0adb0e74cc06e0eacc57e2a37b5f

最根本的还是得IDE平台才行。。。
