### ISSUE TITLE
谷歌翻译未知错误

### ISSUE THREAD

**Issue by Assassin-King** [YiiGuxing/TranslationPlugin#200]
## Description
idea's HttpProxy Check Connection is successful. 求大佬指教

## Environment & Stack Trace
>Plugin v2.1.1  
>IntelliJ IDEA 2018.2.2  
>Build #IU-182.4129.33, built on August 21, 2018  
>JRE: 1.8.0_101-b13 amd64  
>JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1455)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2979)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:558)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:329)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:338)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:394)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:475)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:451)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:47)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:303)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
Caused by: java.lang.NullPointerException
	at com.android.tools.idea.updater.AndroidSdkUpdaterPlugin$AndroidAuthenticator.getPasswordAuthentication(AndroidSdkUpdaterPlugin.java:97)
	at com.intellij.util.proxy.CommonProxy$CommonAuthenticator.getPasswordAuthentication(CommonProxy.java:275)
	at java.net.Authenticator.requestPasswordAuthentication(Authenticator.java:248)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:162)
	at java.net.SocksSocketImpl$2.run(SocksSocketImpl.java:160)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.SocksSocketImpl.authenticate(SocksSocketImpl.java:159)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:472)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	... 20 more
```

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
这是Android 插件的问题，见：https://github.com/JetBrains/android/pull/9
