### ISSUE TITLE
有道翻译报错    translate.google.com可以改成translate.google.cn 方便国内用户

### ISSUE THREAD

**Issue by Hasiy** [YiiGuxing/TranslationPlugin#213]
>Plugin v2.1.1  
>Android Studio 3.2.1  
>Build #AI-181.5540.7.32.5056338, built on October 9, 2018  
>JRE: 1.8.0_152-release-1136-b06 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Youdao Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Status: 404. Status=404, Url=http://openapi.youdao.com/api?appKey=123123123&from=auto&to=en&salt=1540291996651&sign=433F24C89ACAE66536554E0973E83E10&q=android
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:512)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:278)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:412)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:336)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:403)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:335)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:403)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:252)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
可能是有道服务的问题，现在应该好了。
国内用户默认是translate.google.cn的，除非你设备的语言环境为非中文。

**Comment by nick938** [comment]
translate.google.cn停止服务了啊，现在
