### ISSUE TITLE
翻译失败

### ISSUE THREAD

**Issue by liuFeCC** [YiiGuxing/TranslationPlugin#227]
>Plugin v2.2  
>IntelliJ IDEA 2018.1.5  
>构建 #IU-181.5281.24, 建于 June 12, 2018  
>JRE: 1.8.0_152-release-1136-b39 amd64  
>JVM: OpenJDK 64-Bit Server VM 由 JetBrains s.r.o 
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Status: 503. Status=503, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=en&hl=zh-CN&tk=596280.1021008&q=%E5%BC%80%E5%A7%8B%E6%96%B0%E5%A2%9E%E6%B2%99%E7%9B%92%E5%BA%94%E7%94%A8%E4%BF%A1%E6%81%AF
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:512)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:278)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:412)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:336)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:403)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:335)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:403)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:252)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by liuFeCC** [comment]
用的好好的，然后就突然翻译失败了，没有勾选Google翻译选项，网络也没有进行代理设置，就是一切默认的设置

**Comment by YiiGuxing** [comment]
根据翻译API返回的结果，这是服务器的错误，和插件无关，同一URL，我这边也是请求成功的。

**Comment by wzm996** [comment]
我这个是怎么回事？该怎么解决？


>Plugin v2.3.2  
>IntelliJ IDEA 2018.3.4  
>Build #IU-183.5429.30, built on January 29, 2019  
>JRE: 1.8.0_152-release-1343-b26 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 503. Status=503, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=540232.961297&q=public
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:643)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:624)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:387)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:442)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
@wzm996 稍候再试吧

**Comment by wzm996** [comment]
@YiiGuxing 好的我再等等
