### ISSUE TITLE
TranslateException

### ISSUE THREAD

**Issue by willchun** [YiiGuxing/TranslationPlugin#232]
>Plugin v2.2  
>Android Studio 3.2  
>Build #AI-181.5540.7.32.5014246, built on September 18, 2018  
>JRE: 1.8.0_152-release-1136-b06 x86_64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.14.2

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > Translation failed: Unknown error
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Status: 503. Status=503, Url=https://translate.google.com/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=en&hl=en&tk=943131.584528&q=params
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:512)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:278)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:412)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:336)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:403)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:335)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:403)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:49)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:252)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
see: #227
