### ISSUE TITLE
翻译失败，未知错误

### ISSUE THREAD

**Issue by kecson** [YiiGuxing/TranslationPlugin#260]
## Description
Please describe the problem in detail. Be sure to include:
- Steps to reproduce the problem.
- What happened.
- What you think the correct behavior should be.

## Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):
>Plugin v2.3.2  
>Android Studio 3.4  
>Build #AI-183.5429.30.34.5452501, built on April 10, 2019  
>JRE: 1.8.0_152-release-1343-b01 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/mozilla/javascript/Scriptable
	at delight.rhinosandox.RhinoSandboxes.create(RhinoSandboxes.java:9)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.setupEngine(JavaxPacScriptParser.java:51)
	at com.github.markusbernhardt.proxy.selector.pac.JavaxPacScriptParser.<init>(JavaxPacScriptParser.java:40)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.selectEngine(PacProxySelector.java:76)
	at com.github.markusbernhardt.proxy.selector.pac.PacProxySelector.<init>(PacProxySelector.java:41)
	at com.github.markusbernhardt.proxy.util.ProxyUtil.buildPacSelectorForUrl(ProxyUtil.java:90)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.createPacSelector(IEProxySearchStrategy.java:114)
	at com.github.markusbernhardt.proxy.search.browser.ie.IEProxySearchStrategy.getProxySelector(IEProxySearchStrategy.java:40)
	at com.github.markusbernhardt.proxy.ProxySearch.getProxySelector(ProxySearch.java:222)
	at com.intellij.util.net.IdeaWideProxySelector.select(IdeaWideProxySelector.java:79)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:213)
	at com.intellij.util.proxy.CommonProxy.select(CommonProxy.java:182)
	at com.intellij.util.net.HttpConfigurable.openConnection(HttpConfigurable.java:412)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:557)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:387)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:442)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.Scriptable
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:241)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more
```

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
#259
