### ISSUE TITLE
谷歌翻译失败

### ISSUE THREAD

**Issue by chengweng** [YiiGuxing/TranslationPlugin#265]
## Description
突然谷歌翻译就不能使用了，其它百度和有道是可以翻译

## Environment & Stack Trace
>Plugin v2.3.2  
>IntelliJ IDEA 2017.2.6  
>Build #IU-172.4574.8, built on November 7, 2017  
>JRE: 1.8.0_152-release-915-b12 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Status: 429. Status=429, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-TW&hl=zh-CN&tk=847334.685060&q=66
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:519)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:288)
	at com.intellij.util.io.HttpRequests.getCharset(HttpRequests.java:423)
	at com.intellij.util.io.HttpRequests.access$500(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:346)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.lambda$doProcess$0(HttpRequests.java:414)
	at com.intellij.util.net.ssl.CertificateManager.runWithUntrustedCertificateStrategy(CertificateManager.java:349)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:414)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:394)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:60)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:262)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

[Get Environment & Stack Trace](http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb)

**Comment by YiiGuxing** [comment]
HTTP CODE: 429 TOO MANY REQUESTS

请稍候再试
