### ISSUE TITLE
Google翻译: Forbidden

### ISSUE THREAD

**Issue by smudgeJJJ** [YiiGuxing/TranslationPlugin#277]
>Plugin v2.3.3  
>IntelliJ IDEA 2019.1.3  
>Build #IU-191.7479.19, built on May 28, 2019  
>JRE: 1.8.0_202-release-1483-b58 x86_64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.14.5

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: Forbidden
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 403. Status=403, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=342544.239063&q=sss
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:649)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:47)
	... 7 more
```

**Comment by smudgeJJJ** [comment]
在浏览器访问https://translate.google.cn/是可以的

**Comment by YiiGuxing** [comment]
失败的时候多试几次就可以，目录还不清楚是什么原因。

**Comment by smudgeJJJ** [comment]
> 失败的时候多试几次就可以，目录还不清楚是什么原因。

好的

**Comment by mcxinyu** [comment]
出现频率有点高了

>Plugin v2.3.4  
>Android Studio 3.4.2  
>Build #AI-183.6156.11.34.5692245, built on June 27, 2019  
>JRE: 1.8.0_152-release-1343-b01 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: Forbidden
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 403. Status=403, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=145132.305458&q=Center
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:643)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:624)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:387)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:442)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:47)
	... 7 more
```

**Comment by mcxinyu** [comment]
建议不要草率关闭这个issuse

**Comment by YiiGuxing** [comment]
谷歌翻译不能使用的信号。。。

**Comment by mcxinyu** [comment]
@YiiGuxing 把接口放postman测试没那么多错误呀，是不是有appid之类的东西呢？

**Comment by YiiGuxing** [comment]
@mcxinyu 那是因为有缓存

**Comment by mcxinyu** [comment]
确认么？

**Comment by YiiGuxing** [comment]
@smudgeJJJ 并不，猜的，我现在一次都不能成功，postman中。

**Comment by YiiGuxing** [comment]
应该是TK算法改变了。。。

**Comment by mcxinyu** [comment]
我使用的一个chrome翻译插件挺稳定的，也许可以参考下。[划词翻译](https://github.com/Selection-Translator/crx-selection-translate)

**Comment by smudgeJJJ** [comment]
现在多试几次的确是可以成功的，不太影响使用

**Comment by YiiGuxing** [comment]
看来是得考虑从Google服务器上更新获取TKK值了，我现在是随机生成的。。。

**Comment by danielesk** [comment]
@YiiGuxing Is this problem solved ?

**Comment by YiiGuxing** [comment]
@danielesk Yes. 
![image](https://user-images.githubusercontent.com/10737066/61191808-2cbdcf00-a6e1-11e9-9952-bcd96db247dd.png)

**Comment by BIGMONK** [comment]
刚刚更新完2.3.4，还是这样啊

**Comment by mcxinyu** [comment]
@BIGMONK  2.3.4是旧版

**Comment by BIGMONK** [comment]
> @BIGMONK 2.3.4是旧版

你好，android studio 没检测到更新的啊  显示是2.3.4    2019.7.12

**Comment by BIGMONK** [comment]
> @BIGMONK 2.3.4是旧版

项目的release也是到2.3.4

**Comment by mcxinyu** [comment]
因为还没发布。‘ready’! ok?

**Comment by mcxinyu** [comment]
ready for release

**Comment by BIGMONK** [comment]
> 因为还没发布。‘ready’! ok?

好的，谢谢
