### ISSUE TITLE
2.3.5版本异常

### ISSUE THREAD

**Issue by zbq2019** [YiiGuxing/TranslationPlugin#281]
IDEA版本： **2019.1**
TranslationPlugin版本：**2.3.5**

异常堆栈
java.lang.Throwable: Assertion failed: Network shouldn't be accessed in EDT or inside read action
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:496)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:68)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:54)
	at cn.yiiguxing.plugin.translate.trans.TKK.<clinit>(TK.kt:44)
	at cn.yiiguxing.plugin.translate.TranslationAppComponent.initComponent(TranslationAppComponent.kt:18)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:482)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:407)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:393)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:347)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by YiiGuxing** [comment]
请提供重现步骤，我这无法复现。

**Comment by jiahuanle** [comment]
@YiiGuxing 好像问题并没有解决，Translation版本2.3.6依然存在这个问题，导致无法使用

**Comment by YiiGuxing** [comment]
@jiahuanle 请提供详细的信息。因为我这边是没有什么问题的。
