### ISSUE TITLE
idea2019.1.3  插件v2.3.6版本 新建文件新建类名输入框 选择并替换 失效了

### ISSUE THREAD

**Issue by JefferyJu** [YiiGuxing/TranslationPlugin#282]

**Comment by danielesk** [comment]
@YiiGuxing 

经常性的有问题

>Plugin v2.3.6  
>PhpStorm 2019.1.3  
>Build #PS-191.7479.51, built on June 18, 2019  
>JRE: 1.8.0_202-release-1483-b53 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 7 6.1

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 429. Status=429, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=en&hl=zh-CN&tk=322972.151031&q=%E3%81%AE%E3%81%AE
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:649)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:47)
	... 7 more
```

**Comment by YiiGuxing** [comment]
@danielesk 请求过于频繁，被限制了，这是没办法的事情。还有，你这个问题和本Issue无关，如再遇到类似的情况请另开一个Issue，谢谢。

**Comment by JefferyJu** [comment]
希望可以早点发布新版本, 哈哈

**Comment by YiiGuxing** [comment]
@JefferyJu 最近版本发得有些频繁，先缓缓。。。

**Comment by YiiGuxing** [comment]
这个Issue等版本发布了再关

**Comment by danielesk** [comment]
@YiiGuxing 好的，谢谢了。
