### ISSUE TITLE
2019.1的版本在更新Translation为2.3.6后，报错，

### ISSUE THREAD

**Issue by helxiong** [YiiGuxing/TranslationPlugin#283]
Update TKK failed

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2055)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:615)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateFromGoogle$elementJS$1.process(TK.kt:68)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateFromGoogle$elementJS$1.process(TK.kt:31)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:68)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:54)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateAsync$$inlined$executeOnPooledThread$1.run(Applications.kt:167)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by YiiGuxing** [comment]
网络问题，请检查你的网络

**Comment by wanghaocun** [comment]
> 网络问题，请检查你的网络环境

为啥以前从未出现过这个问题   就近几天才反复出现  网络也没有什么异常啊
我现在PyCharm和IntelliJ IDEA都出现这个报错了
作者说的网络问题太宽泛了  有没有比较明确的解决办法

**Comment by YiiGuxing** [comment]
@wanghaocun 网络的问题与插件没有太多的关系，网络的问题又很复杂，所以很难给出比较明确的解决办法。在README的FAQ部分已经给出了一些常用的处理办法，所以在提交Issue之前请先阅读FAQ，在Issue的默认模板中也明确地列出并要求提交者先阅读FAQ和搜索类似的问题，再考虑是否有必要提交Issue。然而很少有人按要求来做，这对于项目的管理来说是带来了一些额外的负担的，因此为了减轻负担，重复的问题只会打上一个“重复”标签，不做其他地解释。请相互体谅一下，谢谢！
