### ISSUE TITLE
2.3.6版本异常

### ISSUE THREAD

**Issue by jiahuanle** [YiiGuxing/TranslationPlugin#287]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Issue Details
error code
```
Update TKK failed

java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:615)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateFromGoogle$elementJS$1.process(TK.kt:68)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateFromGoogle$elementJS$1.process(TK.kt:31)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:68)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:54)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateAsync$$inlined$executeOnPooledThread$1.run(Applications.kt:167)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
### Environment & Stack Trace
- Plugin version:2.3.6
- IDE version:phpstorm 2019.1.3
- Operating System and version: macOs Mojave 10.14.5 
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
duplicate: #283

**Comment by YiiGuxing** [comment]
你这个很有可能是代理的问题

**Comment by jiahuanle** [comment]
没有开任何网络代理吖，我重启一下电脑试试

**Comment by jiahuanle** [comment]
重启后可以了，谢谢您！

**Comment by YiiGuxing** [comment]
不用谢，可以了就行，下个版本我还是把这个崩溃提示给关了吧，体验不好，改成通知提示。

**Comment by liuzhihangs** [comment]
这个问题我也遇到了, 当前情况是 IDEA 2019.2 使用时报 TKK  但是 我的 DataGrip 并没有问题. 如果是网络问题或者代理, 应该是两个都无法使用..

Failed to update TKK.

>Plugin v2.3.7  
>IntelliJ IDEA 2019.2  
>Build #IU-192.5728.98, built on July 23, 2019  
>Runtime version: 11.0.3+12-b304.10 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.14.4

**Comment by liuzhihangs** [comment]
... 竟然是这个原因

之前一直能用, 更新完 2019.2 发现这个被勾住了, 之前什么都没设置过的.issues 还可以.


![image](https://user-images.githubusercontent.com/26057042/62029286-c7a3c680-b214-11e9-902c-299fcf817938.png)
