### ISSUE TITLE
idea 报错

### ISSUE THREAD

**Issue by holysky5** [YiiGuxing/TranslationPlugin#291]
## Preflight Checklist

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.
idea 2019.1.3 版本
## Issue Details
Update TKK failed

java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:615)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateFromGoogle$elementJS$1.process(TK.kt:68)
	at cn.yiiguxing.plugin.translate.trans.TKK$updateFromGoogle$elementJS$1.process(TK.kt:31)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:68)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:54)
	at cn.yiiguxing.plugin.translate.trans.TKK.getValue(TK.kt:44)
	at cn.yiiguxing.plugin.translate.trans.TKKt.tk$default(TK.kt:99)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.getTranslateUrl(GoogleTranslator.kt:70)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
duplicate: #283
