### ISSUE TITLE
翻译失败: 网络连接超时，请检查网络连接

### ISSUE THREAD

**Issue by h976353715** [YiiGuxing/TranslationPlugin#293]
## Preflight Checklist

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Description
>Plugin v2.3.7  
>IntelliJ IDEA 2019.2  
>Build #IU-192.5728.98, built on July 23, 2019  
>Runtime version: 11.0.3+12-b304.10 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.14.5

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 网络连接超时，请检查网络连接
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:174)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1221)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:626)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:389)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:453)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:47)
	... 7 more
```

### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by YiiGuxing** [comment]
![image](https://user-images.githubusercontent.com/10737066/61844746-1aa71200-aed3-11e9-92fb-e005250add64.png)

**Comment by h976353715** [comment]
网络什么的没问题，更新后就不能用了

**Comment by YiiGuxing** [comment]
网络问题与插件是没有什么关系的。
你试试访问 https://translate.google.cn/ ，看看能不能使用，如果能使用，那就检查一下IDE的代理设置。
也可以参考一下 [`network`](https://github.com/YiiGuxing/TranslationPlugin/issues?q=label%3Anetwork+is%3Aclosed) 标签下其他问题的处理方法。
