### ISSUE TITLE
梯子不能挂载，应该是pac名单有影响

### ISSUE THREAD

**Issue by will746** [YiiGuxing/TranslationPlugin#296]
挂载梯子、 或者全局状态下正常。 一旦启用pac过滤，就有影响，很难受啊。

>Plugin v2.3.2  
>Android Studio 3.4  
>Build #AI-183.5429.30.34.5452501, built on April 10, 2019  
>JRE: 1.8.0_152-release-1343-b01 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate > 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:169)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 403. Status=403, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=172931.262669&q=upload+Video+AD+Record
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:643)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:624)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:387)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:442)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:45)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:16)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	... 7 more
```

**Comment by YiiGuxing** [comment]
网络的问题和插件没有关系的。你看看你是不是勾选了使用translate.google.com这个选项。
