### ISSUE TITLE
百度翻译 翻译失败: 访问频率受限

### ISSUE THREAD

**Issue by 625250353** [YiiGuxing/TranslationPlugin#304]
使用快速翻译必然会提示翻译失败: 访问频率受限,需要等两秒再按一次才会成功,之前使用并未发生. 
以为是账号问题,更换账号后依然如此.

**Comment by 625250353** [comment]
翻译失败: 访问频率受限

>Plugin v2.3.8  
>PhpStorm 2019.2  
>构建 #PS-192.5728.108, 建于 July 24, 2019  
>JRE: 11.0.3+12-b304.10 amd64  
>JVM: OpenJDK 64-Bit Server VM 由 JetBrains s.r.o 　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 【汉化作者】平方X　　　　　　　　　　　　　　　　　　　　 【汉化反馈】https://www.pingfangx.com　　　　　　　　　　　　　　　　　　　　  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: 翻译失败: 访问频率受限
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:174)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Baidu Translate :: Translate failed: 54003
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:96)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:47)
	... 7 more
```

**Comment by YiiGuxing** [comment]
应该是百度API服务做了访问频率限制，看来只能延长访问时间间隔了

**Comment by 625250353** [comment]
我已经更换了同事刚注册的 ID和密钥进行尝试,结果依然如此




------------------ 原始邮件 ------------------
发件人: "Yii.Guxing"<notifications@github.com>; 
发送时间: 2019年8月21日(星期三) 下午2:28
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com>; 
抄送: "孙"<625250353@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [YiiGuxing/TranslationPlugin] 百度翻译 翻译失败: 访问频率受限 (#304)




应该是百度API服务做了访问频率限制，看来只能延长访问时间间隔了

**Comment by YiiGuxing** [comment]
我这边也是这样的，人家服务做这样的限制很正常，下一版延长访问时间间隔就行了。
