### ISSUE TITLE
谷歌翻译经常失败啊

### ISSUE THREAD

**Issue by Vixb1122** [YiiGuxing/TranslationPlugin#306]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

## Issue Details
1. 谷歌翻译经常失败
2. 访问请求链接发现是存在“异常流量”？
3. 但是我用网页版的谷歌翻译都没问题
4. 我用的一款UWP翻译软件，该软件用的也是类似的请求接口，也没有问题
5. 能否抓取该软件的链接，把请求接口替换下
6. 这款软件叫 [Fluent Translator](
https://www.microsoft.com/zh-cn/p/fluent-translator/9mz0951tfqlf)

### Environment & Stack Trace
>Plugin v2.3.8  
>Android Studio 3.6 Canary 8  
>Build #AI-192.5728.98.36.5825043, built on August 23, 2019  
>Runtime version: 1.8.0_212-release-1586-b04 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:174)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 429. Status=429, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=188884.279974&q=file
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:664)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:645)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:389)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:453)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:47)
	... 7 more
```

**Comment by YiiGuxing** [comment]
日志给出的结果是请求过于频繁，被服务器限制了，是不是你那边请求的次数太多太频繁了？

**Comment by Vixb1122** [comment]
> 日志给出的结果是请求过于频繁，被服务器限制了，是不是你那边请求的次数太多太频繁了？
@YiiGuxing ，没有啊，每天请求不超过30次，是因为公司网络下，其他人的请求也被计算在内了吗？

**Comment by YiiGuxing** [comment]
那就很奇怪了，我就没有遇到过这个问题

**Comment by Vixb1122** [comment]
@YiiGuxing 我这边直接在浏览器中进行请求，返回的结果是
```
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？

如果 Google 自动检测到从您的计算机网络发出的请求可能违反服务条款，就会显示此网页。这些请求一旦停止，此阻断即会失效。

该流量可能是由恶意软件、浏览器插件或发送自动请求的脚本发出的。如果您与他人共享网络连接，请向管理员寻求帮助 — 这可能是由多台计算机使用同一 IP 地址导致的。了解详情

有时，如果您使用的是自动程序普遍使用的高级条款或者正在快速连续地发送请求，则可能会出现此网页。

IP 地址：61.149.179.190
时间：2019-08-30T03:16:32Z
网址：https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=188884.279974&q=file
```

**Comment by YiiGuxing** [comment]
这应该和你们公司网络有关，可能最后到达Google服务器上都是同一个IP地址。

**Comment by Vixb1122** [comment]
@YiiGuxing 不可以直接使用谷歌网页版的翻译请求吗，貌似网页版没有限制

**Comment by YiiGuxing** [comment]
是同一个接口，只是参数不同而已，但是不可能弄成一样的，因为很多参数数据并不知道如何获取。
你可以试试使用Chrome的谷歌翻译官方插件试试会不会出现这个问题，插件使用的参数和Chrome的官方插件是一样的。

**Comment by Vixb1122** [comment]
> 是同一个接口，只是参数不同而已，但是不可能弄成一样的，因为很多参数数据并不知道如何获取。
> 你可以试试使用Chrome的谷歌翻译官方插件试试会不会出现这个问题，插件使用的参数和Chrome的官方插件是一样的。

现在ip被解封了，能请求了

**Comment by kinizumi** [comment]
现在谷歌所有服务都被大陆完全彻底地封杀了
https://www.vpnmentor.com/tools/test-the-great-china-firewall/
http://www.chinafirewalltest.com/?siteurl=
