### ISSUE TITLE
有道翻译失败，提示未知错误【205】

### ISSUE THREAD

**Issue by PDDDD** [YiiGuxing/TranslationPlugin#3071]
### 📝 问题描述

配置有道翻译后，翻译单词出现“翻译失败: 未知错误[205]”，Marketplace搜索最新版本为3.1.3+201u202，下载最新版3.4.1本地安装提示不兼容。Plugin 'Translation' is incompatible with this installation  

### 🏷 插件版本

3.1.3+201u202

### 🔁 翻译引擎

有道翻译

### 💻 IDE及运行环境

```plain text
Android Studio 4.1.1
Build #AI-201.8743.12.41.6953283, built on November 5, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 6
```

### 📋 堆栈跟踪

```plain text
>Plugin v3.1.3+201u202  
>Android Studio 4.1.1  
>Build #AI-201.8743.12.41.6953283, built on November 5, 2020  
>Runtime version: 1.8.0_242-release-1644-b01 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0


cn.yiiguxing.plugin.translate.trans.TranslateException: 有道翻译 :: 翻译失败: 未知错误[205]
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: 有道翻译 :: Translate failed: 205
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:107)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:91)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 8 more
```
```

**Comment by YiiGuxing** [comment]
我刚刚尝试了一下，3.1.3+201u202 版本有道翻译是可以正常使用的，会不会是你有道翻译控制台配置有误啊？实在不行你可以升级你的IDE，以获取最新的插件版本，你的IDE版本太老了。
