### ISSUE TITLE
老是报TTS Error

### ISSUE THREAD

**Issue by TerryLiu** [YiiGuxing/TranslationPlugin#309]
## Issue Details
今天使用时老是报错,请给诊断下.

### Description
TTS Error

java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:484)
	at sun.net.www.http.HttpClient$1.run(HttpClient.java:482)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.HttpClient.privilegedOpenServer(HttpClient.java:481)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:522)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:609)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:378)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:387)
	at com.intellij.util.io.HttpRequests$RequestImpl.doReadBytes(HttpRequests.java:436)
	at com.intellij.util.io.HttpRequests$RequestImpl.readBytes(HttpRequests.java:431)
	at com.intellij.util.io.RequestBuilder.lambda$readBytes$2(RequestBuilder.java:80)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
	at com.intellij.util.io.RequestBuilder.readBytes(RequestBuilder.java:80)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.play(GoogleTTSPlayer.kt:139)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.access$play(GoogleTTSPlayer.kt:37)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$PlayTask.run(GoogleTTSPlayer.kt:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TerryLiu** [comment]
又测试了下发现是http代理问题, 请问能增加相关的开关设置吗?

**Comment by YiiGuxing** [comment]
@TerryLiu 代理可是IDE的设置，我插件可不能擅自修改这个设置，这不合理，只能自己手动设置了。
