### ISSUE TITLE
无法发音

### ISSUE THREAD

**Issue by sonictuzi** [YiiGuxing/TranslationPlugin#317]
更新TTK失败，请检查网络连接

>Plugin v2.4.0  
>IntelliJ IDEA 2019.1.1  
>构建 #IU-191.6707.61, 建于 April 16, 2019  
>JRE: 1.8.0_202-release-1483-b44 amd64  
>JVM: OpenJDK 64-Bit Server VM 由 JetBrains s.r.o ————————————————————【汉化作者：平方X 汉化反馈：http://www.pingfangx.com】  
>OS: Windows 10 10.0

```
java.net.SocketTimeoutException: connect timed out
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:615)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at com.intellij.util.io.RequestBuilder.lambda$readString$3(RequestBuilder.java:86)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:86)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:74)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:57)
	at cn.yiiguxing.plugin.translate.trans.TKK.getValue(TK.kt:47)
	at cn.yiiguxing.plugin.translate.trans.TKKt.tk$default(TK.kt:111)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$playlist$2.invoke(GoogleTTSPlayer.kt:75)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$playlist$2.invoke(GoogleTTSPlayer.kt:37)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.getPlaylist(GoogleTTSPlayer.kt)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.play(GoogleTTSPlayer.kt:136)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.access$play(GoogleTTSPlayer.kt:37)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$PlayTask.run(GoogleTTSPlayer.kt:93)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by YiiGuxing** [comment]
duplicate: #299
