### ISSUE TITLE
idea 3 EAP. Translation2.4 报错. 不能使用

### ISSUE THREAD

**Issue by ten951** [YiiGuxing/TranslationPlugin#318]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Description
kotlin.UninitializedPropertyAccessException: lateinit property windowListener has not been initialized
	at cn.yiiguxing.plugin.translate.ui.TranslationDialog.dispose(TranslationDialog.kt:372)
	at com.intellij.openapi.ui.DialogWrapper$1.dispose(DialogWrapper.java:150)
	at com.intellij.openapi.util.ObjectTree$1.execute(ObjectTree.java:27)
	at com.intellij.openapi.util.ObjectTree$1.execute(ObjectTree.java:23)
	at com.intellij.openapi.util.ObjectNode$1.execute(ObjectNode.java:103)
	at com.intellij.openapi.util.ObjectNode$1.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:198)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:146)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:108)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:104)
	at com.intellij.openapi.ui.DialogWrapper.disposeIfNeeded(DialogWrapper.java:2140)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.dispose(DialogWrapperPeerImpl.java:749)
	at java.desktop/java.awt.Window.disposeImpl(Window.java:1174)
	at java.desktop/java.awt.Window$1DisposeAction.run(Window.java:1202)
	at java.desktop/java.awt.Window.doDispose(Window.java:1223)
	at java.desktop/java.awt.Window.dispose(Window.java:1164)
	at com.intellij.openapi.wm.impl.IdeFrameImpl.dispose(IdeFrameImpl.java:513)
	at com.intellij.openapi.wm.impl.WindowManagerImpl.disposeRootFrame(WindowManagerImpl.java:615)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeFrame.lambda$showIfNoProjectOpened$1(WelcomeFrame.java:195)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:810)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:469)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:705)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:468)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)### Environment & Stack Trace
- Plugin version:
- IDE version:
- Operating System and version:
- Stack Trace (for crash):

**Comment by ten951** [comment]
@YiiGuxing 并没有收到推送更新2.4.1版本. 是需要等么?

**Comment by YiiGuxing** [comment]
2.4.1还是Open状态啊
