### ISSUE TITLE
IDE Fatal Errors,Translation2.4.0,PhpStorm2019.2.2

### ISSUE THREAD

**Issue by allTrue** [YiiGuxing/TranslationPlugin#321]
#### Error:
![image](https://user-images.githubusercontent.com/8850458/65103454-df235280-da00-11e9-82d0-f9141cdb9ed1.png)
#### logs:
`
java.sql.SQLException: Cannot load JDBC driver class 'org.sqlite.JDBC'
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:489)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:599)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:809)
	at org.apache.commons.dbutils.AbstractQueryRunner.prepareConnection(AbstractQueryRunner.java:319)
	at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:459)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.initTable(WordBookService.kt:150)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.initialize(WordBookService.kt:65)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.<init>(WordBookService.kt:54)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:243)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:232)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:197)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:231)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:44)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService$Companion.getInstance(WordBookService.kt:345)
	at cn.yiiguxing.plugin.translate.util.ApplicationsKt.<clinit>(Applications.kt:84)
	at cn.yiiguxing.plugin.translate.TranslationAppComponent.initComponent(TranslationAppComponent.kt:18)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
	at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:438)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.sqlite.JDBC
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:282)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.commons.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:483)
	... 53 more
`
#### PhpStorm-2019.2.2版本信息
> 同环境下 IDEA 使用正常
![image](https://user-images.githubusercontent.com/8850458/65103639-6c66a700-da01-11e9-90d4-69b44fafcc0a.png)

**Comment by YiiGuxing** [comment]
请问这是什么操作导致的？

**Comment by allTrue** [comment]
> 请问这是什么操作导致的？

更新到 2.4.0 后重启 IDE 就报错，尝试在 Database 面板安装了 SQLite 驱动后重启 IDE 问题依旧

**Comment by YiiGuxing** [comment]
同样的版本，我这里没有问题啊。
你尝试到用户目录下找到`.translation`目录，看看里面是不是有一人`driver.jar`文件，如果有的话，把它删除了，然后重启IDE看看情况。

**Comment by allTrue** [comment]
没有 driver.jar 
``` bash
$ ll
total 24
drwxr-xr-x   4 xx  staff    128  9 18 09:57 .
drwxr-xr-x+ 73 xx  staff   2336  9 18 09:07 ..
-rw-r--r--   1 xx  staff      0  9 18 09:07 .lock
-rw-r--r--   1 xx  staff  12288  9 18 09:57 wordbook.db
```

**Comment by YiiGuxing** [comment]
这就那奇怪了，我这边无法重现这个问题。
那之前你是不是在单词本面板里下载过驱动文件？

**Comment by YiiGuxing** [comment]
试一试这个包：
[TranslationPlugin-2.4.0.zip](https://github.com/YiiGuxing/TranslationPlugin/files/3624337/TranslationPlugin-2.4.0.zip)

**Comment by allTrue** [comment]
可以使用了。因为一更新插件就报错，看单词翻译面板上也没有“收藏”按钮，所以没有去看单词本面板。刚看到你的留言后去打开单词本面板发现有个提示“下载缺失的驱动”，下载安装后能正常使用了

**Comment by YiiGuxing** [comment]
麻烦你帮忙做个测试，删除`.translation/driver.jar`文件，安装我上面发的包，然后重启IDE，看看是否还在提示错误，谢谢。

**Comment by allTrue** [comment]
我刚拿上面的包试了，安装重启 IDE 后没有再报 IDE Fatal Errors 错误，但是在单词本面板下载安装驱动再重启 IDE时，报了个 Plugin Error 错误后 IDE 自身被关闭，再打开 IDE 时发现 translation 被IDE自动禁用了。手动启用插件再试，会重现 Plugin Error 、IDE 被退出及插件被自动禁用问题。可反复重现。报告如下：
```
Plugin 'cn.yiiguxing.plugin.translate' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NoClassDefFoundError: org/apache/commons/dbcp2/BasicDataSource
    at cn.yiiguxing.plugin.translate.wordbook.WordBookService.initialize(WordBookService.kt:58)
    at cn.yiiguxing.plugin.translate.wordbook.WordBookService.<init>(WordBookService.kt:54)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:243)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:232)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:197)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:231)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:75)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:44)
    at cn.yiiguxing.plugin.translate.wordbook.WordBookService$Companion.getInstance(WordBookService.kt:347)
    at cn.yiiguxing.plugin.translate.util.ApplicationsKt.<clinit>(Applications.kt:84)
    at cn.yiiguxing.plugin.translate.TranslationAppComponent.initComponent(TranslationAppComponent.kt:18)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:503)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$load$7(ApplicationImpl.java:414)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:414)
    at com.intellij.idea.IdeaApplication.lambda$executeInitAppInEdt$5(IdeaApplication.java:150)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:438)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.dbcp2.BasicDataSource PluginClassLoader[cn.yiiguxing.plugin.translate, 2.4.0] com.intellij.ide.plugins.cl.PluginClassLoader@10c7adc0
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:75)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    ... 48 more
```

**Comment by YiiGuxing** [comment]
是不是你安装的方式不对哦，安装的时候不需要解压zip文件，直接选择zip文件安装：

![image](https://user-images.githubusercontent.com/10737066/65125679-6932e180-da28-11e9-927a-37d778c1ec04.png)
![image](https://user-images.githubusercontent.com/10737066/65125741-85cf1980-da28-11e9-84f8-f226818f6b19.png)

**Comment by allTrue** [comment]
我确实解压了...。重新安装 zip 包后没有出现问题，能正常使用了。

**Comment by YiiGuxing** [comment]
@allTrue 是否是删除了`.translation/driver.jar`文件后再安装的？

**Comment by allTrue** [comment]
是的，确认删除了 .translation/driver.jar

**Comment by YiiGuxing** [comment]
好的，谢谢！那么这个问题算了解决了。

**Comment by allTrue** [comment]
谢谢～！
