### ISSUE TITLE
翻译后点击小喇叭不发音，然后过一段时间后显示TTS网络超时

### ISSUE THREAD

**Issue by Jeffrey2971** [YiiGuxing/TranslationPlugin#3625]
### 📝 问题描述

选中单词进行翻译后点击小喇叭不发音，然后过一段时间后显示TTS网络超时

### 🏷 插件版本

3.4.2

### 🔁 翻译引擎

百度翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Licensed to kiddy inseams
You have a perpetual fallback license for this version.
Subscription is active until August 1, 2025.
Runtime version: 17.0.5+1-b653.23 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    debugger.watches.in.variables=false
    ide.experimental.ui=true
    js.debugger.webconsole=false

Non-Bundled Plugins:
    com.4lex4.intellij.solarized (2.4.0)
    some.awesome (1.14)
    cn.olange.rule (1.0.4)
    com.intellij.ideolog (203.0.30.0)
    com.markskelton.one-dark-theme (5.7.2)
    AceJump (3.8.10)
    com.euphoricity.gitignore (0.3)
    VisualVMLauncher (1.21.211.6085.0)
    com.intellij.aqua.selenium (223.8214.16)
    com.intellij.aqua (223.7571.117)
    GrepConsole (12.15.211.6693.1)
    SequenceDiagram (2.2.6)
    izhangzhihao.rainbow.brackets (2023.1.0)
    org.intellij.gitee (2022.3.8)
    com.baomidou.plugin.idea.mybatisx (1.5.5)
    cn.yiiguxing.plugin.translate (3.4.2)

Kotlin: 223-1.7.21-release-272-IJ8214.52
```

### 📋 堆栈跟踪

```plain text
DEBUG - Puts disk cache: F6D1567B899EDA43FF62A59811A93A8C
2023-05-11 09:40:26,388 [  41559]   WARN - #cn.yiiguxing.plugin.translate.trans.google.TKK - TKK update failed
java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:613)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:360)
	at com.intellij.util.io.HttpRequests$RequestImpl.doReadBytes(HttpRequests.java:436)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:425)
	at com.intellij.util.io.RequestBuilder.lambda$readString$4(RequestBuilder.java:81)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:334)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:81)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.updateFromGoogle(TK.kt:77)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.update(TK.kt:49)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.getValue(TK.kt:35)
	at cn.yiiguxing.plugin.translate.trans.google.TKKt.tk$default(TK.kt:110)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$playlist$2.invoke(GoogleTTSPlayer.kt:69)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$playlist$2.invoke(GoogleTTSPlayer.kt:58)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.getPlaylist(GoogleTTSPlayer.kt:58)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.play(GoogleTTSPlayer.kt:117)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer.access$play(GoogleTTSPlayer.kt:33)
	at cn.yiiguxing.plugin.translate.tts.GoogleTTSPlayer$PlayTask.run(GoogleTTSPlayer.kt:83)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by YiiGuxing** [comment]
参见： #2315
