### ISSUE TITLE
谷歌:我们的系统检测到您的计算机网络中存在异常流量

### ISSUE THREAD

**Issue by yangbangdong** [YiiGuxing/TranslationPlugin#369]
* [x ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Environment & Stack Trace
>Plugin v2.4.2  
>IntelliJ IDEA 2019.2.2  
>Build #IU-192.6603.28, built on September 6, 2019  
>Runtime version: 11.0.3+12-b304.56 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: Too Many Requests
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:54)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:185)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 429. Status=429, Url=https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=468895.102270&q=Test+Service+Api
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:664)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:645)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:389)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:453)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$translate$2.process(AbstractTranslator.kt:19)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:48)
	... 7 more
```
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？
IP 地址：111.199.81.245
时间：2019-10-16T09:25:48Z
网址：https://translate.google.cn/translate_a/single?client=gtx&dt=t&dt=bd&dt=rm&dj=1&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&hl=zh-CN&tk=468895.102270&q=Test+Service+Api

只有我一个人用这个插件,并且在自己家,被谷歌流控了,插件方面是否存在多次使用谷歌翻译的地方?

**Comment by YiiGuxing** [comment]
短时间内翻译的次数太多了，稍候再尝试进行翻译。
