### ISSUE TITLE
最新版本IEDA 异常

### ISSUE THREAD

**Issue by QABQ** [YiiGuxing/TranslationPlugin#383]
java.lang.NoSuchMethodError: 'javax.swing.ButtonGroup com.intellij.ui.layout.LayoutBuilder.getButtonGroup()'
	at cn.yiiguxing.plugin.translate.ui.TranslationPanel$component$2.invoke(TranslationPanel.kt:613)
	at cn.yiiguxing.plugin.translate.ui.TranslationPanel$component$2.invoke(TranslationPanel.kt:47)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at cn.yiiguxing.plugin.translate.ui.TranslationPanel.getComponent(TranslationPanel.kt)
	at cn.yiiguxing.plugin.translate.ui.TranslationBalloon.initTranslationPanel(TranslationBalloon.kt:118)
	at cn.yiiguxing.plugin.translate.ui.TranslationBalloon.<init>(TranslationBalloon.kt:78)
	at cn.yiiguxing.plugin.translate.TranslationUIManager.showBalloon(TranslationUIManager.kt:46)
	at cn.yiiguxing.plugin.translate.action.TranslateAction.onActionPerformed(TranslateAction.kt:44)
	at cn.yiiguxing.plugin.translate.action.AutoSelectAction.actionPerformed(AutoSelectAction.kt:60)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:602)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:655)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:654)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:472)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:828)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
![image](https://user-images.githubusercontent.com/10395320/67755933-0b0c0c00-fa74-11e9-8b03-07d088fc3ab1.png)

**Comment by QABQ** [comment]
跟新到最新插件已解决问题
