### ISSUE TITLE
idea启动中，意外停电关机后重启idea使用插件显示TKK更新失败，插件无法使用

### ISSUE THREAD

**Issue by liuluobing** [YiiGuxing/TranslationPlugin#393]
idea启动中，意外停电关机后重启idea使用插件显示TKK更新失败，插件无法使用

之前因为这个问题重装了系统，装完后插件使用正常，突然死机后插件显示TKK更新失败，无法使用

win10专业版  64位

**Comment by liuluobing** [comment]
>Plugin v2.5.1  
>IntelliJ IDEA 2019.2.4  
>Build #IU-192.7142.36, built on October 29, 2019  
>Runtime version: 11.0.4+10-b304.77 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.NetworkException: connect timed out. host=translate.google.cn
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:87)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:54)
	at cn.yiiguxing.plugin.translate.trans.TKK.getValue(TK.kt:44)
	at cn.yiiguxing.plugin.translate.trans.TKKt.tk$default(TK.kt:106)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.getTranslateUrl(GoogleTranslator.kt:64)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:44)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1227)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:626)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:389)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:453)
	at com.intellij.util.io.RequestBuilder.lambda$readString$3(RequestBuilder.java:86)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:86)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:67)
	... 12 more
```
