### ISSUE TITLE
Deepl翻译提示“网络连接超时”

### ISSUE THREAD

**Issue by MouXinyue** [YiiGuxing/TranslationPlugin#3956]
### 📝 问题描述

配置了Deepl密钥后，插件窗口显示网络间接超时。实际上网络可用，我使用postman和deeplapi(java)的依赖代码分别测试，都可以成功翻译。
--插件提示页面
![1688008322728](https://github.com/YiiGuxing/TranslationPlugin/assets/50064863/3e051700-aa3c-42cd-8f69-cc8e515a5126)
--postman测试
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/50064863/33beb7c8-00cc-4160-a9d7-abb243b3ac52)
--deepl api 官方依赖测试
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/50064863/0e17fc43-362b-48bc-b66e-002c1b3c9700)

期望：
可以正常使用deepl翻译

### 🏷 插件版本

3.5.0

### 🔁 翻译引擎

DeepL 翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Rachel Navarro
Subscription is active until April 5, 2024.
For educational use only.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins:
    com.alibaba.p3c.smartfox (2.1.1)
    MavenRunHelper (4.20.213.3714.1)
    cn.cloud.auto.restful.tool (1.4.5)
    cn.yiiguxing.plugin.translate (3.5.0)

Kotlin: 231-1.8.21-IJ9011.34
```

### 📋 堆栈跟踪

```plain text
--Idea的日志
2023-06-29 10:06:23,825 [ 637720]   WARN - #cn.yiiguxing.plugin.translate.trans.TranslateService - Translation error
cn.yiiguxing.plugin.translate.trans.TranslateException: DeepL 翻译[translate.deepl] :: 网络连接超时
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:12)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:56)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:179)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:118)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:112)
	at cn.yiiguxing.plugin.translate.util.Http.post$lambda$0(Http.kt:100)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:524)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:506)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:335)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:99)
	at cn.yiiguxing.plugin.translate.util.Http.post(Http.kt:70)
	at cn.yiiguxing.plugin.translate.trans.deepl.DeeplService.translate(DeeplService.kt:49)
	at cn.yiiguxing.plugin.translate.trans.deepl.DeeplTranslator.call(DeeplTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.deepl.DeeplTranslator.access$call(DeeplTranslator.kt:19)
	at cn.yiiguxing.plugin.translate.trans.deepl.DeeplTranslator$doTranslate$1.invoke(DeeplTranslator.kt:51)
	at cn.yiiguxing.plugin.translate.trans.deepl.DeeplTranslator$doTranslate$1.invoke(DeeplTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.deepl.DeeplTranslator.doTranslate(DeeplTranslator.kt:53)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:20)
	... 11 more
```

**Comment by YiiGuxing** [comment]
请检查 IDE 的网络配置，代理配置什么的，插件是通过 IDE 发的网络请求。

**Comment by MouXinyue** [comment]
找到问题了，因为我之前在Idea的vm配置里增加了-Didea.connection.timeout=5，导致超时时间太短了，把时间调大就好了。
