### ISSUE TITLE
Translation error[translate.ali]: 'java.io.OutputStream com.intellij.util.io.PathKt.outputStream$default(java.nio.file.Path, boolean, int, java.lang.Object)'

### ISSUE THREAD

**Issue by ruandashuai** [YiiGuxing/TranslationPlugin#3974]
### 📝 问题描述

使用阿里翻译，选词-->右键-->翻译，提示：翻译时出错。

我编写了java代码进行测试，用正确的AccessKey ID和AccessKey Secret调用了阿里翻译的API，可以正常使用。

插件3.5.0、3.4.1两个版本都已测试，都是相同的问题

### 🏷 插件版本

3.5.0、3.4.1

### 🔁 翻译引擎

阿里翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.2 EAP (Ultimate Edition)
Build #IU-232.8453.116, built on June 29, 2023
Runtime version: 17.0.7+7-b1000.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
```

### 📋 堆栈跟踪

```plain text
Translation error[translate.ali]: 'java.io.OutputStream com.intellij.util.io.PathKt.outputStream$default(java.nio.file.Path, boolean, int, java.lang.Object)'
  
  java.lang.NoSuchMethodError: 'java.io.OutputStream com.intellij.util.io.PathKt.outputStream$default(java.nio.file.Path, boolean, int, java.lang.Object)'
at cn.yiiguxing.plugin.translate.util.IOKt.writeSafe(IO.kt:24)
at cn.yiiguxing.plugin.translate.service.CacheService.putDiskCache(CacheService.kt:66)
at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:59)
at cn.yiiguxing.plugin.translate.trans.ali.AliTranslator.doTranslate(AliTranslator.kt:60)
at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:20)
at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:180)
at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)




request.txt内容：
Translator: translate.ali
Source language: 检测语言(auto)
Target language: 中文（简体）(zh-CN)
================ Request Text ================
Client
==============================================
```

**Comment by YiiGuxing** [comment]
2023.2 版本还没有适配
