### ISSUE TITLE
插件 Translation 中有异常（3.5.1）

### ISSUE THREAD

**Issue by ark-65** [YiiGuxing/TranslationPlugin#4060]
### 📝 问题描述

1. 鼠标右键选词不出「翻译」选项

### 🏷 插件版本

3.5.1

### 🔁 翻译引擎

谷歌翻译

### 💻 IDE及运行环境

```plain text
WebStorm 2023.1.4
Build #WS-231.9225.18, built on July 13, 2023
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
```

### 📋 堆栈跟踪

```plain text
com.intellij.diagnostic.PluginException: Cannot load class cn.yiiguxing.plugin.translate.action.TranslateRenderedDocSelectionAction (
  error: cn/yiiguxing/intellij/compat/action/UpdateInBackgroundCompatAction,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Translation, id=cn.yiiguxing.plugin.translate, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9225.18/WebStorm.app.plugins/TranslationPlugin, version=3.5.1, package=null, isBundled=false), packagePrefix=null, instanceId=119, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:325)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:172)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cn.yiiguxing.plugin.translate.action.TranslationPromoter$Companion$COMPARATOR$1.invoke(TranslationPromoter.kt:16)
	at cn.yiiguxing.plugin.translate.action.TranslationPromoter$Companion$COMPARATOR$1.invoke(TranslationPromoter.kt:14)
	at cn.yiiguxing.plugin.translate.action.TranslationPromoter.COMPARATOR$lambda$1(TranslationPromoter.kt:14)
	at java.base/java.util.Comparator.lambda$comparingInt$7b0bb60$1(Comparator.java:494)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sortWith(MutableCollectionsJVM.kt:42)
	at cn.yiiguxing.plugin.translate.action.TranslationPromoter.promote(TranslationPromoter.kt:10)
	at com.intellij.openapi.actionSystem.impl.Utils.rearrangeByPromoters(Utils.java:801)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$14(Utils.java:750)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1100)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:425)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:421)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$16(Utils.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$18(Utils.java:760)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$20(Utils.java:759)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: cn/yiiguxing/intellij/compat/action/UpdateInBackgroundCompatAction
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:268)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:112)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:233)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:183)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:320)
	... 42 more
Caused by: java.lang.ClassNotFoundException: cn.yiiguxing.intellij.compat.action.UpdateInBackgroundCompatAction PluginClassLoader(plugin=PluginDescriptor(name=Translation, id=cn.yiiguxing.plugin.translate, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9225.18/WebStorm.app.plugins/TranslationPlugin, version=3.5.1, package=null, isBundled=false), packagePrefix=null, instanceId=119, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 50 more
```

**Comment by YiiGuxing** [comment]
请问你是怎么安装插件的？

**Comment by ark-65** [comment]
从插件商店更新的

**Comment by ark-65** [comment]
从插件商店更新的

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月17日(星期一) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 插件 Translation 中有异常（3.5.1） (Issue #4060)





 
请问你是怎么安装插件的？

**Comment by YiiGuxing** [comment]
重启 IDE 能解决吗？

**Comment by YiiGuxing** [comment]
我能看一下这个目录下的文件吗？还有其子目录的：

~/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9225.18/WebStorm.app.plugins/TranslationPlugin

**Comment by ark-65** [comment]
一个不愿意透露姓名的赵铁柱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月17日(星期一) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 插件 Translation 中有异常（3.5.1） (Issue #4060)





 
我能看一下这个目录下的文件吗？还有其子目录的：
 
~/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/231.9225.18/WebStorm.app.plugins/TranslationPlugin

**Comment by YiiGuxing** [comment]
？？？

**Comment by ark-65** [comment]
[TranslationPlugin.zip](https://github.com/YiiGuxing/TranslationPlugin/files/12075023/TranslationPlugin.zip)

**Comment by ark-65** [comment]
昨天用邮件回复的。。。附件没发出来。。。。

**Comment by YiiGuxing** [comment]
如果你是从IDE内的插件页面安装的话，这个应该是IDE的BUG了，你安装后的包并不全，所以才会出现这个问题，你先把插件卸载掉，再重新安装试试。

请问你是从哪个版本升级上来导致出现这个问题的？我看看能不能复现，并返回给JetBrains的工程师。

**Comment by ark-65** [comment]
具体哪个版本升级上来的我也忘却了。
我把插件卸载然后重新安装后正常了，这应该和升级的时候包没有覆盖全导致的

**Comment by YiiGuxing** [comment]
能否请你提供一下IDE的日志吗？我要反馈给JetBrains的工程师。
日志收集：
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/10737066/d87d3226-f508-4188-a141-484f5a3effed)

**Comment by ark-65** [comment]
[webstorm-logs-20230718-1338418377925447744210058.zip](https://github.com/YiiGuxing/TranslationPlugin/files/12076563/webstorm-logs-20230718-1338418377925447744210058.zip)

**Comment by YiiGuxing** [comment]
感谢！

**Comment by YiiGuxing** [comment]
你好，你能详细说明一下你是怎么更新这个插件，从而导致这个问题的？是点击 IDE 内部插件商店页面的 “Update ”按钮吗？还是从插件商店网页下载下来安装的，还是说其他的方式？能提供一下具体的操作步骤吗？

**Comment by ark-65** [comment]
大概是这样的：
打开 IDE 之后，右下角提示有更新插件，我就点了个更新（多个插件同时更新，有 NPM Package Json，SonarLint），同时打开 plugins 查看更新进度，更行完成后提示我重启 IDE
重启之后就开始报错了
PS：NPM Package Json 的 next 版本刚好是个收费版，更新之后，这个插件也没了，变成了未安装状态

**Comment by YiiGuxing** [comment]
好的，感谢🙏
