### ISSUE TITLE
无法翻译，提示网络错误

### ISSUE THREAD

**Issue by JohanGt** [YiiGuxing/TranslationPlugin#4072]
### 📝 问题描述

翻译时出错，网络连接超时

### 🏷 插件版本

6.0

### 🔁 翻译引擎

有道翻译, 百度翻译

### 💻 IDE及运行环境

```plain text
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-b2043.56-9586694 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

**Comment by YiiGuxing** [comment]
请检查网络环境。

**Comment by JohanGt** [comment]
网络没问题，插件能正常安装，github能正常访问，之前在mac本上使用的AS版本是小蜜蜂正常的

**Comment by thiskiller** [comment]
> 

<img width="215" alt="image" src="https://github.com/YiiGuxing/TranslationPlugin/assets/59038634/6546185b-aa2a-40ab-a1fd-a2904f1a3095">


更新 TKK 失败，请检查网络连接

>Plugin v3.1.3+201u202  
>IntelliJ IDEA 2020.2.3  
>Build #IU-202.7660.26, built on October 6, 2020  
>Runtime version: 11.0.8+10-b944.34 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: macOS 10.15.7

```
cn.yiiguxing.plugin.translate.trans.NetworkException: Read timed out. host=translate.googleapis.com
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:89)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:55)
	at cn.yiiguxing.plugin.translate.trans.TKK.getValue(TK.kt:45)
	at cn.yiiguxing.plugin.translate.trans.TKKt.tk$default(TK.kt:116)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.getRequestUrl(GoogleTranslator.kt:81)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:82)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:467)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:461)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1403)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:606)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:57)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:376)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:385)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:439)
	at com.intellij.util.io.RequestBuilder.lambda$readString$3(RequestBuilder.java:78)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:78)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:69)
	... 18 more
```

**Comment by YiiGuxing** [comment]
@thiskiller #2315
