### ISSUE TITLE
有道云翻译不能用了，望修复

### ISSUE THREAD

**Issue by HelloWar** [YiiGuxing/TranslationPlugin#414]
有道云翻译不能用了，望修复
![image](https://user-images.githubusercontent.com/23720965/70682539-26587100-1cda-11ea-9c7e-bc4fbda1981d.png)

![image](https://user-images.githubusercontent.com/23720965/70682682-9535ca00-1cda-11ea-934c-16ad525b5894.png)

我调用了第三方的有道翻译接口，api没问题，故应该是插件问题，google翻译可以使用

**Comment by YiiGuxing** [comment]
请提供详细的错误信息

**Comment by YiiGuxing** [comment]
我这边是可以使用的

**Comment by HelloWar** [comment]
我用的是最新的idea，之前一直没升级，今天升级了idea和最新的plugin，后来发现google源可以使用，但是有道的不行了------------------ 原始邮件 ------------------
发件人: "Yii.Guxing"<notifications@github.com>
发送时间: 2019年12月12日(星期四) 中午12:37
收件人: "YiiGuxing/TranslationPlugin"<TranslationPlugin@noreply.github.com>;
抄送: "MrHC"<278571941@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [YiiGuxing/TranslationPlugin] 有道云翻译不能用了，望修复 (#414)



我这边是可以使用的
 
&mdash;

**Comment by HelloWar** [comment]
> 请提供详细的错误信息

您用的idea版本是多少，我的是2019.3

**Comment by YiiGuxing** [comment]
请另阅： #365

**Comment by HelloWar** [comment]
![image](https://user-images.githubusercontent.com/23720965/70763390-da1b3880-1d8e-11ea-8f0a-9d80f3d2146c.png)
您好，这个没有控制台报错，只是显示  翻译失败：服务器错误

**Comment by YiiGuxing** [comment]
...

获取错误信息的方法在FAQ里的最后一个问题：http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb
请按其方法获取并贴上。

**Comment by HelloWar** [comment]
>Plugin v2.6.1  
>IntelliJ IDEA 2019.3  
>Build #IU-193.5233.102, built on November 28, 2019  
>Runtime version: 11.0.4+10-b520.11 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Youdao Translate :: 翻译失败: 服务器异常
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:89)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Youdao Translate :: Translate failed: 303
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:90)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:63)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:518)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:500)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:68)
	... 7 more
```

**Comment by YiiGuxing** [comment]
这是有道服务器的异常，请检查一下有道的APP ID和KEY。
再不行的话请提供一下翻译日志：Help -> Show Log in Explorer -> 打开idea.log -> 搜索 `Translate url`
![image](https://user-images.githubusercontent.com/10737066/70770062-ddbab980-1da6-11ea-80e4-2a7b7d05c1b4.png)

然后提供`Translate url`

**Comment by HelloWar** [comment]
Translate url: https://openapi.youdao.com/api?appKey=462af25cf82ae251+&from=auto&to=auto&salt=ac35186b-7bb2-498d-b08c-1db769f8f451&sign=F148C59204C2D66AF8BF011C775C8E4E25BFBEA771B587937B3C2D02374D6A9D&signType=v3&curtime=1576122271&q=Request+Method

**Comment by HelloWar** [comment]
![image](https://user-images.githubusercontent.com/23720965/70770660-35f2bb00-1da9-11ea-91fe-b743d708901b.png)
我觉得应该是这个时间戳的问题

**Comment by YiiGuxing** [comment]
唉，有道的新的API无法重放，但我这边是没有问题的，那么我想应该是你那边应用服务状态可能有问题，请尝试一下在有道后台新建一个翻译应用和服务。

**Comment by YiiGuxing** [comment]
> 我觉得应该是这个时间戳的问题

不会，我这边都是可以成功翻译的。

**Comment by YiiGuxing** [comment]
你试一下使用`curtime=1576122271` 和 `q=Request Method`，生成一下翻译URL，看看生成的URL和上面你给的URL一不一样嘛

**Comment by YiiGuxing** [comment]
> 我觉得应该是这个时间戳的问题

你给的URL上的时间戳1576122271是昨天的啊，应该就是这个问题了，检查一下系统时间。

**Comment by HelloWar** [comment]
不是的，这条url的日志是昨天的

**Comment by HelloWar** [comment]
解决了，谢谢。
