### ISSUE TITLE
[Bug]由于原Rust插件已被弃用导致的Rust文档无法翻译

### ISSUE THREAD

**Issue by gtoxlili** [YiiGuxing/TranslationPlugin#4413]
### 📝 问题描述

在将 Rust 插件替换为 https://plugins.jetbrains.com/plugin/22407-rust 这个之后, Translation 就插件无法正确识别 Rust 文档了
![image](https://github.com/YiiGuxing/TranslationPlugin/assets/39382699/7e638ef7-9190-4421-a771-33ffa22177d0)

### 🏷 插件版本

3.5.4

### 🔁 翻译引擎

DeepL 翻译

### 💻 IDE及运行环境

```plain text
IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 13, 2023
For educational use only.
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-152-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
    run.processes.with.pty=false
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.intellij.zh (232.172)
    com.jetbrains.rust (232.9921.46)
    cn.yiiguxing.plugin.translate (3.5.4)

Kotlin: 232-1.9.0-IJ9921.47
Current Desktop: Pantheon
```

**Comment by TCeason** [comment]
Same question:

```
 Translation parsing failed[translate.google]: Parameter specified as non-null is null: method cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>, parameter terms
  
  java.lang.NullPointerException: Parameter specified as non-null is null: method cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>, parameter terms
at cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>(GoogleDictDocument.kt)
at cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Factory.getDocument(GoogleDictDocument.kt:49)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslation.toTranslation(GoogleTranslation.kt:61)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseTranslation(GoogleTranslator.kt:164)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseTranslation(GoogleTranslator.kt:21)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$2.invoke(GoogleTranslator.kt:67)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$2.invoke(GoogleTranslator.kt:67)
at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:52)
at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:68)
at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:20)
at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:129)
at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by YiiGuxing** [comment]
> Same question:
> 
> ```
>  Translation parsing failed[translate.google]: Parameter specified as non-null is null: method cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>, parameter terms
>   
>   java.lang.NullPointerException: Parameter specified as non-null is null: method cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>, parameter terms
> at cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>(GoogleDictDocument.kt)
> at cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Factory.getDocument(GoogleDictDocument.kt:49)
> at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslation.toTranslation(GoogleTranslation.kt:61)
> at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseTranslation(GoogleTranslator.kt:164)
> at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseTranslation(GoogleTranslator.kt:21)
> at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$2.invoke(GoogleTranslator.kt:67)
> at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$2.invoke(GoogleTranslator.kt:67)
> at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
> at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:52)
> at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:68)
> at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:20)
> at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:129)
> at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
> at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
> at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
> at java.base/java.lang.Thread.run(Thread.java:833)
> ```

@TCeason This is a different issue, you need to upgrade the plugin.

**Comment by TCeason** [comment]
> > Same question:
> > ```
> >  Translation parsing failed[translate.google]: Parameter specified as non-null is null: method cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>, parameter terms
> >   
> >   java.lang.NullPointerException: Parameter specified as non-null is null: method cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>, parameter terms
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Dict.<init>(GoogleDictDocument.kt)
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleDictDocument$Factory.getDocument(GoogleDictDocument.kt:49)
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslation.toTranslation(GoogleTranslation.kt:61)
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseTranslation(GoogleTranslator.kt:164)
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseTranslation(GoogleTranslator.kt:21)
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$2.invoke(GoogleTranslator.kt:67)
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$2.invoke(GoogleTranslator.kt:67)
> > at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
> > at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:52)
> > at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:68)
> > at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:20)
> > at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:129)
> > at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
> > at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> > at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> > at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
> > at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
> > at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> > at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
> > at java.base/java.lang.Thread.run(Thread.java:833)
> > ```
> 
> @TCeason This is a different issue, you need to upgrade the plugin.

It was fixed after the upgrade.
