### ISSUE TITLE
使用时插件频繁报错

### ISSUE THREAD

**Issue by EmptyDreams** [YiiGuxing/TranslationPlugin#491]
* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

把鼠标放到英语单词上的时候右下角弹错误

### Environment & Stack Trace
- Plugin version: 2.9.0
- IDE version:  IDEA 2020.1
- Operating System and version: Windows 10
- Stack Trace:
`cn.yiiguxing.plugin.translate.trans.TranslateException: Youdao Translate :: 翻译失败: 未知错误[113]
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:231)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:173)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Youdao Translate :: Translate failed: 113
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:90)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 6 more`

**Comment by YiiGuxing** [comment]
这是文档翻译中的一个小问题，可以暂时关闭文档翻译，等待下一个版本的发布

**Comment by superdevops-cn** [comment]
v2.9.2出现同样的错误

**Comment by YiiGuxing** [comment]
@superdevops-cn 你的应该不是同样问题，你可以贴出你的错误信息。

**Comment by superdevops-cn** [comment]
> @superdevops-cn 你的应该不是同样问题，你可以贴出你的错误信息。

今早测试已经能正常使用，等待下次出现错误贴出报错信息，谢谢！

**Comment by superdevops-cn** [comment]
> @superdevops-cn 你的应该不是同样问题，你可以贴出你的错误信息。
今早已经能正常使用，后续若有同样错误，我再贴出来，谢谢您
