### ISSUE TITLE
翻译失败: 缺少必填的参数

### ISSUE THREAD

**Issue by w-ji-ang** [YiiGuxing/TranslationPlugin#492]
Failed to translate documentation: 翻译失败: 缺少必填的参数

>Plugin v2.9.0  
>IntelliJ IDEA 2020.1.1  
>Build #IU-201.7223.91, built on April 30, 2020  
>Runtime version: 11.0.6+8-b765.40 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: 翻译失败: 缺少必填的参数
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:231)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:173)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Baidu Translate :: Translate failed: 54000
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:102)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 6 more
```

**Comment by YiiGuxing** [comment]
已修复，见 #491
