### ISSUE TITLE
百度翻译失败: 缺少必填的参数

### ISSUE THREAD

**Issue by xufan930** [YiiGuxing/TranslationPlugin#500]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Description
我用的是百度翻译,如果把鼠标指向某些类时或者手动CTRL+Q时后报错.例如BigDecimal或者是我自己写的类.
15:42	Documentation
			Failed to translate documentation: 翻译失败: 缺少必填的参数
			Copy to Clipboard

### Environment & Stack Trace
- Plugin version: 2.9
- IDE version:  IDEA 2020.1.1
- Operating System and version:  Windows 10 
- Stack Trace:
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:231)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:173)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Unknown language code:nor
	at cn.yiiguxing.plugin.translate.trans.Lang$Companion.valueOfBaiduCode(Languages.kt:284)
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslation.toTranslation(BaiduTranslation.kt:25)
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 6 more

**Comment by YiiGuxing** [comment]
#492
