### ISSUE TITLE
百度翻译Request-URI Too Long

### ISSUE THREAD

**Issue by xufan930** [YiiGuxing/TranslationPlugin#502]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

### Description
如果鼠标放到BigDecimal上就会报错
9:32	Documentation
			Failed to translate documentation: 翻译失败: Request-URI Too Long
			Copy to Clipboard

### Environment & Stack Trace
- Plugin version: 2.9.1
- IDE version: IDEA 2020.1.1
- Operating System and version: Windows 10 
- Stack Trace:
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: 翻译失败: Request-URI Too Long
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:242)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:178)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 414. Status=414, Url=http://api.fanyi.baidu.com/api/trans/vip/translate?appid=敏感信息&from=auto&to=zh&salt=1589851285313&sign=1fde46ee1260f227ffd5e4f68a28c0eb&q=Immutable%2C+arbitrary-precision+signed+decimal+numbers.+A+BigDecimal+consists+of+an+arbitrary+precision+integer+unscaled+value+and+a+32-bit+integer+scale.+If+zero+or+positive%2C+the+scale+is+the+number+of+digits+to+the+right+of+the+decimal+point.+If+negative%2C+the+unscaled+value+of+the+number+is+multiplied+by+ten+to+the+power+of+the+negation+of+the+scale.+The+value+of+the+number+represented+by+the+BigDecimal+is+therefore+%28unscaledValue+%C3%97+10-scale%29.%0AThe+BigDecimal+class+provides+operations+for+arithmetic%2C+scale+manipulation%2C+rounding%2C+comparison%2C+hashing%2C+and+format+conversion.+The+toString+method+provides+a+canonical+representation+of+a+BigDecimal.%0AThe+BigDecimal+class+gives+its+user+complete+control+over+rounding+behavior.+If+no+rounding+mode+is+specified+and+the+exact+result+cannot+be+represented%2C+an+exception+is+thrown%3B+otherwise%2C+calculations+can+be+carried+out+to+a+chosen+precision+and+rounding+mode+by+supplying+an+appropriate+MathContext+object+to+the+operation.+In+either+case%2C+eight+rounding+modes+are+provided+for+the+control+of+rounding.+Using+the+integer+fields+in+this+class+%28such+as+ROUND_HALF_UP%29+to+represent+rounding+mode+is+largely+obsolete%3B+the+enumeration+values+of+the+RoundingMode+enum%2C+%28such+as+RoundingMode.HALF_UP%29+should+be+used+instead.%0AWhen+a+MathContext+object+is+supplied+with+a+precision+setting+of+0+%28for+example%2C+MathContext.UNLIMITED%29%2C+arithmetic+operations+are+exact%2C+as+are+the+arithmetic+methods+which+take+no+MathContext+object.+%28This+is+the+only+behavior+that+was+supported+in+releases+prior+to+5.%29+As+a+corollary+of+computing+the+exact+result%2C+the+rounding+mode+setting+of+a+MathContext+object+with+a+precision+setting+of+0+is+not+used+and+thus+irrelevant.+In+the+case+of+divide%2C+the+exact+quotient+could+have+an+infinitely+long+decimal+expansion%3B+for+example%2C+1+divided+by+3.+If+the+quotient+has+a+nonterminating+decimal+expansion+and+the+operation+is+specified+to+return+an+exact+result%2C+an+ArithmeticException+is+thrown.+Otherwise%2C+the+exact+result+of+the+division+is+returned%2C+as+done+for+other+operations.%0AWhen+the+precision+setting+is+not+0%2C+the+rules+of+BigDecimal+arithmetic+are+broadly+compatible+with+selected+modes+of+operation+of+the+arithmetic+defined+in+ANSI+X3.274-1996+and+ANSI+X3.274-1996%2FAM+1-2000+%28section+7.4%29.+Unlike+those+standards%2C+BigDecimal+includes+many+rounding+modes%2C+which+were+mandatory+for+division+in+BigDecimal+releases+prior+to+5.+Any+conflicts+between+these+ANSI+standards+and+the+BigDecimal+specification+are+resolved+in+favor+of+BigDecimal.%0ASince+the+same+numerical+value+can+have+different+representations+%28with+different+scales%29%2C+the+rules+of+arithmetic+and+rounding+must+specify+both+the+numerical+result+and+the+scale+used+in+the+result%27s+representation.%0AIn+general+the+rounding+modes+and+precision+setting+determine+how+operations+return+results+with+a+limited+number+of+digits+when+the+exact+result+has+more+digits+%28perhaps+infinitely+many+in+the+case+of+division%29+than+the+number+of+digits+returned.+First%2C+the+total+number+of+digits+to+return+is+specified+by+the+MathContext%27s+precision+setting%3B+this+determines+the+result%27s+precision.+The+digit+count+starts+from+the+leftmost+nonzero+digit+of+the+exact+result.+The+rounding+mode+determines+how+any+discarded+trailing+digits+affect+the+returned+result.%0AFor+all+arithmetic+operators+%2C+the+operation+is+carried+out+as+though+an+exact+intermediate+result+were+first+calculated+and+then+rounded+to+the+number+of+digits+specified+by+the+precision+setting+%28if+necessary%29%2C+using+the+selected+rounding+mode.+If+the+exact+result+is+not+returned%2C+some+digit+positions+of+the+exact+result+are+discarded.+When+rounding+increases+the+magnitude+of+the+returned+result%2C+it+is+possible+for+a+new+digit+position+to+be+created+by+a+carry+propagating+to+a+leading+%229%22+digit.+For+example%2C+rounding+the+value+999.9+to+three+digits+rounding+up+would+be+numerically+equal+to+one+thousand%2C+represented+as+100%C3%97101.+In+such+cases%2C+the+new+%221%22+is+the+leading+digit+position+of+the+returned+result.%0ABesides+a+logical+exact+result%2C+each+arithmetic+operation+has+a+preferred+scale+for+representing+a+result.+The+preferred+scale+for+each+operation+is+listed+in+the+table+below.%0APreferred+Scales+for+Results+of+Arithmetic+Operations%0AOperation%0APreferred+Scale+of+Result%0AAdd%0Amax%28addend.scale%28%29%2C+augend.scale%28%29%29%0ASubtract%0Amax%28minuend.scale%28%29%2C+subtrahend.scale%28%29%29%0AMultiply%0Amultiplier.scale%28%29+%2B+multiplicand.scale%28%29%0ADivide%0Adividend.scale%28%29+-+divisor.scale%28%29%0AThese+scales+are+the+ones+used+by+the+methods+which+return+exact+arithmetic+results%3B+except+that+an+exact+divide+may+have+to+use+a+larger+scale+since+the+exact+result+may+have+more+digits.+For+example%2C+1%2F32+is+0.03125.%0ABefore+rounding%2C+the+scale+of+the+logical+exact+intermediate+result+is+the+preferred+scale+for+that+operation.+If+the+exact+numerical+result+cannot+be+represented+in+precision+digits%2C+rounding+selects+the+set+of+digits+to+return+and+the+scale+of+the+result+is+reduced+from+the+scale+of+the+intermediate+result+to+the+least+scale+which+can+represent+the+precision+digits+actually+returned.+If+the+exact+result+can+be+represented+with+at+most+precision+digits%2C+the+representation+of+the+result+with+the+scale+closest+to+the+preferred+scale+is+returned.+In+particular%2C+an+exactly+representable+quotient+may+be+represented+in+fewer+than+precision+digits+by+removing+trailing+zeros+and+decreasing+the+scale.+For+example%2C+rounding+to+three+digits+using+the+floor+rounding+mode%2C+19%2F100+%3D+0.19+%2F%2F+integer%3D19%2C+scale%3D2+but+21%2F110+%3D+0.190+%2F%2F+integer%3D190%2C+scale%3D3+%0ANote+that+for+add%2C+subtract%2C+and+multiply%2C+the+reduction+in+scale+will+equal+the+number+of+digit+positions+of+the+exact+result+which+are+discarded.+If+the+rounding+causes+a+carry+propagation+to+create+a+new+high-order+digit+position%2C+an+additional+digit+of+the+result+is+discarded+than+when+no+new+digit+position+is+created.%0AOther+methods+may+have+slightly+different+rounding+semantics.+For+example%2C+the+result+of+the+pow+method+using+the+specified+algorithm+can+occasionally+differ+from+the+rounded+mathematical+result+by+more+than+one+unit+in+the+last+place%2C+one+ulp.%0ATwo+types+of+operations+are+provided+for+manipulating+the+scale+of+a+BigDecimal%3A+scaling%2Frounding+operations+and+decimal+point+motion+operations.+Scaling%2Frounding+operations+%28setScale+and+round%29+return+a+BigDecimal+whose+value+is+approximately+%28or+exactly%29+equal+to+that+of+the+operand%2C+but+whose+scale+or+precision+is+the+specified+value%3B+that+is%2C+they+increase+or+decrease+the+precision+of+the+stored+number+with+minimal+effect+on+its+value.+Decimal+point+motion+operations+%28movePointLeft+and+movePointRight%29+return+a+BigDecimal+created+from+the+operand+by+moving+the+decimal+point+a+specified+distance+in+the+specified+direction.%0AFor+the+sake+of+brevity+and+clarity%2C+pseudo-code+is+used+throughout+the+descriptions+of+BigDecimal+methods.+The+pseudo-code+expression+%28i+%2B+j%29+is+shorthand+for+%22a+BigDecimal+whose+value+is+that+of+the+BigDecimal+i+added+to+that+of+the+BigDecimal+j.%22+The+pseudo-code+expression+%28i+%3D%3D+j%29+is+shorthand+for+%22true+if+and+only+if+the+BigDecimal+i+represents+the+same+value+as+the+BigDecimal+j.%22+Other+pseudo-code+expressions+are+interpreted+similarly.+Square+brackets+are+used+to+represent+the+particular+BigInteger+and+scale+pair+defining+a+BigDecimal+value%3B+for+example+%5B19%2C+2%5D+is+the+BigDecimal+numerically+equal+to+0.19+having+a+scale+of+2.%0ANote%3A+care+should+be+exercised+if+BigDecimal+objects+are+used+as+keys+in+a+SortedMap+or+elements+in+a+SortedSet+since+BigDecimal%27s+natural+ordering+is+inconsistent+with+equals.+See+Comparable%2C+java.util.SortedMap+or+java.util.SortedSet+for+more+information.%0AAll+methods+and+constructors+for+this+class+throw+NullPointerException+when+passed+a+null+object+reference+for+any+input+parameter.%0A%0ASee+Also%3A%0ABigInteger%2C+MathContext%2C+RoundingMode%2C+java.util.SortedMap%2C+java.util.SortedSet
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:643)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:624)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:375)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:384)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:438)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 6 more

**Comment by YiiGuxing** [comment]
将在3.0版本得到修复（仅2019.3以上的IDE版本可用）。

见：https://github.com/YiiGuxing/TranslationPlugin/commit/a77c0fdcae1a050aa9a2f1648d29b17b51c6e317
