### ISSUE TITLE
java.lang.NoSuchFieldError: BalloonClose

### ISSUE THREAD

**Issue by FoxCATT** [YiiGuxing/TranslationPlugin#514]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]* 

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem. 
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 

## Issue Details
NoSuchFieldError: BalloonClose
### Description

Last Action: $EditorTranslateAction 

### Environment & Stack Trace
- Plugin version: Translation version: 2.5.1 
- IDE version: IntelliJ IDEA 2020.1.1  Build #IU-201.7223.91 
- Operating System and version:  Windows 10 
- Stack Trace:
```log
2020-05-30 18:26:31,347 [2283267]  ERROR - llij.ide.plugins.PluginManager - BalloonClose 
java.lang.NoSuchFieldError: BalloonClose
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.getCloseButton(BalloonImpl.java:1051)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl$CloseButton.<init>(BalloonImpl.java:1602)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl$CloseButton.<init>(BalloonImpl.java:1600)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl$7.createActions(BalloonImpl.java:707)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl$MyComponent._setBounds(BalloonImpl.java:1845)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl$AbstractPosition.updateBounds(BalloonImpl.java:1097)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.createComponent(BalloonImpl.java:740)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.show(BalloonImpl.java:561)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.show(BalloonImpl.java:442)
	at cn.yiiguxing.plugin.translate.ui.TranslationBalloon.show(TranslationBalloon.kt:216)
	at cn.yiiguxing.plugin.translate.TranslationUIManager.showBalloon(TranslationUIManager.kt:57)
	at cn.yiiguxing.plugin.translate.action.TranslateAction.onActionPerformed(TranslateAction.kt:43)
	at cn.yiiguxing.plugin.translate.action.AutoSelectAction.actionPerformed(AutoSelectAction.kt:56)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-05-30 18:26:31,347 [2283267]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.1.1  Build #IU-201.7223.91 
2020-05-30 18:26:31,347 [2283267]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-05-30 18:26:31,347 [2283267]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2020-05-30 18:26:31,347 [2283267]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Translation version: 2.5.1 
2020-05-30 18:26:31,347 [2283267]  ERROR - llij.ide.plugins.PluginManager - Last Action: $EditorTranslateAction 
```

**Comment by YiiGuxing** [comment]
Please upgrade the plugin to the latest version.
