### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by qinbo1022** [YiiGuxing/TranslationPlugin#519]
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: **Too Many Requests**
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:89)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 429. Status=429, Url=https://translate.google.cn/translate_a/single?sl=auto&tl=zh-CN&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dj=1&ie=UTF-8&oe=UTF-8&hl=zh-CN&tk=628485.993724&q=strange+Message+Map
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:649)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:392)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:447)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:63)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:528)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:504)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:357)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:68)
	... 7 more

**Comment by qinbo1022** [comment]
实际上没有翻译几个单词，另外chrome安装了simple translate插件也会提示：达到服务器使用限制

**Comment by YiiGuxing** [comment]
这个就没有办法了，谷歌翻译服务限制了你的IP。。。

**Comment by qinbo1022** [comment]
> 这个就没有办法了，谷歌翻译服务限制了你的IP。。。我无能为力

好的，我知道了，谢谢

**Comment by YiiGuxing** [comment]
会不会是因为开启了自动文档翻译，导致翻译次数过多，过于频繁？可以尝试关掉文档翻译试试。

**Comment by qinbo1022** [comment]
> 会不会是因为开启了自动文档翻译，导致翻译次数过多，过多超过？可以尝试关掉文档翻译试试。

请问这个功能是默认开启的吗，我并没有单独设置过

**Comment by YiiGuxing** [comment]
是默认开启的

**Comment by qinbo1022** [comment]
> 是默认开启的

已经关掉了，但暂时无法看到是否生效，下周反馈

**Comment by qinbo1022** [comment]
已经确定是ip被限制了，与自动翻译无关

**Comment by Smliences** [comment]
后续要怎么办，我刚也遇到这个问题，吐了呀

**Comment by Smliences** [comment]
> 已经确定是ip被限制了，与自动翻译无关

后续要怎么办，我刚刚也碰到了这个问题

**Comment by qinbo1022** [comment]
> > 已经确定是ip被限制了，与自动翻译无关
> 
> 后续要怎么办，我刚刚也碰到了这个问题

换用另一个插件

**Comment by YiiGuxing** [comment]
@Smliences 可以先使用有道和百度的，也不知道谷歌会不会解封。
