### ISSUE TITLE
翻译请求数据太大报错

### ISSUE THREAD

**Issue by Varian-Wrynn** [YiiGuxing/TranslationPlugin#521]
Failed to translate documentation: 翻译失败: Request Entity Too Large

>Plugin v2.9.1  
>IntelliJ IDEA 2020.1.2  
>Build #IU-201.7846.76, built on June 1, 2020  
>Runtime version: 11.0.7+10-b765.53 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: macOS 10.15.5

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: Request Entity Too Large
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:205)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:176)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 413. Status=413, Url=https://translate.google.cn/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=413379.61891&q=%3Cdiv+class%3D%22content%22%3E%0A++An+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ExecutorService%22%3E%3Ccode%3EExecutorService%3C%2Fcode%3E%3C%2Fa%3E+that+executes+each+submitted+task+using+one+of+possibly+several+pooled+threads%2C+normally+configured+using+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.Executors%22%3E%3Ccode%3EExecutors%3C%2Fcode%3E%3C%2Fa%3E+factory+methods.+%0A+%3Cp%3EThread+pools+address+two+different+problems%3A+they+usually+provide+improved+performance+when+executing+large+numbers+of+asynchronous+tasks%2C+due+to+reduced+per-task+invocation+overhead%2C+and+they+provide+a+means+of+bounding+and+managing+the+resources%2C+including+threads%2C+consumed+when+executing+a+collection+of+tasks.+Each+%3Ccode%3EThreadPoolExecutor%3C%2Fcode%3E+also+maintains+some+basic+statistics%2C+such+as+the+number+of+completed+tasks.+%3C%2Fp%3E%0A+%3Cp%3ETo+be+useful+across+a+wide+range+of+contexts%2C+this+class+provides+many+adjustable+parameters+and+extensibility+hooks.+However%2C+programmers+are+urged+to+use+the+more+convenient+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.Executors%22%3E%3Ccode%3EExecutors%3C%2Fcode%3E%3C%2Fa%3E+factory+methods+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.Executors%23newCachedThreadPool%28%29%22%3E%3Ccode%3EExecutors.newCachedThreadPool%3C%2Fcode%3E%3C%2Fa%3E+%28unbounded+thread+pool%2C+with+automatic+thread+reclamation%29%2C+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.Executors%23newFixedThreadPool%28int%29%22%3E%3Ccode%3EExecutors.newFixedThreadPool%3C%2Fcode%3E%3C%2Fa%3E+%28fixed+size+thread+pool%29+and+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.Executors%23newSingleThreadExecutor%28%29%22%3E%3Ccode%3EExecutors.newSingleThreadExecutor%3C%2Fcode%3E%3C%2Fa%3E+%28single+background+thread%29%2C+that+preconfigure+settings+for+the+most+common+usage+scenarios.+Otherwise%2C+use+the+following+guide+when+manually+configuring+and+tuning+this+class%3A+%3C%2Fp%3E%0A+%3Cdl%3E+%0A++%3Cdt%3E%0A+++Core+and+maximum+pool+sizes%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++A+%3Ccode%3EThreadPoolExecutor%3C%2Fcode%3E+will+automatically+adjust+the+pool+size+%28see+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23getPoolSize%28%29%22%3E%3Ccode%3EgetPoolSize%3C%2Fcode%3E%3C%2Fa%3E%29+according+to+the+bounds+set+by+corePoolSize+%28see+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23getCorePoolSize%28%29%22%3E%3Ccode%3EgetCorePoolSize%3C%2Fcode%3E%3C%2Fa%3E%29+and+maximumPoolSize+%28see+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23getMaximumPoolSize%28%29%22%3E%3Ccode%3EgetMaximumPoolSize%3C%2Fcode%3E%3C%2Fa%3E%29.+When+a+new+task+is+submitted+in+method+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23execute%28java.lang.Runnable%29%22%3E%3Ccode%3Eexecute%28Runnable%29%3C%2Fcode%3E%3C%2Fa%3E%2C+and+fewer+than+corePoolSize+threads+are+running%2C+a+new+thread+is+created+to+handle+the+request%2C+even+if+other+worker+threads+are+idle.+If+there+are+more+than+corePoolSize+but+less+than+maximumPoolSize+threads+running%2C+a+new+thread+will+be+created+only+if+the+queue+is+full.+By+setting+corePoolSize+and+maximumPoolSize+the+same%2C+you+create+a+fixed-size+thread+pool.+By+setting+maximumPoolSize+to+an+essentially+unbounded+value+such+as+%3Ccode%3EInteger.MAX_VALUE%3C%2Fcode%3E%2C+you+allow+the+pool+to+accommodate+an+arbitrary+number+of+concurrent+tasks.+Most+typically%2C+core+and+maximum+pool+sizes+are+set+only+upon+construction%2C+but+they+may+also+be+changed+dynamically+using+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23setCorePoolSize%28int%29%22%3E%3Ccode%3EsetCorePoolSize%3C%2Fcode%3E%3C%2Fa%3E+and+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23setMaximumPoolSize%28int%29%22%3E%3Ccode%3EsetMaximumPoolSize%3C%2Fcode%3E%3C%2Fa%3E.+%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++On-demand+construction%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++By+default%2C+even+core+threads+are+initially+created+and+started+only+when+new+tasks+arrive%2C+but+this+can+be+overridden+dynamically+using+method+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23prestartCoreThread%28%29%22%3E%3Ccode%3EprestartCoreThread%3C%2Fcode%3E%3C%2Fa%3E+or+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23prestartAllCoreThreads%28%29%22%3E%3Ccode%3EprestartAllCoreThreads%3C%2Fcode%3E%3C%2Fa%3E.+You+probably+want+to+prestart+threads+if+you+construct+the+pool+with+a+non-empty+queue.+%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++Creating+new+threads%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++New+threads+are+created+using+a+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadFactory%22%3E%3Ccode%3EThreadFactory%3C%2Fcode%3E%3C%2Fa%3E.+If+not+otherwise+specified%2C+a+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.Executors%23defaultThreadFactory%28%29%22%3E%3Ccode%3EExecutors.defaultThreadFactory%3C%2Fcode%3E%3C%2Fa%3E+is+used%2C+that+creates+threads+to+all+be+in+the+same+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.lang.ThreadGroup%22%3E%3Ccode%3EThreadGroup%3C%2Fcode%3E%3C%2Fa%3E+and+with+the+same+%3Ccode%3ENORM_PRIORITY%3C%2Fcode%3E+priority+and+non-daemon+status.+By+supplying+a+different+ThreadFactory%2C+you+can+alter+the+thread%27s+name%2C+thread+group%2C+priority%2C+daemon+status%2C+etc.+If+a+%3Ccode%3EThreadFactory%3C%2Fcode%3E+fails+to+create+a+thread+when+asked+by+returning+null+from+%3Ccode%3EnewThread%3C%2Fcode%3E%2C+the+executor+will+continue%2C+but+might+not+be+able+to+execute+any+tasks.+Threads+should+possess+the+%22modifyThread%22+%3Ccode%3ERuntimePermission%3C%2Fcode%3E.+If+worker+threads+or+other+threads+using+the+pool+do+not+possess+this+permission%2C+service+may+be+degraded%3A+configuration+changes+may+not+take+effect+in+a+timely+manner%2C+and+a+shutdown+pool+may+remain+in+a+state+in+which+termination+is+possible+but+not+completed.%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++Keep-alive+times%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++If+the+pool+currently+has+more+than+corePoolSize+threads%2C+excess+threads+will+be+terminated+if+they+have+been+idle+for+more+than+the+keepAliveTime+%28see+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23getKeepAliveTime%28java.util.concurrent.TimeUnit%29%22%3E%3Ccode%3EgetKeepAliveTime%28TimeUnit%29%3C%2Fcode%3E%3C%2Fa%3E%29.+This+provides+a+means+of+reducing+resource+consumption+when+the+pool+is+not+being+actively+used.+If+the+pool+becomes+more+active+later%2C+new+threads+will+be+constructed.+This+parameter+can+also+be+changed+dynamically+using+method+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23setKeepAliveTime%28long%2C+java.util.concurrent.TimeUnit%29%22%3E%3Ccode%3EsetKeepAliveTime%28long%2C+TimeUnit%29%3C%2Fcode%3E%3C%2Fa%3E.+Using+a+value+of+%3Ccode%3ELong.MAX_VALUE%3C%2Fcode%3E+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.TimeUnit%23NANOSECONDS%22%3E%3Ccode%3ETimeUnit.NANOSECONDS%3C%2Fcode%3E%3C%2Fa%3E+effectively+disables+idle+threads+from+ever+terminating+prior+to+shut+down.+By+default%2C+the+keep-alive+policy+applies+only+when+there+are+more+than+corePoolSize+threads.+But+method+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23allowCoreThreadTimeOut%28boolean%29%22%3E%3Ccode%3EallowCoreThreadTimeOut%28boolean%29%3C%2Fcode%3E%3C%2Fa%3E+can+be+used+to+apply+this+time-out+policy+to+core+threads+as+well%2C+so+long+as+the+keepAliveTime+value+is+non-zero.+%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++Queuing%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++Any+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.BlockingQueue%22%3E%3Ccode%3EBlockingQueue%3C%2Fcode%3E%3C%2Fa%3E+may+be+used+to+transfer+and+hold+submitted+tasks.+The+use+of+this+queue+interacts+with+pool+sizing%3A+%0A+++%3Cul%3E+%0A++++%3Cli%3E+If+fewer+than+corePoolSize+threads+are+running%2C+the+Executor+always+prefers+adding+a+new+thread+rather+than+queuing.%3C%2Fli%3E+%0A++++%3Cli%3E+If+corePoolSize+or+more+threads+are+running%2C+the+Executor+always+prefers+queuing+a+request+rather+than+adding+a+new+thread.%3C%2Fli%3E+%0A++++%3Cli%3E+If+a+request+cannot+be+queued%2C+a+new+thread+is+created+unless+this+would+exceed+maximumPoolSize%2C+in+which+case%2C+the+task+will+be+rejected.%3C%2Fli%3E+%0A+++%3C%2Ful%3E+There+are+three+general+strategies+for+queuing%3A+%0A+++%3Col%3E+%0A++++%3Cli%3E+%3Cem%3E+Direct+handoffs.%3C%2Fem%3E+A+good+default+choice+for+a+work+queue+is+a+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.SynchronousQueue%22%3E%3Ccode%3ESynchronousQueue%3C%2Fcode%3E%3C%2Fa%3E+that+hands+off+tasks+to+threads+without+otherwise+holding+them.+Here%2C+an+attempt+to+queue+a+task+will+fail+if+no+threads+are+immediately+available+to+run+it%2C+so+a+new+thread+will+be+constructed.+This+policy+avoids+lockups+when+handling+sets+of+requests+that+might+have+internal+dependencies.+Direct+handoffs+generally+require+unbounded+maximumPoolSizes+to+avoid+rejection+of+new+submitted+tasks.+This+in+turn+admits+the+possibility+of+unbounded+thread+growth+when+commands+continue+to+arrive+on+average+faster+than+they+can+be+processed.+%3C%2Fli%3E+%0A++++%3Cli%3E%3Cem%3E+Unbounded+queues.%3C%2Fem%3E+Using+an+unbounded+queue+%28for+example+a+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.LinkedBlockingQueue%22%3E%3Ccode%3ELinkedBlockingQueue%3C%2Fcode%3E%3C%2Fa%3E+without+a+predefined+capacity%29+will+cause+new+tasks+to+wait+in+the+queue+when+all+corePoolSize+threads+are+busy.+Thus%2C+no+more+than+corePoolSize+threads+will+ever+be+created.+%28And+the+value+of+the+maximumPoolSize+therefore+doesn%27t+have+any+effect.%29+This+may+be+appropriate+when+each+task+is+completely+independent+of+others%2C+so+tasks+cannot+affect+each+others+execution%3B+for+example%2C+in+a+web+page+server.+While+this+style+of+queuing+can+be+useful+in+smoothing+out+transient+bursts+of+requests%2C+it+admits+the+possibility+of+unbounded+work+queue+growth+when+commands+continue+to+arrive+on+average+faster+than+they+can+be+processed.+%3C%2Fli%3E+%0A++++%3Cli%3E%3Cem%3EBounded+queues.%3C%2Fem%3E+A+bounded+queue+%28for+example%2C+an+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ArrayBlockingQueue%22%3E%3Ccode%3EArrayBlockingQueue%3C%2Fcode%3E%3C%2Fa%3E%29+helps+prevent+resource+exhaustion+when+used+with+finite+maximumPoolSizes%2C+but+can+be+more+difficult+to+tune+and+control.+Queue+sizes+and+maximum+pool+sizes+may+be+traded+off+for+each+other%3A+Using+large+queues+and+small+pools+minimizes+CPU+usage%2C+OS+resources%2C+and+context-switching+overhead%2C+but+can+lead+to+artificially+low+throughput.+If+tasks+frequently+block+%28for+example+if+they+are+I%2FO+bound%29%2C+a+system+may+be+able+to+schedule+time+for+more+threads+than+you+otherwise+allow.+Use+of+small+queues+generally+requires+larger+pool+sizes%2C+which+keeps+CPUs+busier+but+may+encounter+unacceptable+scheduling+overhead%2C+which+also+decreases+throughput.+%3C%2Fli%3E+%0A+++%3C%2Fol%3E+%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++Rejected+tasks%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++New+tasks+submitted+in+method+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23execute%28java.lang.Runnable%29%22%3E%3Ccode%3Eexecute%28Runnable%29%3C%2Fcode%3E%3C%2Fa%3E+will+be+%3Cem%3Erejected%3C%2Fem%3E+when+the+Executor+has+been+shut+down%2C+and+also+when+the+Executor+uses+finite+bounds+for+both+maximum+threads+and+work+queue+capacity%2C+and+is+saturated.+In+either+case%2C+the+%3Ccode%3Eexecute%3C%2Fcode%3E+method+invokes+the+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.RejectedExecutionHandler%23rejectedExecution%28java.lang.Runnable%2C+java.util.concurrent.ThreadPoolExecutor%29%22%3E%3Ccode%3ERejectedExecutionHandler.rejectedExecution%28Runnable%2C+ThreadPoolExecutor%29%3C%2Fcode%3E%3C%2Fa%3E+method+of+its+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.RejectedExecutionHandler%22%3E%3Ccode%3ERejectedExecutionHandler%3C%2Fcode%3E%3C%2Fa%3E.+Four+predefined+handler+policies+are+provided%3A+%0A+++%3Col%3E+%0A++++%3Cli%3E+In+the+default+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor.AbortPolicy%22%3E%3Ccode%3EThreadPoolExecutor.AbortPolicy%3C%2Fcode%3E%3C%2Fa%3E%2C+the+handler+throws+a+runtime+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.RejectedExecutionException%22%3E%3Ccode%3ERejectedExecutionException%3C%2Fcode%3E%3C%2Fa%3E+upon+rejection.+%3C%2Fli%3E+%0A++++%3Cli%3E+In+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor.CallerRunsPolicy%22%3E%3Ccode%3EThreadPoolExecutor.CallerRunsPolicy%3C%2Fcode%3E%3C%2Fa%3E%2C+the+thread+that+invokes+%3Ccode%3Eexecute%3C%2Fcode%3E+itself+runs+the+task.+This+provides+a+simple+feedback+control+mechanism+that+will+slow+down+the+rate+that+new+tasks+are+submitted.+%3C%2Fli%3E+%0A++++%3Cli%3E+In+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor.DiscardPolicy%22%3E%3Ccode%3EThreadPoolExecutor.DiscardPolicy%3C%2Fcode%3E%3C%2Fa%3E%2C+a+task+that+cannot+be+executed+is+simply+dropped.+%3C%2Fli%3E+%0A++++%3Cli%3EIn+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor.DiscardOldestPolicy%22%3E%3Ccode%3EThreadPoolExecutor.DiscardOldestPolicy%3C%2Fcode%3E%3C%2Fa%3E%2C+if+the+executor+is+not+shut+down%2C+the+task+at+the+head+of+the+work+queue+is+dropped%2C+and+then+execution+is+retried+%28which+can+fail+again%2C+causing+this+to+be+repeated.%29+%3C%2Fli%3E+%0A+++%3C%2Fol%3E+It+is+possible+to+define+and+use+other+kinds+of+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.RejectedExecutionHandler%22%3E%3Ccode%3ERejectedExecutionHandler%3C%2Fcode%3E%3C%2Fa%3E+classes.+Doing+so+requires+some+care+especially+when+policies+are+designed+to+work+only+under+particular+capacity+or+queuing+policies.+%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++Hook+methods%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++This+class+provides+%3Ccode%3Eprotected%3C%2Fcode%3E+overridable+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23beforeExecute%28java.lang.Thread%2C+java.lang.Runnable%29%22%3E%3Ccode%3EbeforeExecute%28Thread%2C+Runnable%29%3C%2Fcode%3E%3C%2Fa%3E+and+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23afterExecute%28java.lang.Runnable%2C+java.lang.Throwable%29%22%3E%3Ccode%3EafterExecute%28Runnable%2C+Throwable%29%3C%2Fcode%3E%3C%2Fa%3E+methods+that+are+called+before+and+after+execution+of+each+task.+These+can+be+used+to+manipulate+the+execution+environment%3B+for+example%2C+reinitializing+ThreadLocals%2C+gathering+statistics%2C+or+adding+log+entries.+Additionally%2C+method+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23terminated%28%29%22%3E%3Ccode%3Eterminated%3C%2Fcode%3E%3C%2Fa%3E+can+be+overridden+to+perform+any+special+processing+that+needs+to+be+done+once+the+Executor+has+fully+terminated.+%0A+++%3Cp%3EIf+hook+or+callback+methods+throw+exceptions%2C+internal+worker+threads+may+in+turn+fail+and+abruptly+terminate.%3C%2Fp%3E%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++Queue+maintenance%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++Method+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23getQueue%28%29%22%3E%3Ccode%3EgetQueue%28%29%3C%2Fcode%3E%3C%2Fa%3E+allows+access+to+the+work+queue+for+purposes+of+monitoring+and+debugging.+Use+of+this+method+for+any+other+purpose+is+strongly+discouraged.+Two+supplied+methods%2C+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23remove%28java.lang.Runnable%29%22%3E%3Ccode%3Eremove%28Runnable%29%3C%2Fcode%3E%3C%2Fa%3E+and+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23purge%28%29%22%3E%3Ccode%3Epurge%3C%2Fcode%3E%3C%2Fa%3E+are+available+to+assist+in+storage+reclamation+when+large+numbers+of+queued+tasks+become+cancelled.%0A++%3C%2Fdd%3E+%0A++%3Cdt%3E%0A+++Finalization%0A++%3C%2Fdt%3E+%0A++%3Cdd%3E%0A+++A+pool+that+is+no+longer+referenced+in+a+program+%3Cem%3EAND%3C%2Fem%3E+has+no+remaining+threads+will+be+%3Ccode%3Eshutdown%3C%2Fcode%3E+automatically.+If+you+would+like+to+ensure+that+unreferenced+pools+are+reclaimed+even+if+users+forget+to+call+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23shutdown%28%29%22%3E%3Ccode%3Eshutdown%3C%2Fcode%3E%3C%2Fa%3E%2C+then+you+must+arrange+that+unused+threads+eventually+die%2C+by+setting+appropriate+keep-alive+times%2C+using+a+lower+bound+of+zero+core+threads+and%2For+setting+%3Ca+href%3D%22psi_element%3A%2F%2Fjava.util.concurrent.ThreadPoolExecutor%23allowCoreThreadTimeOut%28boolean%29%22%3E%3Ccode%3EallowCoreThreadTimeOut%28boolean%29%3C%2Fcode%3E%3C%2Fa%3E.+%0A++%3C%2Fdd%3E+%0A+%3C%2Fdl%3E+%0A+%3Cp%3E%3Cstrong%3EExtension+example%3C%2Fstrong%3E.+Most+extensions+of+this+class+override+one+or+more+of+the+protected+hook+methods.+For+example%2C+here+is+a+subclass+that+adds+a+simple+pause%2Fresume+feature%3A+%3C%2Fp%3E%0A+%3Cpre+id%3D%220%22%3E%3C%2Fpre%3E+%0A%3C%2Fdiv%3E%0A%3Ctable+class%3D%22sections%22%3E%0A+%3Ctbody%3E%0A++%3Ctr%3E%0A+++%3Ctd+valign%3D%22top%22+class%3D%22section%22%3E%3Cp%3ESince%3A%3C%2Fp%3E%3C%2Ftd%3E%0A+++%3Ctd+valign%3D%22top%22%3E%3Cp%3E1.5+%3C%2Fp%3E%3C%2Ftd%3E%0A++%3C%2Ftr%3E%0A+%3C%2Ftbody%3E%0A%3C%2Ftable%3E
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:643)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:624)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:375)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:384)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:438)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 6 more
```

**Comment by YiiGuxing** [comment]
这个是翻译API的限制，目前先不做处理。
