### ISSUE TITLE
翻译有的文档就不停的报错。

### ISSUE THREAD

**Issue by wangzhaoqiang** [YiiGuxing/TranslationPlugin#531]
翻译有的文档就不停的提示这个错误。例如ava.util.regex.Pattern类的文档注释时就提示这个错误。
Failed to translate documentation: 翻译失败: Request-URI Too Long

>Plugin v2.9.1  
>IntelliJ IDEA 2020.1.1  
>Build #IU-201.7223.91, built on April 30, 2020  
>Runtime version: 11.0.6+8-b765.40 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.14.6

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: 翻译失败: Request-URI Too Long
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:242)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:178)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 414. Status=414, Url=http://api.fanyi.baidu.com/api/trans/vip/translate?appid=20200420000424997&from=auto&to=zh&salt=1592443320588&sign=d834fcae36b7a4339087b86b2cfaad36&q=A+compiled+representation+of+a+regular+expression.%0AA+regular+expression%2C+specified+as+a+string%2C+must+first+be+compiled+into+an+instance+of+this+class.+The+resulting+pattern+can+then+be+used+to+create+a+Matcher+object+that+can+match+arbitrary+character+sequences+against+the+regular+expression.+All+of+the+state+involved+in+performing+a+match+resides+in+the+matcher%2C+so+many+matchers+can+share+the+same+pattern.%0AA+typical+invocation+sequence+is+thus%0A+++Pattern+p+%3D+Pattern.compile%28%22a*b%22%29%3B%0A+++Matcher+m+%3D+p.matcher%28%22aaaaab%22%29%3B%0A+++boolean+b+%3D+m.matches%28%29%3B%0AA+matches+method+is+defined+by+this+class+as+a+convenience+for+when+a+regular+expression+is+used+just+once.+This+method+compiles+an+expression+and+matches+an+input+sequence+against+it+in+a+single+invocation.+The+statement%0A+++boolean+b+%3D+Pattern.matches%28%22a*b%22%2C+%22aaaaab%22%29%3B%0Ais+equivalent+to+the+three+statements+above%2C+though+for+repeated+matches+it+is+less+efficient+since+it+does+not+allow+the+compiled+pattern+to+be+reused.%0AInstances+of+this+class+are+immutable+and+are+safe+for+use+by+multiple+concurrent+threads.+Instances+of+the+Matcher+class+are+not+safe+for+such+use.%0ASummary+of+regular-expression+constructs%0AConstruct%0AMatches%0A%C2%A0%0ACharacters%0Ax%0AThe+character+x%0A%5C%5C%0AThe+backslash+character%0A%5C0n%0AThe+character+with+octal+value+0n+%280%C2%A0%3C%3D%C2%A0n%C2%A0%3C%3D%C2%A07%29%0A%5C0nn%0AThe+character+with+octal+value+0nn+%280%C2%A0%3C%3D%C2%A0n%C2%A0%3C%3D%C2%A07%29%0A%5C0mnn%0AThe+character+with+octal+value+0mnn+%280%C2%A0%3C%3D%C2%A0m%C2%A0%3C%3D%C2%A03%2C+0%C2%A0%3C%3D%C2%A0n%C2%A0%3C%3D%C2%A07%29%0A%5Cxhh%0AThe+character+with+hexadecimal%C2%A0value%C2%A00xhh%0A%5Cuhhhh%0AThe+character+with+hexadecimal%C2%A0value%C2%A00xhhhh%0A%5Cx%7Bh...h%7D%0AThe+character+with+hexadecimal%C2%A0value%C2%A00xh...h+%28Character.MIN_CODE_POINT+%C2%A0%3C%3D%C2%A00xh...h%C2%A0%3C%3D%C2%A0+Character.MAX_CODE_POINT%29%0A%5Ct%0AThe+tab+character+%28%27%5Cu0009%27%29%0A%5Cn%0AThe+newline+%28line+feed%29+character+%28%27%5Cu000A%27%29%0A%5Cr%0AThe+carriage-return+character+%28%27%5Cu000D%27%29%0A%5Cf%0AThe+form-feed+character+%28%27%5Cu000C%27%29%0A%5Ca%0AThe+alert+%28bell%29+character+%28%27%5Cu0007%27%29%0A%5Ce%0AThe+escape+character+%28%27%5Cu001B%27%29%0A%5Ccx%0AThe+control+character+corresponding+to+x%0A%C2%A0%0ACharacter+classes%0A%5Babc%5D%0Aa%2C+b%2C+or+c+%28simple+class%29%0A%5B%5Eabc%5D%0AAny+character+except+a%2C+b%2C+or+c+%28negation%29%0A%5Ba-zA-Z%5D%0Aa+through+z+or+A+through+Z%2C+inclusive+%28range%29%0A%5Ba-d%5Bm-p%5D%5D%0Aa+through+d%2C+or+m+through+p%3A+%5Ba-dm-p%5D+%28union%29%0A%5Ba-z%26%26%5Bdef%5D%5D%0Ad%2C+e%2C+or+f+%28intersection%29%0A%5Ba-z%26%26%5B%5Ebc%5D%5D%0Aa+through+z%2C+except+for+b+and+c%3A+%5Bad-z%5D+%28subtraction%29%0A%5Ba-z%26%26%5B%5Em-p%5D%5D%0Aa+through+z%2C+and+not+m+through+p%3A+%5Ba-lq-z%5D%28subtraction%29%0A%C2%A0%0APredefined+character+classes%0A.%0AAny+character+%28may+or+may+not+match+line+terminators%29%0A%5Cd%0AA+digit%3A+%5B0-9%5D%0A%5CD%0AA+non-digit%3A+%5B%5E0-9%5D%0A%5Ch%0AA+horizontal+whitespace+character%3A+%5B+%5Ct%5CxA0%5Cu1680%5Cu180e%5Cu2000-%5Cu200a%5Cu202f%5Cu205f%5Cu3000%5D%0A%5CH%0AA+non-horizontal+whitespace+character%3A+%5B%5E%5Ch%5D%0A%5Cs%0AA+whitespace+character%3A+%5B+%5Ct%5Cn%5Cx0B%5Cf%5Cr%5D%0A%5CS%0AA+non-whitespace+character%3A+%5B%5E%5Cs%5D%0A%5Cv%0AA+vertical+whitespace+character%3A+%5B%5Cn%5Cx0B%5Cf%5Cr%5Cx85%5Cu2028%5Cu2029%5D%0A%5CV%0AA+non-vertical+whitespace+character%3A+%5B%5E%5Cv%5D%0A%5Cw%0AA+word+character%3A+%5Ba-zA-Z_0-9%5D%0A%5CW%0AA+non-word+character%3A+%5B%5E%5Cw%5D%0A%C2%A0%0APOSIX+character+classes+%28US-ASCII+only%29%0A%5Cp%7BLower%7D%0AA+lower-case+alphabetic+character%3A+%5Ba-z%5D%0A%5Cp%7BUpper%7D%0AAn+upper-case+alphabetic+character%3A%5BA-Z%5D%0A%5Cp%7BASCII%7D%0AAll+ASCII%3A%5B%5Cx00-%5Cx7F%5D%0A%5Cp%7BAlpha%7D%0AAn+alphabetic+character%3A%5B%5Cp%7BLower%7D%5Cp%7BUpper%7D%5D%0A%5Cp%7BDigit%7D%0AA+decimal+digit%3A+%5B0-9%5D%0A%5Cp%7BAlnum%7D%0AAn+alphanumeric+character%3A%5B%5Cp%7BAlpha%7D%5Cp%7BDigit%7D%5D%0A%5Cp%7BPunct%7D%0APunctuation%3A+One+of+%21%22%23%24%25%26%27%28%29*%2B%2C-.%2F%3A%3B%3C%3D%3E%3F%40%5B%5C%5D%5E_%60%7B%7C%7D%7E%0A+%0A%5Cp%7BGraph%7D%0AA+visible+character%3A+%5B%5Cp%7BAlnum%7D%5Cp%7BPunct%7D%5D%0A%5Cp%7BPrint%7D%0AA+printable+character%3A+%5B%5Cp%7BGraph%7D%5Cx20%5D%0A%5Cp%7BBlank%7D%0AA+space+or+a+tab%3A+%5B+%5Ct%5D%0A%5Cp%7BCntrl%7D%0AA+control+character%3A+%5B%5Cx00-%5Cx1F%5Cx7F%5D%0A%5Cp%7BXDigit%7D%0AA+hexadecimal+digit%3A+%5B0-9a-fA-F%5D%0A%5Cp%7BSpace%7D%0AA+whitespace+character%3A+%5B+%5Ct%5Cn%5Cx0B%5Cf%5Cr%5D%0A%C2%A0%0Ajava.lang.Character+classes+%28simple+java+character+type%29%0A%5Cp%7BjavaLowerCase%7D%0AEquivalent+to+java.lang.Character.isLowerCase%28%29%0A%5Cp%7BjavaUpperCase%7D%0AEquivalent+to+java.lang.Character.isUpperCase%28%29%0A%5Cp%7BjavaWhitespace%7D%0AEquivalent+to+java.lang.Character.isWhitespace%28%29%0A%5Cp%7BjavaMirrored%7D%0AEquivalent+to+java.lang.Character.isMirrored%28%29%0A%C2%A0%0AClasses+for+Unicode+scripts%2C+blocks%2C+categories+and+binary+properties%0A%5Cp%7BIsLatin%7D%0AA+Latin%C2%A0script+character+%28script%29%0A%5Cp%7BInGreek%7D%0AA+character+in+the+Greek%C2%A0block+%28block%29%0A%5Cp%7BLu%7D%0AAn+uppercase+letter+%28category%29%0A%5Cp%7BIsAlphabetic%7D%0AAn+alphabetic+character+%28binary+property%29%0A%5Cp%7BSc%7D%0AA+currency+symbol%0A%5CP%7BInGreek%7D%0AAny+character+except+one+in+the+Greek+block+%28negation%29%0A%5B%5Cp%7BL%7D%26%26%5B%5E%5Cp%7BLu%7D%5D%5D%0AAny+letter+except+an+uppercase+letter+%28subtraction%29%0A%C2%A0%0ABoundary+matchers%0A%5E%0AThe+beginning+of+a+line%0A%24%0AThe+end+of+a+line%0A%5Cb%0AA+word+boundary%0A%5CB%0AA+non-word+boundary%0A%5CA%0AThe+beginning+of+the+input%0A%5CG%0AThe+end+of+the+previous+match%0A%5CZ%0AThe+end+of+the+input+but+for+the+final+terminator%2C+if%C2%A0any%0A%5Cz%0AThe+end+of+the+input%0A%C2%A0%0ALinebreak+matcher%0A%5CR%0AAny+Unicode+linebreak+sequence%2C+is+equivalent+to+%5Cu000D%5Cu000A%7C%5B%5Cu000A%5Cu000B%5Cu000C%5Cu000D%5Cu0085%5Cu2028%5Cu2029%5D+%0A%C2%A0%0AGreedy+quantifiers%0AX%3F%0AX%2C+once+or+not+at+all%0AX*%0AX%2C+zero+or+more+times%0AX%2B%0AX%2C+one+or+more+times%0AX%7Bn%7D%0AX%2C+exactly+n+times%0AX%7Bn%2C%7D%0AX%2C+at+least+n+times%0AX%7Bn%2Cm%7D%0AX%2C+at+least+n+but+not+more+than+m+times%0A%C2%A0%0AReluctant+quantifiers%0AX%3F%3F%0AX%2C+once+or+not+at+all%0AX*%3F%0AX%2C+zero+or+more+times%0AX%2B%3F%0AX%2C+one+or+more+times%0AX%7Bn%7D%3F%0AX%2C+exactly+n+times%0AX%7Bn%2C%7D%3F%0AX%2C+at+least+n+times%0AX%7Bn%2Cm%7D%3F%0AX%2C+at+least+n+but+not+more+than+m+times%0A%C2%A0%0APossessive+quantifiers%0AX%3F%2B%0AX%2C+once+or+not+at+all%0AX*%2B%0AX%2C+zero+or+more+times%0AX%2B%2B%0AX%2C+one+or+more+times%0AX%7Bn%7D%2B%0AX%2C+exactly+n+times%0AX%7Bn%2C%7D%2B%0AX%2C+at+least+n+times%0AX%7Bn%2Cm%7D%2B%0AX%2C+at+least+n+but+not+more+than+m+times%0A%C2%A0%0ALogical+operators%0AXY%0AX+followed+by+Y%0AX%7CY%0AEither+X+or+Y%0A%28X%29%0AX%2C+as+a+capturing+group%0A%C2%A0%0ABack+references%0A%5Cn%0AWhatever+the+nth+capturing+group+matched%0A%5Ck%3Cname%3E%0AWhatever+the+named-capturing+group+%22name%22+matched%0A%C2%A0%0AQuotation%0A%5C%0ANothing%2C+but+quotes+the+following+character%0A%5CQ%0ANothing%2C+but+quotes+all+characters+until+%5CE%0A%5CE%0ANothing%2C+but+ends+quoting+started+by+%5CQ%0A+%0A%C2%A0%0ASpecial+constructs+%28named-capturing+and+non-capturing%29%0A%28%3F%3Cname%3EX%29%0AX%2C+as+a+named-capturing+group%0A%28%3F%3AX%29%0AX%2C+as+a+non-capturing+group%0A%28%3FidmsuxU-idmsuxU%29%C2%A0%0ANothing%2C+but+turns+match+flags+i+d+m+s+u+x+U+on+-+off%0A%28%3Fidmsux-idmsux%3AX%29%C2%A0%C2%A0%0AX%2C+as+a+non-capturing+group+with+the+given+flags+i+d+m+s+u+x+on+-+off%0A%28%3F%3DX%29%0AX%2C+via+zero-width+positive+lookahead%0A%28%3F%21X%29%0AX%2C+via+zero-width+negative+lookahead%0A%28%3F%3C%3DX%29%0AX%2C+via+zero-width+positive+lookbehind%0A%28%3F%3C%21X%29%0AX%2C+via+zero-width+negative+lookbehind%0A%28%3F%3EX%29%0AX%2C+as+an+independent%2C+non-capturing+group%0A+%0ABackslashes%2C+escapes%2C+and+quoting%0AThe+backslash+character+%28%27%5C%27%29+serves+to+introduce+escaped+constructs%2C+as+defined+in+the+table+above%2C+as+well+as+to+quote+characters+that+otherwise+would+be+interpreted+as+unescaped+constructs.+Thus+the+expression+%5C%5C+matches+a+single+backslash+and+%5C%7B+matches+a+left+brace.%0AIt+is+an+error+to+use+a+backslash+prior+to+any+alphabetic+character+that+does+not+denote+an+escaped+construct%3B+these+are+reserved+for+future+extensions+to+the+regular-expression+language.+A+backslash+may+be+used+prior+to+a+non-alphabetic+character+regardless+of+whether+that+character+is+part+of+an+unescaped+construct.%0ABackslashes+within+string+literals+in+Java+source+code+are+interpreted+as+required+by+The+Java%E2%84%A2+Language+Specification+as+either+Unicode+escapes+%28section+3.3%29+or+other+character+escapes+%28section+3.10.6%29+It+is+therefore+necessary+to+double+backslashes+in+string+literals+that+represent+regular+expressions+to+protect+them+from+interpretation+by+the+Java+bytecode+compiler.+The+string+literal+%22%5Cb%22%2C+for+example%2C+matches+a+single+backspace+character+when+interpreted+as+a+regular+expression%2C+while+%22%5C%5Cb%22+matches+a+word+boundary.+The+string+literal+%22%5C%28hello%5C%29%22+is+illegal+and+leads+to+a+compile-time+error%3B+in+order+to+match+the+string+%28hello%29+the+string+literal+%22%5C%5C%28hello%5C%5C%29%22+must+be+used.%0ACharacter+Classes%0ACharacter+classes+may+appear+within+other+character+classes%2C+and+may+be+composed+by+the+union+operator+%28implicit%29+and+the+intersection+operator+%28%26%26%29.+The+union+operator+denotes+a+class+that+contains+every+character+that+is+in+at+least+one+of+its+operand+classes.+The+intersection+operator+denotes+a+class+that+contains+every+character+that+is+in+both+of+its+operand+classes.%0AThe+precedence+of+character-class+operators+is+as+follows%2C+from+highest+to+lowest%3A%0A1%C2%A0%C2%A0%C2%A0%C2%A0%0ALiteral+escape%C2%A0%C2%A0%C2%A0%C2%A0%0A%5Cx%0A2%C2%A0%C2%A0%C2%A0%C2%A0%0AGrouping%0A%5B...%5D%0A3%C2%A0%C2%A0%C2%A0%C2%A0%0ARange%0Aa-z%0A4%C2%A0%C2%A0%C2%A0%C2%A0%0AUnion%0A%5Ba-e%5D%5Bi-u%5D%0A5%C2%A0%C2%A0%C2%A0%C2%A0%0AIntersection%0A%5Ba-z%26%26%5Baeiou%5D%5D%0ANote+that+a+different+set+of+metacharacters+are+in+effect+inside+a+character+class+than+outside+a+character+class.+For+instance%2C+the+regular+expression+.+loses+its+special+meaning+inside+a+character+class%2C+while+the+expression+-+becomes+a+range+forming+metacharacter.%0ALine+terminators%0AA+line+terminator+is+a+one-+or+two-character+sequence+that+marks+the+end+of+a+line+of+the+input+character+sequence.+The+following+are+recognized+as+line+terminators%3A%0AA+newline+%28line+feed%29+character%C2%A0%28%27%5Cn%27%29%2C%0AA+carriage-return+character+followed+immediately+by+a+newline+character%C2%A0%28%22%5Cr%5Cn%22%29%2C%0AA+standalone+carriage-return+character%C2%A0%28%27%5Cr%27%29%2C%0AA+next-line+character%C2%A0%28%27%5Cu0085%27%29%2C%0AA+line-separator+character%C2%A0%28%27%5Cu2028%27%29%2C+or%0AA+paragraph-separator+character%C2%A0%28%27%5Cu2029%29.%0AIf+UNIX_LINES+mode+is+activated%2C+then+the+only+line+terminators+recognized+are+newline+characters.%0AThe+regular+expression+.+matches+any+character+except+a+line+terminator+unless+the+DOTALL+flag+is+specified.%0ABy+default%2C+the+regular+expressions+%5E+and+%24+ignore+line+terminators+and+only+match+at+the+beginning+and+the+end%2C+respectively%2C+of+the+entire+input+sequence.+If+MULTILINE+mode+is+activated+then+%5E+matches+at+the+beginning+of+input+and+after+any+line+terminator+except+at+the+end+of+input.+When+in+MULTILINE+mode+%24+matches+just+before+a+line+terminator+or+the+end+of+the+input+sequence.%0AGroups+and+capturing%0AGroup+number%0ACapturing+groups+are+numbered+by+counting+their+opening+parentheses+from+left+to+right.+In+the+expression+%28%28A%29%28B%28C%29%29%29%2C+for+example%2C+there+are+four+such+groups%3A%0A1%C2%A0%C2%A0%C2%A0%C2%A0%0A%28%28A%29%28B%28C%29%29%29%0A2%C2%A0%C2%A0%C2%A0%C2%A0%0A%28A%29%0A3%C2%A0%C2%A0%C2%A0%C2%A0%0A%28B%28C%29%29%0A4%C2%A0%C2%A0%C2%A0%C2%A0%0A%28C%29%0AGroup+zero+always+stands+for+the+entire+expression.%0ACapturing+groups+are+so+named+because%2C+during+a+match%2C+each+subsequence+of+the+input+sequence+that+matches+such+a+group+is+saved.+The+captured+subsequence+may+be+used+later+in+the+expression%2C+via+a+back+reference%2C+and+may+also+be+retrieved+from+the+matcher+once+the+match+operation+is+complete.%0AGroup+name%0AA+capturing+group+can+also+be+assigned+a+%22name%22%2C+a+named-capturing+group%2C+and+then+be+back-referenced+later+by+the+%22name%22.+Group+names+are+composed+of+the+following+characters.+The+first+character+must+be+a+letter.%0AThe+uppercase+letters+%27A%27+through+%27Z%27+%28%27%5Cu0041%27%C2%A0through%C2%A0%27%5Cu005a%27%29%2C%0AThe+lowercase+letters+%27a%27+through+%27z%27+%28%27%5Cu0061%27%C2%A0through%C2%A0%27%5Cu007a%27%29%2C%0AThe+digits+%270%27+through+%279%27+%28%27%5Cu0030%27%C2%A0through%C2%A0%27%5Cu0039%27%29%2C%0AA+named-capturing+group+is+still+numbered+as+described+in+Group+number.%0AThe+captured+input+associated+with+a+group+is+always+the+subsequence+that+the+group+most+recently+matched.+If+a+group+is+evaluated+a+second+time+because+of+quantification+then+its+previously-captured+value%2C+if+any%2C+will+be+retained+if+the+second+evaluation+fails.+Matching+the+string+%22aba%22+against+the+expression+%28a%28b%29%3F%29%2B%2C+for+example%2C+leaves+group+two+set+to+%22b%22.+All+captured+input+is+discarded+at+the+beginning+of+each+match.%0AGroups+beginning+with+%28%3F+are+either+pure%2C+non-capturing+groups+that+do+not+capture+text+and+do+not+count+towards+the+group+total%2C+or+named-capturing+group.%0AUnicode+support%0AThis+class+is+in+conformance+with+Level+1+of+Unicode+Technical+Standard+%2318%3A+Unicode+Regular+Expression%2C+plus+RL2.1+Canonical+Equivalents.%0AUnicode+escape+sequences+such+as+%5Cu2014+in+Java+source+code+are+processed+as+described+in+section+3.3+of+The+Java%E2%84%A2+Language+Specification.+Such+escape+sequences+are+also+implemented+directly+by+the+regular-expression+parser+so+that+Unicode+escapes+can+be+used+in+expressions+that+are+read+from+files+or+from+the+keyboard.+Thus+the+strings+%22%5Cu2014%22+and+%22%5C%E2%80%94%22%2C+while+not+equal%2C+compile+into+the+same+pattern%2C+which+matches+the+character+with+hexadecimal+value+0x2014.%0AA+Unicode+character+can+also+be+represented+in+a+regular-expression+by+using+its+Hex+notation%28hexadecimal+code+point+value%29+directly+as+described+in+construct+%5Cx%7B...%7D%2C+for+example+a+supplementary+character+U%2B2011F+can+be+specified+as+%5Cx%7B2011F%7D%2C+instead+of+two+consecutive+Unicode+escape+sequences+of+the+surrogate+pair+%5CuD840%5CuDD1F.%0AUnicode+scripts%2C+blocks%2C+categories+and+binary+properties+are+written+with+the+%5Cp+and+%5CP+constructs+as+in+Perl.+%5Cp%7Bprop%7D+matches+if+the+input+has+the+property+prop%2C+while+%5CP%7Bprop%7D+does+not+match+if+the+input+has+that+property.%0AScripts%2C+blocks%2C+categories+and+binary+properties+can+be+used+both+inside+and+outside+of+a+character+class.%0AScripts+are+specified+either+with+the+prefix+Is%2C+as+in+IsHiragana%2C+or+by+using+the+script+keyword+%28or+its+short+form+sc%29as+in+script%3DHiragana+or+sc%3DHiragana.%0AThe+script+names+supported+by+Pattern+are+the+valid+script+names+accepted+and+defined+by+UnicodeScript.forName.%0ABlocks+are+specified+with+the+prefix+In%2C+as+in+InMongolian%2C+or+by+using+the+keyword+block+%28or+its+short+form+blk%29+as+in+block%3DMongolian+or+blk%3DMongolian.%0AThe+block+names+supported+by+Pattern+are+the+valid+block+names+accepted+and+defined+by+UnicodeBlock.forName.%0ACategories+may+be+specified+with+the+optional+prefix+Is%3A+Both+%5Cp%7BL%7D+and+%5Cp%7BIsL%7D+denote+the+category+of+Unicode+letters.+Same+as+scripts+and+blocks%2C+categories+can+also+be+specified+by+using+the+keyword+general_category+%28or+its+short+form+gc%29+as+in+general_category%3DLu+or+gc%3DLu.%0AThe+supported+categories+are+those+of+The+Unicode+Standard+in+the+version+specified+by+the+Character+class.+The+category+names+are+those+defined+in+the+Standard%2C+both+normative+and+informative.%0ABinary+properties+are+specified+with+the+prefix+Is%2C+as+in+IsAlphabetic.+The+supported+binary+properties+by+Pattern+are%0AAlphabetic%0AIdeographic%0ALetter%0ALowercase%0AUppercase%0ATitlecase%0APunctuation%0AControl%0AWhite_Space%0ADigit%0AHex_Digit%0AJoin_Control%0ANoncharacter_Code_Point%0AAssigned%0AThe+following+Predefined+Character+classes+and+POSIX+character+classes+are+in+conformance+with+the+recommendation+of+Annex+C%3A+Compatibility+Properties+of+Unicode+Regular+Expression+%2C+when+UNICODE_CHARACTER_CLASS+flag+is+specified.%0AClasses%0AMatches%0A%5Cp%7BLower%7D%0AA+lowercase+character%3A%5Cp%7BIsLowercase%7D%0A%5Cp%7BUpper%7D%0AAn+uppercase+character%3A%5Cp%7BIsUppercase%7D%0A%5Cp%7BASCII%7D%0AAll+ASCII%3A%5B%5Cx00-%5Cx7F%5D%0A%5Cp%7BAlpha%7D%0AAn+alphabetic+character%3A%5Cp%7BIsAlphabetic%7D%0A%5Cp%7BDigit%7D%0AA+decimal+digit+character%3Ap%7BIsDigit%7D%0A%5Cp%7BAlnum%7D%0AAn+alphanumeric+character%3A%5B%5Cp%7BIsAlphabetic%7D%5Cp%7BIsDigit%7D%5D%0A%5Cp%7BPunct%7D%0AA+punctuation+character%3Ap%7BIsPunctuation%7D%0A%5Cp%7BGraph%7D%0AA+visible+character%3A+%5B%5E%5Cp%7BIsWhite_Space%7D%5Cp%7Bgc%3DCc%7D%5Cp%7Bgc%3DCs%7D%5Cp%7Bgc%3DCn%7D%5D%0A%5Cp%7BPrint%7D%0AA+printable+character%3A+%5B%5Cp%7BGraph%7D%5Cp%7BBlank%7D%26%26%5B%5E%5Cp%7BCntrl%7D%5D%5D%0A%5Cp%7BBlank%7D%0AA+space+or+a+tab%3A+%5B%5Cp%7BIsWhite_Space%7D%26%26%5B%5E%5Cp%7Bgc%3DZl%7D%5Cp%7Bgc%3DZp%7D%5Cx0a%5Cx0b%5Cx0c%5Cx0d%5Cx85%5D%5D%0A%5Cp%7BCntrl%7D%0AA+control+character%3A+%5Cp%7Bgc%3DCc%7D%0A%5Cp%7BXDigit%7D%0AA+hexadecimal+digit%3A+%5B%5Cp%7Bgc%3DNd%7D%5Cp%7BIsHex_Digit%7D%5D%0A%5Cp%7BSpace%7D%0AA+whitespace+character%3A%5Cp%7BIsWhite_Space%7D%0A%5Cd%0AA+digit%3A+%5Cp%7BIsDigit%7D%0A%5CD%0AA+non-digit%3A+%5B%5E%5Cd%5D%0A%5Cs%0AA+whitespace+character%3A+%5Cp%7BIsWhite_Space%7D%0A%5CS%0AA+non-whitespace+character%3A+%5B%5E%5Cs%5D%0A%5Cw%0AA+word+character%3A+%5B%5Cp%7BAlpha%7D%5Cp%7Bgc%3DMn%7D%5Cp%7Bgc%3DMe%7D%5Cp%7Bgc%3DMc%7D%5Cp%7BDigit%7D%5Cp%7Bgc%3DPc%7D%5Cp%7BIsJoin_Control%7D%5D%0A%5CW%0AA+non-word+character%3A+%5B%5E%5Cw%5D%0ACategories+that+behave+like+the+java.lang.Character+boolean+ismethodname+methods+%28except+for+the+deprecated+ones%29+are+available+through+the+same+%5Cp%7Bprop%7D+syntax+where+the+specified+property+has+the+name+javamethodname.%0AComparison+to+Perl+5%0AThe+Pattern+engine+performs+traditional+NFA-based+matching+with+ordered+alternation+as+occurs+in+Perl+5.%0APerl+constructs+not+supported+by+this+class%3A%0APredefined+character+classes+%28Unicode+character%29%0A%5CX%C2%A0%C2%A0%C2%A0%C2%A0Match+Unicode+extended+grapheme+cluster%0AThe+backreference+constructs%2C+%5Cg%7Bn%7D+for+the+nthcapturing+group+and+%5Cg%7Bname%7D+for+named-capturing+group.%0AThe+named+character+construct%2C+%5CN%7Bname%7D+for+a+Unicode+character+by+its+name.%0AThe+conditional+constructs+%28%3F%28condition%29X%29+and+%28%3F%28condition%29X%7CY%29%2C%0AThe+embedded+code+constructs+%28%3F%7Bcode%7D%29+and+%28%3F%3F%7Bcode%7D%29%2C%0AThe+embedded+comment+syntax+%28%3F%23comment%29%2C+and%0AThe+preprocessing+operations+%5Cl+%5Cu%2C+%5CL%2C+and+%5CU.%0AConstructs+supported+by+this+class+but+not+by+Perl%3A%0ACharacter-class+union+and+intersection+as+described+above.%0ANotable+differences+from+Perl%3A%0AIn+Perl%2C+%5C1+through+%5C9+are+always+interpreted+as+back+references%3B+a+backslash-escaped+number+greater+than+9+is+treated+as+a+back+reference+if+at+least+that+many+subexpressions+exist%2C+otherwise+it+is+interpreted%2C+if+possible%2C+as+an+octal+escape.+In+this+class+octal+escapes+must+always+begin+with+a+zero.+In+this+class%2C+%5C1+through+%5C9+are+always+interpreted+as+back+references%2C+and+a+larger+number+is+accepted+as+a+back+reference+if+at+least+that+many+subexpressions+exist+at+that+point+in+the+regular+expression%2C+otherwise+the+parser+will+drop+digits+until+the+number+is+smaller+or+equal+to+the+existing+number+of+groups+or+it+is+one+digit.%0APerl+uses+the+g+flag+to+request+a+match+that+resumes+where+the+last+match+left+off.+This+functionality+is+provided+implicitly+by+the+Matcher+class%3A+Repeated+invocations+of+the+find+method+will+resume+where+the+last+match+left+off%2C+unless+the+matcher+is+reset.%0AIn+Perl%2C+embedded+flags+at+the+top+level+of+an+expression+affect+the+whole+expression.+In+this+class%2C+embedded+flags+always+take+effect+at+the+point+at+which+they+appear%2C+whether+they+are+at+the+top+level+or+within+a+group%3B+in+the+latter+case%2C+flags+are+restored+at+the+end+of+the+group+just+as+in+Perl.%0AFor+a+more+precise+description+of+the+behavior+of+regular+expression+constructs%2C+please+see+Mastering+Regular+Expressions%2C+3nd+Edition%2C+Jeffrey+E.+F.+Friedl%2C+O%27Reilly+and+Associates%2C+2006.%0A%0ASince%3A%0A1.4%0ASee+Also%3A%0AString.split%28String%2C+int%29%2C+String.split%28String%29
	at com.intellij.util.io.HttpRequests.throwHttpStatusError(HttpRequests.java:643)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:624)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:375)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:384)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:438)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 6 more
```

**Comment by YiiGuxing** [comment]
此问题已在下一个版本得到修复

**Comment by wangzhaoqiang** [comment]
感谢！
