### ISSUE TITLE
一个小bug

### ISSUE THREAD

**Issue by 2191751138** [YiiGuxing/TranslationPlugin#535]
版本2.9.1的插件在goland中使用会出现翻译失败,服务器异常的bug。。 我确定我的应用id和密钥是有效的。可以在pycharm中的2.6.2版本中正常使用。！

**Comment by 2191751138** [comment]
![2OGDQ61H~(24_J$_4~_`D~2](https://user-images.githubusercontent.com/40062163/85975075-b0afba80-ba09-11ea-85ba-15bec979acee.png)
![Uploading `L_9UL65[Z4A7}}}TA)@%[0.png…]()

**Comment by 2191751138** [comment]
![2OGDQ61H~(24_J$_4~_`D~2](https://user-images.githubusercontent.com/40062163/85975075-b0afba80-ba09-11ea-85ba-15bec979acee.png)
![`L_9UL65 Z4A7}}}TA)@% 0](https://user-images.githubusercontent.com/40062163/85975098-c45b2100-ba09-11ea-83ef-e038a154662b.png)

**Comment by 2191751138** [comment]
![L2CA406`48`J43 WOPGL@7S](https://user-images.githubusercontent.com/40062163/85975143-db017800-ba09-11ea-9d82-7da5ae439e3f.png)

**Comment by YiiGuxing** [comment]
请提供异常信息

**Comment by 2191751138** [comment]
>Plugin v2.9.1  
>GoLand 2020.1.2  
>Build #GO-201.7223.97, built on May 1, 2020  
>Runtime version: 11.0.6+8-b765.40 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Youdao Translate :: 翻译失败: 服务器异常
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Youdao Translate :: Translate failed: 303
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:90)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:67)
	... 8 more
```

**Comment by YiiGuxing** [comment]
错误为有道服务器内部异常，请检查APP ID 和APP Key是否正确。

**Comment by 2191751138** [comment]
app ID 和App key是正确的 在Pycharm里面能够使用 ！！！ 我没有任何理由连续复制app ID和App key错误十几次。。。 我怀疑是版本的问题 如果你需要更多的测试我可以继续尝试！！！

**Comment by YiiGuxing** [comment]
这就很奇怪了，我这边是没有问题的，而且这个错误是有道服务器内部的错误，如果app ID和App key都正确的话，很有可以是你帐号状态有问题。
![image](https://user-images.githubusercontent.com/10737066/86338185-99c8cc80-bc84-11ea-9929-25f095f288dd.png)

这样，你打开IDE的日志目录：
![image](https://user-images.githubusercontent.com/10737066/86339338-0db7a480-bc86-11ea-964f-250306dbb438.png)
里面有名为`idea.log`的日志文件，在里面搜索 `Translate url:` 得到请求URL，然后根据URL中的参数、你的app ID、App key 和 API文档提供的签名算法计算出签名，再比对URL中的签名参数是不是一样的，如果是一样的话，那就是和插件无关了，这时候你可以使用API提供的例子自己发送一个请求，看看能不能请求成功。
如果签名不一样，那就有可能是app ID或App key有问题。

**Comment by YiiGuxing** [comment]
API文档：https://ai.youdao.com/DOCSIRMA/html/%E8%87%AA%E7%84%B6%E8%AF%AD%E8%A8%80%E7%BF%BB%E8%AF%91/API%E6%96%87%E6%A1%A3/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1/%E6%96%87%E6%9C%AC%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1-API%E6%96%87%E6%A1%A3.html

文档最下面有多种语言的例子。

**Comment by YiiGuxing** [comment]
还有就是，你复制app ID和App key的时候是从有道网页上复制的吧？不是从其他IDE上复制的哈，从其他IDE上复制可是不行的。

**Comment by 2191751138** [comment]
appID和App key是我新建的应用 不是从其他ide复制的 可能是状态问题 我试试

**Comment by 2191751138** [comment]
解决了  可能是qq拼音带来的粘贴复制粘贴问题  我先将appID和App Key粘贴到IDE里面然后复制在复制粘贴到插件里面 问题就解决了

**Comment by 2191751138** [comment]
非常感谢

**Comment by YiiGuxing** [comment]
那现在问题解决了吗？如果解决了我就要把问题关闭了。还有就是没有必要新建翻译应用，多端使用同一翻译应用是没什么问题的。

**Comment by 2191751138** [comment]
关闭吧！！！ 问题解决了
