### ISSUE TITLE
idea多线程死锁

### ISSUE THREAD

**Issue by LuckyMagacian** [YiiGuxing/TranslationPlugin#548]
## 打开多个项目  idea建立文件索引时触发死锁
```
Found one Java-level deadlock:
=============================
"AWT-EventQueue-0":
  waiting to lock monitor 0x00007fb73714dd00 (object 0x000000078435a068, a org.apache.log4j.spi.RootLogger),
  which is held by "ApplicationImpl pooled thread 89"
"ApplicationImpl pooled thread 89":
  waiting to lock monitor 0x00007fb73714c500 (object 0x0000000784c9b658, a com.intellij.idea.PrintStreamLogger),
  which is held by "Alarm Pool"
"Alarm Pool":
  waiting to lock monitor 0x00007fb73714dd00 (object 0x000000078435a068, a org.apache.log4j.spi.RootLogger),
  which is held by "ApplicationImpl pooled thread 89"

Java stack information for the threads listed above:
===================================================
"AWT-EventQueue-0":
        at org.apache.log4j.Category.callAppenders(Category.java:204)
        - waiting to lock <0x000000078435a068> (a org.apache.log4j.spi.RootLogger)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.debug(Category.java:260)
        at com.intellij.openapi.diagnostic.Log4jBasedLogger.debug(Log4jBasedLogger.java:38)
        at com.intellij.ide.plugins.PluginUtilImpl.logPluginDetection(PluginUtilImpl.java:137)
        at com.intellij.ide.plugins.PluginUtilImpl.doFindPluginId(PluginUtilImpl.java:53)
        at com.intellij.ide.plugins.PluginUtilImpl.findPluginId(PluginUtilImpl.java:34)
        at com.intellij.diagnostic.DefaultIdeaErrorLogger.canHandle(DefaultIdeaErrorLogger.java:52)
        at com.intellij.diagnostic.DialogAppender.appendToLoggers(DialogAppender.java:85)
        at com.intellij.diagnostic.DialogAppender.lambda$queueAppend$0(DialogAppender.java:58)
        at com.intellij.diagnostic.DialogAppender$$Lambda$4722/0x00000008029e3c40.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.7/InvocationEvent.java:313)
        at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.7/EventQueue.java:776)
        at java.awt.EventQueue$4.run(java.desktop@11.0.7/EventQueue.java:727)
        at java.awt.EventQueue$4.run(java.desktop@11.0.7/EventQueue.java:721)
        at java.security.AccessController.doPrivileged(java.base@11.0.7/Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.7/ProtectionDomain.java:85)
        at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.7/EventQueue.java:746)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
        at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
        at com.intellij.ide.IdeEventQueue$$Lambda$691/0x00000008008e7040.compute(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
        at com.intellij.ide.IdeEventQueue$$Lambda$688/0x00000008008e2840.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.7/EventDispatchThread.java:203)
        at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.7/EventDispatchThread.java:124)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.7/EventDispatchThread.java:113)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.7/EventDispatchThread.java:109)
        at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.7/EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.run(java.desktop@11.0.7/EventDispatchThread.java:90)
"ApplicationImpl pooled thread 89":
        at java.io.PrintStream.write(java.base@11.0.7/PrintStream.java:557)
        - waiting to lock <0x0000000784c9b658> (a com.intellij.idea.PrintStreamLogger)
        at sun.nio.cs.StreamEncoder.writeBytes(java.base@11.0.7/StreamEncoder.java:233)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(java.base@11.0.7/StreamEncoder.java:312)
        at sun.nio.cs.StreamEncoder.implFlush(java.base@11.0.7/StreamEncoder.java:316)
        at sun.nio.cs.StreamEncoder.flush(java.base@11.0.7/StreamEncoder.java:153)
        - locked <0x000000078d2802e0> (a java.io.OutputStreamWriter)
        at java.io.OutputStreamWriter.flush(java.base@11.0.7/OutputStreamWriter.java:254)
        at org.apache.log4j.helpers.QuietWriter.flush(QuietWriter.java:59)
        at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:324)
        at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
        - locked <0x000000078d27fdc8> (a org.apache.log4j.ConsoleAppender)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:206)
        - locked <0x000000078435a068> (a org.apache.log4j.spi.RootLogger)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.error(Category.java:305)
        at com.intellij.idea.IdeaLogger.logErrorHeader(IdeaLogger.java:118)
        at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:105)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:172)
        at org.jetbrains.concurrency.Promises.errorIfNotMessage(promise.kt:232)
        at org.jetbrains.concurrency.AsyncPromise.setError(AsyncPromise.kt:156)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:201)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.7/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.7/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.7/Thread.java:834)
"Alarm Pool":
        at org.apache.log4j.Category.callAppenders(Category.java:204)
        - waiting to lock <0x000000078435a068> (a org.apache.log4j.spi.RootLogger)
        at org.apache.log4j.Category.forcedLog(Category.java:391)
        at org.apache.log4j.Category.info(Category.java:666)
        at com.intellij.openapi.diagnostic.Log4jBasedLogger.info(Log4jBasedLogger.java:68)
        at com.intellij.idea.OutputStreamLogger.writeBuffer(PrintStreamLogger.java:67)
        at com.intellij.idea.OutputStreamLogger.processByte(PrintStreamLogger.java:54)
        - locked <0x0000000784c9b680> (a com.intellij.idea.OutputStreamLogger)
        at com.intellij.idea.OutputStreamLogger.write(PrintStreamLogger.java:40)
        at java.io.PrintStream.write(java.base@11.0.7/PrintStream.java:559)
        - locked <0x0000000784c9b658> (a com.intellij.idea.PrintStreamLogger)
        at sun.nio.cs.StreamEncoder.writeBytes(java.base@11.0.7/StreamEncoder.java:233)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(java.base@11.0.7/StreamEncoder.java:312)
        at sun.nio.cs.StreamEncoder.flushBuffer(java.base@11.0.7/StreamEncoder.java:104)
        - locked <0x0000000784e620c8> (a java.io.OutputStreamWriter)
        at java.io.OutputStreamWriter.flushBuffer(java.base@11.0.7/OutputStreamWriter.java:184)
        at java.io.PrintStream.newLine(java.base@11.0.7/PrintStream.java:625)
        - locked <0x0000000784c9b658> (a com.intellij.idea.PrintStreamLogger)
        at java.io.PrintStream.println(java.base@11.0.7/PrintStream.java:900)
        - locked <0x0000000784c9b658> (a com.intellij.idea.PrintStreamLogger)
        at java.lang.Throwable$WrappedPrintStream.println(java.base@11.0.7/Throwable.java:752)
        at java.lang.Throwable.printStackTrace(java.base@11.0.7/Throwable.java:662)
        - locked <0x0000000784c9b658> (a com.intellij.idea.PrintStreamLogger)
        at java.lang.Throwable.printStackTrace(java.base@11.0.7/Throwable.java:648)
        at java.lang.Throwable.printStackTrace(java.base@11.0.7/Throwable.java:639)
        at cn.yiiguxing.plugin.translate.util.LogsKt.w(Logs.kt:27)
        at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.logAndShowWarning(TranslateDocumentationAction.kt:222)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask.nonBlockingGet(TranslatingDocumentationProvider.kt:91)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.translate(TranslatingDocumentationProvider.kt:67)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.access$translate(TranslatingDocumentationProvider.kt:37)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider.translateOriginalDoc(TranslatingDocumentationProvider.kt:34)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider.access$translateOriginalDoc(TranslatingDocumentationProvider.kt:19)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$generateDoc$1.invoke(TranslatingDocumentationProvider.kt:26)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$generateDoc$1.invoke(TranslatingDocumentationProvider.kt:19)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.nullIfRecursive(TranslatingDocumentationProvider.kt:47)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.access$nullIfRecursive(TranslatingDocumentationProvider.kt:37)
        at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider.generateDoc(TranslatingDocumentationProvider.kt:25)
        at com.intellij.lang.documentation.DocumentationProvider.generateHoverDoc(DocumentationProvider.java:104)
        at com.intellij.lang.documentation.CompositeDocumentationProvider.generateHoverDoc(CompositeDocumentationProvider.java:150)
        at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.lambda$getDocumentation$2(DocumentationManager.java:1176)
        at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector$$Lambda$6585/0x00000008029e0840.call(Unknown Source)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:472)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:429)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission$$Lambda$1265/0x00000008011d6840.run(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$1021/0x0000000800c62c40.run(Unknown Source)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$1022/0x0000000800c62440.run(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
        at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$394/0x00000008005c0840.run(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
        at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
        at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:437)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:384)
        at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:177)
        at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.getDocumentation(DocumentationManager.java:1184)
        at com.intellij.codeInsight.documentation.DocumentationManager.generateDocumentation(DocumentationManager.java:726)
        at com.intellij.openapi.editor.EditorMouseHoverPopupManager$Context.calcInfo(EditorMouseHoverPopupManager.java:548)
        at com.intellij.openapi.editor.EditorMouseHoverPopupManager$Context.access$2100(EditorMouseHoverPopupManager.java:438)
        at com.intellij.openapi.editor.EditorMouseHoverPopupManager.lambda$null$7(EditorMouseHoverPopupManager.java:211)
        at com.intellij.openapi.editor.EditorMouseHoverPopupManager$$Lambda$6578/0x0000000802f06c40.run(Unknown Source)
        at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
        at com.intellij.openapi.editor.EditorMouseHoverPopupManager.lambda$scheduleProcessing$8(EditorMouseHoverPopupManager.java:210)
        at com.intellij.openapi.editor.EditorMouseHoverPopupManager$$Lambda$6034/0x0000000803111440.run(Unknown Source)
        at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
        at com.intellij.util.Alarm$Request.runSafely(Alarm.java:367)
        at com.intellij.util.Alarm$Request.run(Alarm.java:357)
        at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11.0.7/Executors.java:515)
        at java.util.concurrent.FutureTask.run(java.base@11.0.7/FutureTask.java:264)
        at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
        at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
        at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1$$Lambda$490/0x000000080062cc40.run(Unknown Source)
        at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:210)
        at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.7/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.7/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.7/Thread.java:834)

Found 1 deadlock.


```

**Comment by YiiGuxing** [comment]
呃。。。打印个日志都能死锁。。。
请问题此事问题出现频率高吗？

**Comment by LuckyMagacian** [comment]
> 呃。。。打印个日志都能死锁。。。
> 请问题此事问题出现频率高吗？

已经出现多次,不过之前都没开visual vm观察原因 
目前只能暂时停用插件了  可能在项目有较多文件的时候比较容易触发

**Comment by YiiGuxing** [comment]
你可以不用禁用插件，只需要在插件设置页取消勾选“文档翻译”选项就行的，这个问题是出现在文档翻译功能上的。

**Comment by LuckyMagacian** [comment]
> 你可以不用禁用插件，只需要在插件设置页取消勾选“文档翻译”选项就行的，这个问题是出现在文档翻译功能上的。

OKOK

**Comment by YiiGuxing** [comment]
新版本已发布，请留意一下是否还有这个问题。
