### ISSUE TITLE
翻译错误 

### ISSUE THREAD

**Issue by 626167431** [YiiGuxing/TranslationPlugin#554]
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:242)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:178)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Unknown language code:hkm
	at cn.yiiguxing.plugin.translate.trans.Lang$Companion.valueOfBaiduCode(Languages.kt:389)
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslation.toTranslation(BaiduTranslation.kt:25)
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 6 more

**Comment by YiiGuxing** [comment]
这是一个语言代码解析错误的问题，但由于百度翻译使用的语言代码不是国际标准代码，且其文档中提供相应的代码对应表也没有该代码，所以目前还无法解决。。。如果百度翻译文档更新了语言代码对应表，我会第一时间更新代码的。

**Comment by 626167431** [comment]
能否阻止报错 要不一直出现这个问题




在2020年07月24日 09:24，Yii.Guxing 写道：

这是一个语言代码解析错误的问题，但由于百度翻译使用的语言代码不是国际标准代码，且其文档中提供相应的代码对应表也没有该代码，所以目前还无法解决。。。如果百度翻译文档更新了语言代码对应表，我会第一时间更新代码的。

**Comment by YiiGuxing** [comment]
一直出现？你翻译的是哪些内容？如果不是很需要自动文档翻译的话，可以暂时关闭自动文档翻译：取消勾选“文档翻译”选项。

**Comment by YiiGuxing** [comment]
还有就是最近比较忙，没有多少时间处理问题，只能等忙完了。。。

**Comment by 626167431** [comment]
去掉了 翻译文档 选项后。没有在次出现了。谢谢




在2020年07月24日 11:13，Yii.Guxing 写道：

还有就是最近比较忙，没有多少时间处理问题，只能等忙完了。。。

**Comment by qqsheji** [comment]
我这现在也出现这个问题

**Comment by qqsheji** [comment]
前几天都没事，最近两天就这样了

**Comment by 626167431** [comment]
去掉了 翻译文档 选项后。 应该可以 



| |
自己
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年9月16日 ***@***.***> 写道：

前几天都没事，最近两天就这样了

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qqsheji** [comment]
我这里已经去掉了翻译文档，不知道咋突然就不行了，报错
>Plugin v3.1-201  
>Android Studio 4.2.1  
>Build #AI-202.7660.26.42.7351085, built on May 11, 2021  
>Runtime version: 11.0.8+10-b944.6842174 amd64  
>VM: OpenJDK 64-Bit Server VM by N/A  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:274)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2709)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2695)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:385)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:439)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:105)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:90)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 12 more
```

**Comment by qqsheji** [comment]
我看配置用的google：
![image](https://user-images.githubusercontent.com/5907480/133867695-90c5cb32-2160-485d-a28a-de3989ac033e.png)

**Comment by qqsheji** [comment]
再接在浏览器访问google.cn 是没有问题的

**Comment by YiiGuxing** [comment]
> 直接在浏览器访问google.cn 是没有问题的

@qqsheji #827

**Comment by qqsheji** [comment]
非常感谢，可以了
