### ISSUE TITLE
翻译文档翻译失败提示错误NoClassDefFoundError: com/sun/javadoc/DocErrorReporter

### ISSUE THREAD

**Issue by mingjunChan** [YiiGuxing/TranslationPlugin#567]
*  [x]  我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
*  [x]  我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
Translate Documentation 异常
### 问题描述
尝试对jdk中的代码文档进行翻译，提示翻译失败，预期是能正确翻译的
![image](https://user-images.githubusercontent.com/11487892/91398865-8181c200-e86f-11ea-8bd2-3a604a9546d1.png)

### 环境 & 错误日志
Failed to translate documentation: com/sun/javadoc/DocErrorReporter

>Plugin v3.0-SNAPSHOT  
>IntelliJ IDEA 2020.1  
>Build #IU-201.6668.121, built on April 8, 2020  
>Runtime version: 11.0.6+8-b765.25 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.15.3

```
java.lang.NoClassDefFoundError: com/sun/javadoc/DocErrorReporter
	at ch.raffael.mddoclet.integrations.idea.MarkdownDocumentationProvider.generateDoc(MarkdownDocumentationProvider.java:127)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:138)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1$lambda$1.compute(TranslateDocumentationAction.kt:56)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1$lambda$1.compute(TranslateDocumentationAction.kt:30)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: com.sun.javadoc.DocErrorReporter PluginClassLoader[ch.raffael.mddoclet.integrations.idea.MarkdownDocletIdea, 1.4-0] com.intellij.ide.plugins.cl.PluginClassLoader@7e1c455
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 13 more
```

**Comment by mingjunChan** [comment]
有人帮帮我吗

**Comment by YiiGuxing** [comment]
@mingjunChan 这似乎是和markdown-doclet插件有冲突了，错误发生在markdown-doclet的内部，你可以尝试禁用markdown-doclet插件看看是否能正常使用。

**Comment by mingjunChan** [comment]
> @mingjunChan 这似乎是和markdown-doclet插件冲突了，错误发生在markdown-doclet的内部，你可以尝试禁用markdown-doclet插件看看是否能够正常使用。

完美解决问题，应该确实属于插件冲突问题，感谢
