### ISSUE TITLE
Failed to translate documentation: Translation failed: Text is too long

### ISSUE THREAD

**Issue by cololi** [YiiGuxing/TranslationPlugin#571]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]*

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Description
Enable translate documentation, because text is too long it crashed.

Failed to translate documentation: Translation failed: Text is too long

>Plugin v2.9.2  
>PyCharm 2020.2.1  
>Build #PY-202.6948.78, built on August 26, 2020  
>Runtime version: 11.0.8+10-b944.31 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: macOS 10.15.6

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Youdao Translate :: Translation failed: Text is too long
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:107)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:106)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:39)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Youdao Translate :: Translate failed: 103
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:99)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:75)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:73)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:84)
	... 10 more
```

**Comment by cololi** [comment]
Can you add value to the limit translate text size?

**Comment by YiiGuxing** [comment]
good idea!
