### ISSUE TITLE
[Auto Generated]Plugin error occurred: Cannot load class cn.yiiguxing.plugin.translate.action.TranslateRenderedDocSelectionAction ( error: ...

### ISSUE THREAD

**Issue by Dmitriyfromrussia** [YiiGuxing/TranslationPlugin#5764]
:warning:_`[Auto Generated Report]-=2A5719A452F6BE3E0AB2EDB6B8EE0F29=-`_

## Description

Cannot load class cn.yiiguxing.plugin.translate.action.TranslateRenderedDocSelectionAction (
  error: cn/yiiguxing/intellij/compat/action/UpdateInBackgroundCompatAction,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Translation, id=cn.yiiguxing.plugin.translate, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.2/plugins/instrumented-TranslationPlugin-3.6.1.jar, version=3.6.1, package=null, isBundled=false), packagePrefix=null, state=active)
)

## Environments
> **Plugin version: 3.6.1**

IntelliJ IDEA 2023.2 (Community Edition)
Build #IC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Operating system: macOS 12.4
Last action id: null

## Stack Trace
```
com.intellij.diagnostic.PluginException: Cannot load class cn.yiiguxing.plugin.translate.action.TranslateRenderedDocSelectionAction (
  error: cn/yiiguxing/intellij/compat/action/UpdateInBackgroundCompatAction,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=Translation, id=cn.yiiguxing.plugin.translate, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.2/plugins/instrumented-TranslationPlugin-3.6.1.jar, version=3.6.1, package=null, isBundled=false), packagePrefix=null, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:331)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:178)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationActionProvider.additionalActions(TranslateDocumentationActionProvider.kt:21)
	at com.intellij.codeInsight.documentation.render.DocRenderer.getContextMenuGroup(DocRenderer.java:205)
	at com.intellij.openapi.editor.impl.EditorImpl$DefaultPopupHandler.getActionGroup(EditorImpl.java:5192)
	at com.intellij.openapi.editor.impl.ContextMenuPopupHandler.handlePopup(ContextMenuPopupHandler.java:29)
	at com.intellij.openapi.editor.impl.EditorImpl.invokePopupIfNeeded(EditorImpl.java:5133)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMousePressedCommand(EditorImpl.java:3993)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mousePressed(EditorImpl.java:3905)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4578)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:791)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:740)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:734)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:762)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: cn/yiiguxing/intellij/compat/action/UpdateInBackgroundCompatAction
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:268)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:113)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:238)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:188)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:326)
	... 55 more
Caused by: java.lang.ClassNotFoundException: cn.yiiguxing.intellij.compat.action.UpdateInBackgroundCompatAction PluginClassLoader(plugin=PluginDescriptor(name=Translation, id=cn.yiiguxing.plugin.translate, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.2/plugins/instrumented-TranslationPlugin-3.6.1.jar, version=3.6.1, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 63 more
```

**Comment by YiiGuxing** [comment]
Please use the correct method to install the plugin.
