### ISSUE TITLE
编辑markdown文件时内存溢出

### ISSUE THREAD

**Issue by harvies** [YiiGuxing/TranslationPlugin#584]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
编辑markdown文件导致内存溢出

### 环境 & 错误日志
- 插件版本: 2.9.2
- IDE版本:  IDEA 2020.1.1
- 操作系统版本: Mac
- 错误日志:
![image](https://user-images.githubusercontent.com/16585330/95833432-31eb4d00-0d6e-11eb-92f0-87f823cc375d.png)
![image](https://user-images.githubusercontent.com/16585330/95833124-cb662f00-0d6d-11eb-83c5-ac08f3d2f9f0.png)
![image](https://user-images.githubusercontent.com/16585330/95833175-dae57800-0d6d-11eb-949a-7ac152c88295.png)
![image](https://user-images.githubusercontent.com/16585330/95833232-e9cc2a80-0d6d-11eb-9fb4-40aa7fb5a7a7.png)

```
"ApplicationImpl pooled thread 478" prio=4 tid=1382 RUNNABLE
    at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
    at java.util.Arrays.copyOf(Arrays.java:3841)
    at javax.swing.text.DefaultStyledDocument$ElementSpec.<init>(DefaultStyledDocument.java:1267)
    at javax.swing.text.html.HTMLDocument$HTMLReader.addContent(HTMLDocument.java:3916)
       Local Variable: javax.swing.text.DefaultStyledDocument$ElementSpec#1131
    at javax.swing.text.html.HTMLDocument$HTMLReader.addContent(HTMLDocument.java:3890)
    at javax.swing.text.html.HTMLDocument$HTMLReader.preContent(HTMLDocument.java:3794)
       Local Variable: char[]#26531
    at javax.swing.text.html.HTMLDocument$HTMLReader.handleText(HTMLDocument.java:2773)
    at javax.swing.text.html.parser.DocumentParser.handleText(DocumentParser.java:271)
    at javax.swing.text.html.parser.Parser.handleText(Parser.java:409)
       Local Variable: javax.swing.text.html.parser.TagElement#3
    at javax.swing.text.html.parser.Parser.endTag(Parser.java:524)
    at javax.swing.text.html.parser.Parser.parseTag(Parser.java:1934)
    at javax.swing.text.html.parser.Parser.parseContent(Parser.java:2195)
    at javax.swing.text.html.parser.Parser.parse(Parser.java:2372)
       Local Variable: java.io.StringReader#1
    at javax.swing.text.html.parser.DocumentParser.parse(DocumentParser.java:135)
       Local Variable: javax.swing.text.html.parser.DocumentParser#1
    at javax.swing.text.html.parser.ParserDelegator.parse(ParserDelegator.java:113)
    at javax.swing.text.html.HTMLEditorKit.read(HTMLEditorKit.java:263)
       Local Variable: javax.swing.text.html.HTMLDocument$HTMLReader#1
    at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:102)
       Local Variable: javax.swing.text.html.HTMLDocument#28
       Local Variable: org.jsoup.nodes.Element#1
    at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:39)
       Local Variable: org.jsoup.nodes.Document#1
       Local Variable: cn.yiiguxing.plugin.translate.trans.YoudaoTranslator#1
       Local Variable: java.lang.String#1381600
    at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       Local Variable: cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1#1
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       Local Variable: java.util.concurrent.ThreadPoolExecutor$Worker#41
    at java.lang.Thread.run(Thread.java:834)

```

**Comment by YiiGuxing** [comment]
@harvies 能否提供你的markdown文件？是文件内容很大吗？

**Comment by harvies** [comment]
> @harvies 能否提供你的markdown文件？是文件内容很大吗？

不是很大，现在没复现了

**Comment by YiiGuxing** [comment]
那我现在先关了这个问题，烦请你多留意一下，如果后面出现的话你再重新打开，我再想办法优化一下。
