### ISSUE TITLE
插件无法 通过idea 代理，提示连接超时

### ISSUE THREAD

**Issue by solante1012** [YiiGuxing/TranslationPlugin#589]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

请详细描述问题，确保包括:
1 提示错误
百度和有道 都提示连不上网，连接超时，proxy已经配置，但似乎不起作用
Google翻译 提示下面错误

### 环境 & 错误日志
- 插件版本: 2.9.2 
- IDE版本:  IDEA 2020.2 
- 操作系统版本: Windows 10 

- 错误日志:
```
在此粘贴错误日志
```java
14:49	TKK
			更新TTK失败，请检查网络连接
			Copy to Clipboard

14:50	Documentation
			Failed to translate documentation: 翻译失败: 无法解析翻译结果
			Copy to Clipboard   关闭快速文档实时翻译

cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 无法解析翻译结果
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:107)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:76)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:37)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1.run(promise.kt:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1 path $



<!-- 获取环境与错误日志: http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb -->

**Comment by YiiGuxing** [comment]
请检查网络环境，网络问题和插件的关系并不大。。。
