### ISSUE TITLE
hyayn5@gmail.com

### ISSUE THREAD

**Issue by hyayn-HOMES** [YiiGuxing/TranslationPlugin#597]
## Preflight Checklist
*Please ensure you've completed the following steps by replacing [ ] with [x]*

* [ ] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Environment & Stack Trace
- Plugin version: 
- IDE version: 
- Operating System and version: 

>Plugin v2.9.2  
>Android Studio 4.1.1  
>Build #AI-201.8743.12.41.6953283, built on November 5, 2020  
>Runtime version: 1.8.0_242-release-1644-b01 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: Translation failed: Unknown error
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:101)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:186)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2665)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2651)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1830)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:384)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:438)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:75)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:73)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:80)
	... 8 more
```

**Comment by YiiGuxing** [comment]
你的IP可能已被谷歌翻译服务所限制，请稍候再尝试。
