### ISSUE TITLE
翻译失败: 网络异常 Remote host terminated the handshake. host=translate.google.cn

### ISSUE THREAD

**Issue by WangJincheng4869** [YiiGuxing/TranslationPlugin#651]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
网络应该是通的，但是会出现反应失败的问题`Remote host terminated the handshake. host=translate.google.cn
`
![image](https://user-images.githubusercontent.com/41162158/104897990-0a7ece80-59b4-11eb-88dd-d3673743a55d.png)
![image](https://user-images.githubusercontent.com/41162158/104898014-1074af80-59b4-11eb-92f0-c7d269f305dc.png)
很玄学的一件事情。无论勾选与否都是会出现这样的错误
![image](https://user-images.githubusercontent.com/41162158/104898317-76613700-59b4-11eb-9710-f9163187746e.png)
但是其实使用划词翻译是可以使用的！

### 环境 & 错误日志
- 插件版本: 3.0.1
- IDE版本: 2020.3.1
- 操作系统版本:  Windows 10  19042.746

- 错误日志:
```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 网络异常
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:128)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1.run(promise.kt:401)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.NetworkException: Remote host terminated the handshake. host=translate.google.cn
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.onError(GoogleTranslator.kt:117)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:21)
	... 11 more
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1588)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:117)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:111)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:84)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:99)
	... 10 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:481)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
	... 27 more
```

**Comment by WangJincheng4869** [comment]
`cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 网络异常
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:128)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1.run(promise.kt:401)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.NetworkException: Remote host terminated the handshake. host=translate.google.cn
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.onError(GoogleTranslator.kt:117)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:21)
	... 11 more
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1588)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:117)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:111)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:84)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:99)
	... 10 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:481)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
	... 27 more`

**Comment by WangJincheng4869** [comment]
```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 网络异常
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:128)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1.run(promise.kt:401)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.NetworkException: Remote host terminated the handshake. host=translate.google.cn
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.onError(GoogleTranslator.kt:117)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:21)
	... 11 more
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1588)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1416)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1314)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:117)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:111)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:84)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:99)
	... 10 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:481)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1408)
	... 27 more
```

**Comment by YiiGuxing** [comment]
这个应该是代理的问题，可以试试关掉网络代理。
