### ISSUE TITLE
Error during translation using shortcut keys

### ISSUE THREAD

**Issue by yongrokkwon** [YiiGuxing/TranslationPlugin#684]
I tried to translate the following languages through the Ctrl + Shift + O shortcut.
`There is a history of making payment before.\nWould you like to continue?`
However, the following error occurred

Translation failed: Unknown error

>Plugin v3.0.1  
>Android Studio 4.1.2  
>Build #AI-201.8743.12.41.7042882, built on December 20, 2020  
>Runtime version: 1.8.0_242-release-1644-b01 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: Translation failed: Unknown error
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:122)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.google.cn/translate_a/single?sl=auto&tl=ko&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dj=1&ie=UTF-8&oe=UTF-8&hl=ko&tk=332809.249086
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:384)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:438)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:85)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:95)
	... 8 more
```

Please let me know if you have any more information you need. I want this error to be resolved.

**Comment by YiiGuxing** [comment]
Too many requests, please try again later.
