### ISSUE TITLE
Failed to translate documentation: 翻译失败: 无法解析翻译结果

### ISSUE THREAD

**Issue by jianyuepei** [YiiGuxing/TranslationPlugin#686]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: Plugin v3.0.1 
- IDE版本: IntelliJ IDEA 2020.3.2
- 操作系统版本: OS: macOS 11.2.3
- 错误日志:
```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 无法解析翻译结果
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:128)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:195)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:86)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:99)
	... 14 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 25 more
```

**Comment by zs808** [comment]
+1

**Comment by ftwater** [comment]
响应内容结构目前如下：
```json
[[[[["\u003cdiv class=\"content\"\u003e提取当前位置，前进和信号的元素。仅在保持锁定状态时呼叫。\u003cp\u003e\u003c/p\u003e\u003c/div\u003e\u003ctable class=\"sections\"\u003e\u003c/table\u003e"]],null,"en"]]]
```

**Comment by xiaochai1027** [comment]
+1 同样谷歌的文档翻译 有问题，刚才试了下有道，计费太贵了

**Comment by qinfen180** [comment]
+1，目前发现谷歌翻译文档有这个问题，直接翻译是没问题的

**Comment by liu95-maker** [comment]
是的 我也是这个问题 暂时先用百度的

**Comment by YiiGuxing** [comment]
家人们呐，不要慌，问题不大~~~（其实一开始内心慌得一比，深怕这个接口再也不能用了。。。）

**Comment by javaxingtao** [comment]
从昨天开始我一顿搞,原来不是我的问题

**Comment by liangtengyu** [comment]
+1  Failed to translate documentation: 翻译失败: 无法解析翻译结果

**Comment by ftwater** [comment]
没写过kotlin，马马虎虎硬编码取出了值，在我的使用场景中暂时可以正常翻译，应个急，有需要的可以取一下，坐等作者commit正式代码后更新插件：D
[应急插件](https://github.com/ftwater/TranslationPluginForTemp/blob/main/TranslationPlugin-3.1-SNAPSHOT.zip?raw=true)

**Comment by AlohaQwQ** [comment]
+1 我访问 translate.google.com 会被墙，不知道跟这个有没有关系

**Comment by lm-lan** [comment]
me too，昨天开始这样了

**Comment by jianyuepei** [comment]
> +1 我访问 translate.google.com 会被墙，不知道跟这个有没有关系

跟这个没关系，我开着VPN，开全局模式，也是报错。

**Comment by makersy** [comment]
我也是，昨天开始这样了

**Comment by YiiGuxing** [comment]
大家先暂时使用其他服务商的或者先暂停使用这个文档翻译哈，我会尽快修复的。。。。。
