### ISSUE TITLE
翻译失败：无法解析翻译结果，Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]

### ISSUE THREAD

**Issue by yuxintan** [YiiGuxing/TranslationPlugin#692]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
翻译使用2.9.1和2.9.2都无法完成，3.0.0和3.0.1错误提示不兼容。
### 问题描述

翻译Java doc就会复现问题，无法解析json

### 环境 & 错误日志
Failed to translate documentation: 翻译失败: 无法解析翻译结果

>Plugin v2.9.1  
>IntelliJ IDEA 2019.3.3  
>Build #IU-193.6494.35, built on February 11, 2020  
>Runtime version: 11.0.5+10-b520.38 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.15.5

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 无法解析翻译结果
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:94)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:205)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:176)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:194)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:939)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:91)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:518)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:500)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:61)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:71)
	... 9 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 21 more
```

下面是2.9.2的，报错相同

Failed to translate documentation: 翻译失败: 无法解析翻译结果

>Plugin v2.9.2  
>IntelliJ IDEA 2019.3.3  
>Build #IU-193.6494.35, built on February 11, 2020  
>Runtime version: 11.0.5+10-b520.38 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.15.5

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 无法解析翻译结果
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:107)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:76)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:37)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:196)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:939)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:75)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:518)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:500)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:73)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:84)
	... 9 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 21 more
```

**Comment by yuxintan** [comment]
使用百度翻译后能正常用，可能是google接口返回的数据有些问题。

**Comment by YiiGuxing** [comment]
谷歌接口的响应内容变更了，需要重新适配。
