### ISSUE TITLE
gson翻译失败

### ISSUE THREAD

**Issue by shanmie** [YiiGuxing/TranslationPlugin#694]
## 问题详情
gson 翻译失败
### 问题描述

  1. 在idea设置里面打开 Editor-->General-->show quick documentation on mouse move 选中选项
  2. 鼠标悬浮源码
  3. 悬浮某个源码函数时有源码注释  此时应该会对源码注释翻译

### 环境 & 错误日志
- 插件版本: 2.9.1 
- IDE版本:  IDEA 2019.2.4 
- 操作系统版本: mac os 
- 错误日志:
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 无法解析翻译结果
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:95)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:205)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:176)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:242)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:939)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:91)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:63)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:72)
	... 6 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 18 more

**Comment by YiiGuxing** [comment]
#686
