### ISSUE TITLE
使用Translate Document总是报错

### ISSUE THREAD

**Issue by springning** [YiiGuxing/TranslationPlugin#696]
使用的api是google的，当使用Translate document时无法使用，日志报错内容如下:
2021-03-19 14:45:01,824 [ 664919]   INFO -                         STDOUT - INFO - Translate url: https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=666286.848688 
2021-03-19 14:45:01,825 [ 664920]   INFO - anslate.trans.GoogleTranslator - Translate url: https://translate.googleapis.com/translate_a/t?sl=auto&tl=zh-CN&client=te_lib&format=html&tk=666286.848688 
2021-03-19 14:45:02,715 [ 665810]   INFO -                         STDOUT - INFO - Translate result: [[[[["\u003cdiv class=\"content\"\u003e描述表生态系统中值的数据类型。此类的实例可用于声明操作的输入和/或输出类型。\u003cp\u003e \u003ca href=\"psi_element://org.apache.flink.table.types.DataType\"\u003e\u003ccode\u003eDataType\u003c/code\u003e\u003c/a\u003e类有两个职责：声明逻辑类型，并向计划者提供有关数据物理表示的提示。虽然逻辑类型是强制性的，但提示是可选的，但对于其他API而言很有用。\u003c/p\u003e\u003cp\u003e逻辑类型独立于任何物理表示，并且接近SQL标准的“数据类型”术语。有关可用逻辑类型及其属性的更多信息，请参见\u003ca href=\"psi_element://org.apache.flink.table.types.logical.LogicalType\"\u003e\u003ccode\u003eLogicalType\u003c/code\u003e\u003c/a\u003e及其子类。\u003c/p\u003e\u003cp\u003e在表格生态系统的边缘需要物理提示。提示指示实现所需的数据格式。例如，数据源可以表示它使用\u003ca href=\"psi_element://java.sql.Timestamp\"\u003e\u003ccode\u003ejava.sql.Timestamp\u003c/code\u003e\u003c/a\u003e类而不是\u003ca href=\"psi_element://java.time.LocalDateTime\"\u003e\u003ccode\u003ejava.time.LocalDateTime\u003c/code\u003e\u003c/a\u003e为逻辑时间戳生成值。有了这些信息，运行时就可以将产生的类转换为其内部数据格式。作为回报，数据接收器可以声明其从运行时使用的数据格式。\u003c/p\u003e\u003c/div\u003e\u003ctable class=\"sections\"\u003e\u003ctbody\u003e\u003ctr\u003e\u003ctd valign=\"top\" class=\"section\"\u003e\u003cp\u003e也可以看看：\u003c/p\u003e\u003c/td\u003e\u003ctd valign=\"top\"\u003e\u003cp\u003e \u003ca href=\"psi_element://org.apache.flink.table.api.DataTypes\"\u003e\u003ccode\u003efor a list of supported data types and instances of this class.\u003c/code\u003e\u003c/a\u003e\u003c/p\u003e\u003c/td\u003e\u003c/tr\u003e\u003c/tbody\u003e\u003c/table\u003e"]],null,"en"]]] 
2021-03-19 14:45:02,715 [ 665810]   INFO - anslate.trans.GoogleTranslator - Translate result: [[[[["\u003cdiv class=\"content\"\u003e描述表生态系统中值的数据类型。此类的实例可用于声明操作的输入和/或输出类型。\u003cp\u003e \u003ca href=\"psi_element://org.apache.flink.table.types.DataType\"\u003e\u003ccode\u003eDataType\u003c/code\u003e\u003c/a\u003e类有两个职责：声明逻辑类型，并向计划者提供有关数据物理表示的提示。虽然逻辑类型是强制性的，但提示是可选的，但对于其他API而言很有用。\u003c/p\u003e\u003cp\u003e逻辑类型独立于任何物理表示，并且接近SQL标准的“数据类型”术语。有关可用逻辑类型及其属性的更多信息，请参见\u003ca href=\"psi_element://org.apache.flink.table.types.logical.LogicalType\"\u003e\u003ccode\u003eLogicalType\u003c/code\u003e\u003c/a\u003e及其子类。\u003c/p\u003e\u003cp\u003e在表格生态系统的边缘需要物理提示。提示指示实现所需的数据格式。例如，数据源可以表示它使用\u003ca href=\"psi_element://java.sql.Timestamp\"\u003e\u003ccode\u003ejava.sql.Timestamp\u003c/code\u003e\u003c/a\u003e类而不是\u003ca href=\"psi_element://java.time.LocalDateTime\"\u003e\u003ccode\u003ejava.time.LocalDateTime\u003c/code\u003e\u003c/a\u003e为逻辑时间戳生成值。有了这些信息，运行时就可以将产生的类转换为其内部数据格式。作为回报，数据接收器可以声明其从运行时使用的数据格式。\u003c/p\u003e\u003c/div\u003e\u003ctable class=\"sections\"\u003e\u003ctbody\u003e\u003ctr\u003e\u003ctd valign=\"top\" class=\"section\"\u003e\u003cp\u003e也可以看看：\u003c/p\u003e\u003c/td\u003e\u003ctd valign=\"top\"\u003e\u003cp\u003e \u003ca href=\"psi_element://org.apache.flink.table.api.DataTypes\"\u003e\u003ccode\u003efor a list of supported data types and instances of this class.\u003c/code\u003e\u003c/a\u003e\u003c/p\u003e\u003c/td\u003e\u003c/tr\u003e\u003c/tbody\u003e\u003c/table\u003e"]],null,"en"]]] 
2021-03-19 14:45:02,716 [ 665811]   INFO -                         STDOUT - WARN - 翻译失败: 无法解析翻译结果 
2021-03-19 14:45:02,716 [ 665811]   INFO -                         STDERR - cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 无法解析翻译结果 
2021-03-19 14:45:02,716 [ 665811]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:128) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:195) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at java.base/java.lang.Thread.run(Thread.java:834) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0] 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:944) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:897) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:846) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:817) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:104) 
2021-03-19 14:45:02,717 [ 665812]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:86) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:99) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	... 10 more 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0] 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:932) 
2021-03-19 14:45:02,718 [ 665813]   INFO -                         STDERR - 	... 22 more 
2021-03-19 14:45:02,718 [ 665813]   WARN - n.TranslateDocumentationAction - 翻译失败: 无法解析翻译结果 
cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 无法解析翻译结果
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:128)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:195)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:86)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:99)
	... 10 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3 path $[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 22 more
2021-03-19 14:45:02,719 [ 665814]   INFO - notification.NotificationGroup - Notification group Document Translation is already registered 
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:27)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.kt:21)
	at cn.yiiguxing.plugin.translate.util.Notifications.showErrorNotification(Notifications.kt:25)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion$logAndShowWarning$$inlined$invokeLater$1.run(Applications.kt:183)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by YiiGuxing** [comment]
duplicate: #686

**Comment by YiiGuxing** [comment]
先暂时使用其他服务商的或者先暂停使用这个文档翻译哈，我会尽快修复的。。。。。
