### ISSUE TITLE
Failed to translate documentation: 翻译失败: 无法解析翻译结果

### ISSUE THREAD

**Issue by Carlos920** [YiiGuxing/TranslationPlugin#701]
### 问题描述
更新3.0.2版本后依旧无法使用文档翻译

### 环境 & 错误日志

Failed to translate documentation: 翻译失败: 无法解析翻译结果

>Plugin v3.0.2  
>IntelliJ IDEA 2020.3.3  
>Build #IU-203.7717.56, built on March 15, 2021  
>Runtime version: 11.0.10+8-b1145.96 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 无法解析翻译结果
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:128)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:195)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:86)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:99)
	... 14 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:386)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 26 more
```

**Comment by smoewhere** [comment]
看了一下返回结果，好像又变成Translate result: ["\u003cdiv class=\"content\"****","en"]这样的形式了，gson解析成object直接报错了
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $

**Comment by j150478** [comment]
同样的问题，今天的插件更新，并没有解决文档翻译的问题

**Comment by smoewhere** [comment]
好像前几天变成了[[[[["\u003cdiv class=\"content\"\u003e提取当前位置，前进和信号的元素。仅在保持锁定状态时呼叫。\u003cp\u003e\u003c/p\u003e\u003c/div\u003e\u003ctable class=\"sections\"\u003e\u003c/table\u003e"]],null,"en"]]]这样的形式，然后今天又改回来了。。导致这次的修复又出问题。 如果要临时解决的话，装回3.0.1版本的就行。
https://plugins.jetbrains.com/plugin/8579-translation/versions

**Comment by cheng-123-yy** [comment]
我的也是这种情况，以前的都可以用，更新了之后文档翻译就不行了

**Comment by makersy** [comment]
> 好像前几天变成了[[[[["\u003cdiv class="content"\u003e提取当前位置，前进和信号的元素。仅在保持锁定状态时呼叫。\u003cp\u003e\u003c/p\u003e\u003c/div\u003e\u003ctable class="sections"\u003e\u003c/table\u003e"]],null,"en"]]]这样的形式，然后今天又改回来了。。导致这次的修复又出问题。 如果要临时解决的话，装回3.0.1版本的就行。
> https://plugins.jetbrains.com/plugin/8579-translation/versions

改回3.0.1版本有效

**Comment by jzdayz** [comment]
> > 好像前几天变成了[[[[["\u003cdiv class="content"\u003e提取当前位置，前进和信号的元素。仅在保持锁定状态时呼叫。\u003cp\u003e\u003c/p\u003e\u003c/div\u003e\u003ctable class="sections"\u003e\u003c/table\u003e"]],null,"en"]]]这样的形式，然后今天又改回来了。。导致这次的修复又出问题。 如果要临时解决的话，装回3.0.1版本的就行。
> > https://plugins.jetbrains.com/plugin/8579-translation/versions
> 
> 改回3.0.1版本有效

+1

**Comment by yuxiangfan** [comment]
我刚更新到最新版本3.0.3，已经修复文档实时翻译，感谢作者！
