### ISSUE TITLE
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor is already disposed

### ISSUE THREAD

**Issue by YiiGuxing** [YiiGuxing/TranslationPlugin#707]
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor is already disposed
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:86)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:1027)
	at com.intellij.openapi.editor.impl.view.LogicalPositionCache.checkDisposed(LogicalPositionCache.java:193)
	at com.intellij.openapi.editor.impl.view.LogicalPositionCache.getLineInfo(LogicalPositionCache.java:178)
	at com.intellij.openapi.editor.impl.view.LogicalPositionCache.offsetToLogicalPosition(LogicalPositionCache.java:90)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.offsetToLogicalPosition(EditorCoordinateMapper.java:81)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.offsetToVisualPosition(EditorCoordinateMapper.java:216)
	at com.intellij.openapi.editor.impl.view.EditorView.offsetToVisualPosition(EditorView.java:190)
	at com.intellij.openapi.editor.impl.EditorImpl.offsetToVisualPosition(EditorImpl.java:1457)
	at cn.yiiguxing.plugin.translate.ui.BalloonPositionTrackerKt.getBalloonLocation(BalloonPositionTracker.kt:49)
	at cn.yiiguxing.plugin.translate.ui.BalloonPositionTrackerKt.access$getBalloonLocation(BalloonPositionTracker.kt:1)
	at cn.yiiguxing.plugin.translate.ui.BalloonPositionTracker.recalculateLocation(BalloonPositionTracker.kt:32)
	at cn.yiiguxing.plugin.translate.ui.BalloonPositionTracker.recalculateLocation(BalloonPositionTracker.kt:16)
	at cn.yiiguxing.plugin.translate.ui.balloon.BalloonImpl.revalidate(BalloonImpl.java:844)
	at com.intellij.util.ui.PositionTracker.revalidate(PositionTracker.java:70)
	at com.intellij.util.ui.PositionTracker.componentResized(PositionTracker.java:51)
	at java.desktop/java.awt.AWTEventMulticaster.componentResized(AWTEventMulticaster.java:168)
	at java.desktop/java.awt.Component.processComponentEvent(Component.java:6478)
	at java.desktop/java.awt.Component.processEvent(Component.java:6432)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

_Originally posted by @Marblog in https://github.com/YiiGuxing/TranslationPlugin/issues/705#issuecomment-803897863_

**Comment by YiiGuxing** [comment]
@Marblog 请问这个问题是如何出现的，可以重现不？

**Comment by 13149107467** [comment]
我也遇到了这个问题，但似乎重新打开编译器，或者重新配置tomcat服务就好了
