### ISSUE TITLE
PHPSTORM报出错误

### ISSUE THREAD

**Issue by Ailen1988** [YiiGuxing/TranslationPlugin#71]
该问题是我在PHPSTORM刚启动的时候, 使用默认的ALT+R翻译时报的错误, 另外ALT+R执行翻译时插件报出"签名错误", 我又使用ALT+1翻译文件内容, 则是可行的.

这个是PHPSTORM的报错
![qq 20170627094638](https://user-images.githubusercontent.com/10841601/27567448-5aa2ebc8-5b1e-11e7-815a-b55f2e31ee7d.png)

下面是日志信息
```
InvocationTargetException: java.nio.channels.ClosedByInterruptException null
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.nio.channels.ClosedByInterruptException null
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:230)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:228)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:238)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:205)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
	at com.intellij.ide.passwordSafe.PasswordSafe.getInstance(PasswordSafe.java:28)
	at cn.yiiguxing.plugin.translate.compat.PasswordSafeCompat.getPassword(PasswordSafeCompat.java:31)
	at cn.yiiguxing.plugin.translate.Settings.getAppPrivateKey(Settings.java:151)
	at cn.yiiguxing.plugin.translate.Translator.getQueryUrl(Translator.java:90)
	at cn.yiiguxing.plugin.translate.Translator.access$000(Translator.java:20)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:164)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.io.InputStream.read(InputStream.java:101)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:81)
	at java.security.DigestInputStream.read(DigestInputStream.java:124)
	at com.google.common.io.LittleEndianDataInputStream.readAndCheckByte(LittleEndianDataInputStream.java:223)
	at com.google.common.io.LittleEndianDataInputStream.readInt(LittleEndianDataInputStream.java:116)
	at com.intellij.credentialStore.kdbx.KdbxSerializerKt.a(KdbxSerializer.kt:122)
	at com.intellij.credentialStore.kdbx.KdbxSerializerKt.readKdbxHeader(KdbxSerializer.kt:145)
	at com.intellij.credentialStore.kdbx.KdbxSerializer.createUnencryptedInputStream(KdbxSerializer.kt:61)
	at com.intellij.credentialStore.kdbx.KdbxStreamFormat.load(kdbx.kt:55)
	at com.intellij.credentialStore.kdbx.KdbxKt.loadKdbx(kdbx.kt:36)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:78)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:44)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.computeProvider(PasswordSafeImpl.kt:38)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt:46)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	... 20 more
Caused by:

java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:164)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.io.InputStream.read(InputStream.java:101)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:81)
	at java.security.DigestInputStream.read(DigestInputStream.java:124)
	at com.google.common.io.LittleEndianDataInputStream.readAndCheckByte(LittleEndianDataInputStream.java:223)
	at com.google.common.io.LittleEndianDataInputStream.readInt(LittleEndianDataInputStream.java:116)
	at com.intellij.credentialStore.kdbx.KdbxSerializerKt.a(KdbxSerializer.kt:122)
	at com.intellij.credentialStore.kdbx.KdbxSerializerKt.readKdbxHeader(KdbxSerializer.kt:145)
	at com.intellij.credentialStore.kdbx.KdbxSerializer.createUnencryptedInputStream(KdbxSerializer.kt:61)
	at com.intellij.credentialStore.kdbx.KdbxStreamFormat.load(kdbx.kt:55)
	at com.intellij.credentialStore.kdbx.KdbxKt.loadKdbx(kdbx.kt:36)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:78)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:44)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.computeProvider(PasswordSafeImpl.kt:38)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt:46)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:228)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:238)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:205)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
	at com.intellij.ide.passwordSafe.PasswordSafe.getInstance(PasswordSafe.java:28)
	at cn.yiiguxing.plugin.translate.compat.PasswordSafeCompat.getPassword(PasswordSafeCompat.java:31)
	at cn.yiiguxing.plugin.translate.Settings.getAppPrivateKey(Settings.java:151)
	at cn.yiiguxing.plugin.translate.Translator.getQueryUrl(Translator.java:90)
	at cn.yiiguxing.plugin.translate.Translator.access$000(Translator.java:20)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Ailen1988** [comment]
补充一下图片
![tim 20170627103854](https://user-images.githubusercontent.com/10841601/27568606-57b01736-5b25-11e7-861c-88972d713adb.png)

**Comment by YiiGuxing** [comment]
请问每次使用ALT+R都会报异常吗？报异常应该并不是插件的问题。至于"签名错误"，请设置正确的APP Key 和 APP 密钥。

**Comment by Ailen1988** [comment]
先谢谢你做了这么赞的插件, 很棒! 

下面说一下问题哈, 我之前一直没有用过ALT+R, 以前用的其他的, 其他的都是没有问题的, 至于"签名错误", 应该不是APP KEY造成的, 因为我使用其他的都是正常的.

**Comment by YiiGuxing** [comment]
ALT+R不会有"签名错误"的提示的。
