### ISSUE TITLE
每次重启以后 百度翻译的应用ID和密钥就必须重新输入，而且还一直报错

### ISSUE THREAD

**Issue by hjk0605** [YiiGuxing/TranslationPlugin#711]
错误信息：

cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: 翻译失败: 未知错误[58003]
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:95)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:242)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:178)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:242)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Baidu Translate :: Translate failed: 58003
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:102)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:63)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:17)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:72)
	... 6 more

**Comment by YiiGuxing** [comment]
应用ID无法保存请看：  https://github.com/YiiGuxing/TranslationPlugin#faq

报错是因为：
> 8. 为什么我的请求会返回58003？
因黑产采用不正当手段收集用户APPID及密钥，由此产生的盗刷字符量现象日益猖獗，系统风控增加了IP校验规则，如同一IP当日使用多个APPID发送翻译请求，则该IP将被封禁当日请求权限，次日解封。
但由于IP多变，应用场景复杂，难免出现误伤正常使用的情况。如您属正常使用，但出现58003的提示，请发送邮件至 translate_api@baidu.com，同时提供如下信息。我方在收到邮件后将与您取得联系，核实后将解除封禁。
公司名称：
产品名称：
联系人：
联系方式：
服务器IP：
APPID：
注：
1）如提供信息不全，将影响审核通过率。
2）请不要将您的APPID及密钥泄露出去，也不要填写到任何第三方软件中，包括“SCITranslate”、“微信学英语”、“Potplayer”等软件以及各类计算机辅助翻译工具插件。如因此造成密钥泄露形成经济损失，或因此被封禁，百度翻译将有权拒绝解封。
