### ISSUE TITLE
IDE error occurred

### ISSUE THREAD

**Issue by megoRU** [YiiGuxing/TranslationPlugin#721]
## Preflight Checklist

* [x] I have read the [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq), but still can't solve my problem.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Description

I had 2 projects running, I closed one and an error appeared

### Environment & Stack Trace
- Plugin version: 3.1
- IDE version: IDEA 2021.1
- Operating System and version:  Windows 10 pro v19043.899

- Stack Trace:
```
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=DiscordBot, containerState=DISPOSE_COMPLETED, componentStore=C:\java_GitHub\DiscordBot) (disposed)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:203)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:440)
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:22)
	at com.intellij.openapi.fileEditor.impl.HTMLEditorProvider$Companion.openEditor(HTMLEditorProvider.kt:49)
	at cn.yiiguxing.plugin.translate.update.UpdateManager$Companion$browseWhatsNew$$inlined$invokeLater$1.run(Applications.kt:183)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by toutoumu** [comment]
还有一个类似的异常
Details: Current thread: Thread[Alarm Pool,4,Idea Thread Group] 1933321113
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1920747192

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:179)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:616)
	at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:32)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:340)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContext(StubBasedPsiElementBase.java:286)
	at com.intellij.psi.util.PsiTreeUtil.getContextOfType(PsiTreeUtil.java:611)
	at com.intellij.psi.util.PsiTreeUtil.getContextOfType(PsiTreeUtil.java:601)
	at com.intellij.psi.css.CssElement.getLanguageOf(CssElement.java:38)
	at com.intellij.psi.css.impl.stubs.base.CssStubElement.getLanguage(CssStubElement.java:40)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$fetchExternalDocumentation$1.invoke(TranslatingDocumentationProvider.kt:73)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$fetchExternalDocumentation$1.invoke(TranslatingDocumentationProvider.kt:24)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.nullIfRecursive(TranslatingDocumentationProvider.kt:98)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.access$nullIfRecursive(TranslatingDocumentationProvider.kt:88)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider.fetchExternalDocumentation(TranslatingDocumentationProvider.kt:59)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.fetchExternalDocumentation(CompositeDocumentationProvider.java:231)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.getDocumentation(DocumentationManager.java:1565)
	at com.intellij.codeInsight.documentation.DocumentationManager.lambda$doFetchDocInfo$20(DocumentationManager.java:1080)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
