### ISSUE TITLE
 Read access is allowed from event dispatch thread or inside read-action only

### ISSUE THREAD

**Issue by YiiGuxing** [YiiGuxing/TranslationPlugin#725]
Details: Current thread: Thread[Alarm Pool,4,Idea Thread Group] 1933321113
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 1920747192

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:179)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:616)
	at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:32)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:340)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContext(StubBasedPsiElementBase.java:286)
	at com.intellij.psi.util.PsiTreeUtil.getContextOfType(PsiTreeUtil.java:611)
	at com.intellij.psi.util.PsiTreeUtil.getContextOfType(PsiTreeUtil.java:601)
	at com.intellij.psi.css.CssElement.getLanguageOf(CssElement.java:38)
	at com.intellij.psi.css.impl.stubs.base.CssStubElement.getLanguage(CssStubElement.java:40)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$fetchExternalDocumentation$1.invoke(TranslatingDocumentationProvider.kt:73)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$fetchExternalDocumentation$1.invoke(TranslatingDocumentationProvider.kt:24)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.nullIfRecursive(TranslatingDocumentationProvider.kt:98)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.access$nullIfRecursive(TranslatingDocumentationProvider.kt:88)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider.fetchExternalDocumentation(TranslatingDocumentationProvider.kt:59)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.fetchExternalDocumentation(CompositeDocumentationProvider.java:231)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.getDocumentation(DocumentationManager.java:1565)
	at com.intellij.codeInsight.documentation.DocumentationManager.lambda$doFetchDocInfo$20(DocumentationManager.java:1080)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

_Originally posted by @toutoumu in https://github.com/YiiGuxing/TranslationPlugin/issues/721#issuecomment-818521944_

**Comment by YiiGuxing** [comment]
@toutoumu 请问如何才能复现这个问题？
