### ISSUE TITLE
翻译失败: 未知错误

### ISSUE THREAD

**Issue by Hassanwh** [YiiGuxing/TranslationPlugin#727]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
请详细描述问题，确保包括:
  1. 输入多行需要翻译的内容。
  2. 翻译失败: 未知错误。
  3. 如果可以，请添加屏幕截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/30260645/114522777-40131b00-9c76-11eb-963e-aa7a2d144955.png)

### 环境 & 错误日志
- 插件版本: v3.0.3  
- IDE版本:  IDEA 2020.2.3  
- 操作系统版本: Windows 10 
- 错误日志:
```
翻译失败: 未知错误

>Plugin v3.0.3  
>IntelliJ IDEA 2020.2.3  
>内部版本号 #IU-202.7660.26, 构建于 October 6, 2020  
>运行时版本: 11.0.8+10-b944.34 amd64  
>JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0
cn.yiiguxing.plugin.translate.trans.TranslateException: Google翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:122)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.google.cn/translate_a/single?sl=auto&tl=zh-CN&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dj=1&ie=UTF-8&oe=UTF-8&hl=zh-CN&tk=14303.453671
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:385)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:439)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:105)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:85)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:57)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:83)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:95)
	... 12 more
```

**Comment by YiiGuxing** [comment]
翻译过于频繁了，稍微再重试

**Comment by RunningShadow-007** [comment]
遇到了同样的问题  并没有经常翻译

**Comment by YiiGuxing** [comment]
> 遇到了同样的问题 并没有经常翻译

如果你开启了文档自动翻译的话，会经常触发翻译的。
