### ISSUE TITLE
翻译失败: 帐号无效 - 检查配置

### ISSUE THREAD

**Issue by RunningShadow-007** [YiiGuxing/TranslationPlugin#740]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

  1. 配置完百度应用程序id和秘钥后
  2. 翻译  提示   翻译失败: 帐号无效 - 检查配置
![image](https://user-images.githubusercontent.com/10829703/116180963-5c21bc80-a74c-11eb-8c51-2d8ff0d90c6b.png)

### 环境 & 错误日志
- 插件版本: 3.1-201
- IDE版本: androidstudio 4.1.2
- 操作系统版本: macos

**Comment by RunningShadow-007** [comment]
有道翻译  配置了账号和秘钥 后也是同样问题
>Plugin v3.1-201  
>Android Studio 4.1.2  
>Build #AI-201.8743.12.41.7042882, built on December 20, 2020  
>Runtime version: 1.8.0_242-release-1644-b3-6915495 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.16

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 有道翻译 :: 翻译失败: 未知错误[205]
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: 有道翻译 :: Translate failed: 205
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:107)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:91)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 8 more
```

**Comment by YiiGuxing** [comment]
新申请的账号可能需要等一段时间后才生效，你先过一会儿再试
