### ISSUE TITLE
Rider翻译的时候报错

### ISSUE THREAD

**Issue by xxxxue** [YiiGuxing/TranslationPlugin#743]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

移到main上面,弹出的依然是英文.但是上面的翻译开关是打开的.
然后点击两下. 切换下开关状态.  他就翻译成功了,
 (此时就出现了下面的截图, 每次都会出现,点开后,单击"全部清除"按钮,在重复最开始的操作.就又出来了)
 但是鼠标移走. 再移回来main 上.  还是英文.

![image](https://user-images.githubusercontent.com/32764266/116550602-90060900-a929-11eb-9000-8376c378dc65.png)

### 环境 & 错误日志
- 插件版本:  3.1 
- IDE版本:  Rider 2021.1.2
- 操作系统版本: win10

- 错误日志:
```
java.lang.IllegalStateException: originalText must not be null
	at cn.yiiguxing.plugin.translate.action.ToggleQuickDocTranslationAction$toggleTranslation$replaceComponentAction$1.run(ToggleQuickDocTranslationAction.kt:67)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:521)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:468)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:119)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:79)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:486)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by niktrop** [comment]
I could not reproduce the exception, but C# documentation should honor "Translate documentation" toggle state once #749 is merged.

**Comment by YiiGuxing** [comment]
已禁用鼠标悬停文档的翻译：https://github.com/YiiGuxing/TranslationPlugin/commit/fc8689ffca3608d6f9592aad67cf93ba35768674
