### ISSUE TITLE
big sur 11.3 idea 2021 插件3.1 老是提示有错误

### ISSUE THREAD

**Issue by duxingxingxing** [YiiGuxing/TranslationPlugin#745]
Details: Current thread: Thread[Alarm Pool,4,Idea Thread Group] 48321091
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,Idea Thread Group] 176003207

java.lang.Throwable: Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:992)
	at com.intellij.psi.impl.source.PsiFileImpl.assertReadAccessAllowed(PsiFileImpl.java:179)
	at com.intellij.psi.impl.source.PsiFileImpl.getStubTree(PsiFileImpl.java:616)
	at com.intellij.psi.impl.source.SpineRef.getStub(SpineRef.java:32)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getStub(StubBasedPsiElementBase.java:340)
	at com.intellij.extapi.psi.StubBasedPsiElementBase.getContext(StubBasedPsiElementBase.java:286)
	at com.intellij.psi.util.PsiTreeUtil.getContextOfType(PsiTreeUtil.java:615)
	at com.intellij.psi.util.PsiTreeUtil.getContextOfType(PsiTreeUtil.java:601)
	at com.intellij.psi.css.CssElement.getLanguageOf(CssElement.java:38)
	at com.intellij.psi.css.impl.stubs.base.CssStubElement.getLanguage(CssStubElement.java:40)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$fetchExternalDocumentation$1.invoke(TranslatingDocumentationProvider.kt:73)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$fetchExternalDocumentation$1.invoke(TranslatingDocumentationProvider.kt:24)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.nullIfRecursive(TranslatingDocumentationProvider.kt:98)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion.access$nullIfRecursive(TranslatingDocumentationProvider.kt:88)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider.fetchExternalDocumentation(TranslatingDocumentationProvider.kt:59)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.fetchExternalDocumentation(CompositeDocumentationProvider.java:231)
	at com.intellij.codeInsight.documentation.DocumentationManager$MyCollector.getDocumentation(DocumentationManager.java:1565)
	at com.intellij.codeInsight.documentation.DocumentationManager.getDocumentationAndProvider(DocumentationManager.java:975)
	at com.intellij.openapi.editor.EditorMouseHoverPopupManager$Context.calcInfo(EditorMouseHoverPopupManager.java:546)
	at com.intellij.openapi.editor.EditorMouseHoverPopupManager.lambda$scheduleProcessing$7(EditorMouseHoverPopupManager.java:208)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.editor.EditorMouseHoverPopupManager.lambda$scheduleProcessing$8(EditorMouseHoverPopupManager.java:207)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:369)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
环境 & 错误日志
插件版本: 3.1
IDE版本: idea 2021.1
操作系统版本: big sur 11.3 M1芯片

**Comment by flipped-cj** [comment]
我的报错日志也是这样的，重装好几次插件都不行。"此插件不是JetBrains的产品。请将问题报告给Yili.Guxing."

**Comment by flipped-cj** [comment]
@YiiGuxing 
在jetbrains插件里安装和GitHub下载安装的都有报错，webstorm2021.1，禁用过汉化插件不是汉化的问题，和新版jetbrains不兼容吗，我之前使用的2020版本没问题
[![gum2mF.png](https://z3.ax1x.com/2021/05/04/gum2mF.png)](https://imgtu.com/i/gum2mF)

**Comment by YiiGuxing** [comment]
重复： #725
