### ISSUE TITLE
最新版idea 中 启用插件 启动报错

### ISSUE THREAD

**Issue by heheshang** [YiiGuxing/TranslationPlugin#751]
Following exceptions happened soon after this one, most probably they are induced.

2021-05-06T09:05:06.026
com.intellij.diagnostic.PluginException:  [Plugin: cn.yiiguxing.plugin.translate]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:250)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:220)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:551)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:539)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:393)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:352)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:331)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$3(ActionUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:147)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$4(ActionUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$23(ActionUpdater.java:322)
	at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$getGroupChildren$25(ActionUpdater.java:321)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.getGroupChildren(ActionUpdater.java:320)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.iterateGroupChildren(ActionUpdater.java:469)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandGroupChild(ActionUpdater.java:343)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$20(ActionUpdater.java:308)
	at com.intellij.util.TimeoutUtil.compute(TimeoutUtil.java:134)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$doExpandActionGroup$22(ActionUpdater.java:307)
	at com.intellij.util.containers.ContainerUtil.concat(ContainerUtil.java:1511)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.doExpandActionGroup(ActionUpdater.java:307)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:199)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroup(ActionUpdater.java:173)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$expandActionGroupWithTimeout$11(ActionUpdater.java:215)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.withTimeout(ProgressIndicatorUtils.java:310)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:215)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.expandActionGroupWithTimeout(ActionUpdater.java:207)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1118)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:175)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:151)
	at com.intellij.ide.IdeEventQueue.onFocusEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:240)
	... 47 more
Caused by: java.lang.NoSuchMethodError: 'java.util.Locale com.intellij.DynamicBundle.getLocale()'
	at cn.yiiguxing.plugin.translate.TranslationBundle$adaptedBundle$2.invoke(TranslationBundle.kt:15)
	at cn.yiiguxing.plugin.translate.TranslationBundle$adaptedBundle$2.invoke(TranslationBundle.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at cn.yiiguxing.plugin.translate.TranslationBundle.getAdaptedBundle(TranslationBundle.kt)
	at cn.yiiguxing.plugin.translate.TranslationBundle.getAdaptedMessage(TranslationBundle.kt:41)
	at cn.yiiguxing.plugin.translate.TranslationBundleKt.adaptedMessage(TranslationBundle.kt:51)
	at cn.yiiguxing.plugin.translate.action.ShowTranslationDialogAction.<init>(ShowTranslationDialogAction.kt:18)
	... 52 more

**Comment by heheshang** [comment]
使用的是发行版本 v3.1

**Comment by impqr** [comment]
问题同上。

插件版本：v3.1
IDEA版本：2021.1.1
JDK版本：GraalVM 21.0.0.2 （OpenJDK 11）
OS版本：Ubuntu 20

**Comment by mritd** [comment]
mac 10.15.7
IDEA 2021.1.1

同样问题，该问题似乎还会导致 IDEA 的设置无法打开

**Comment by karanokyoukai** [comment]
同上，更新至3.1后无法正常启动IDEA，侧边文件栏与IDEA设置均无法打开。
插件版本：v3.1
OS：windows 10 20H2
IDEA版本：2020.3.2

**Comment by wangjifeng0205** [comment]
问题同上，使用的是ORACLE JDK8, 插件使用的是3.1版本，插件会导致idea左侧工程栏无法打开，设置按钮操作无效，禁用插件恢复正常。

**Comment by Second-dimension** [comment]
问题同上，idea今天更新后，设置和左侧工程栏无法打开，会触发idea错误，禁用后正常

插件版本：v3.1
IDEA版本：2021.1.1
OS版本：Windows 10 10.0
IntelliJ IDEA 2021.1.1 (Ultimate Edition)
内部版本号 #IU-211.7142.45，April 30, 2021 构建
运行时版本: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM，JetBrains s.r.o.
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8

**Comment by MrArKi** [comment]
问题同上，禁用正常
插件版本：3.1
OS：windows 10 18363工作站版
IDEA：2021.1.1

**Comment by Hyperion-v** [comment]
同样的问题，且导致 IDEA 的设置无法打开

**Comment by Jacks5320** [comment]
貌似是与新版 kotlin 插件冲突，卸载新版 kotlin 插件回退版本后就可以用了。

**Comment by ningyudie** [comment]
+1

**Comment by bestrow** [comment]
mac 11.0.1
idea 2020.3.3 (Ultimate Edition)
JDK8

**Comment by bestrow** [comment]
同样问题
mac 11.0.1
idea 2020.3.3 (Ultimate Edition)
JDK8

**Comment by xgblack** [comment]
同样的问题，回退kotlin插件版本也没用，问题依然存在

**Comment by hhhyde** [comment]
我直接吧kotlin 禁用了

**Comment by bestrow** [comment]
> 同样问题
> mac 11.0.1
> idea 2020.3.3 (Ultimate Edition)
> JDK8

退回到Translation3.0.3版本解决了

**Comment by HarveyZh0218** [comment]
更新kotlin1.5 导致的

**Comment by cycle2zhou** [comment]
@HarveyZh0218  +1

**Comment by O-kai** [comment]
> 貌似是与新版 kotlin 插件冲突，卸载新版 kotlin 插件回退版本后就可以用了。

我尝试把kotlin关闭，确实没有再报错了！

**Comment by heheshang** [comment]
我禁用了 kotlin 不在报错了

**Comment by mritd** [comment]
彻底删除 kotlin 插件后没问题了。
