### ISSUE TITLE
最新版 IntelliJ IDEA 2021.1.1 Build #IU-211.7142.45, built on April 30, 2021  报错了

### ISSUE THREAD

**Issue by HongJian-Yang** [YiiGuxing/TranslationPlugin#755]
翻译插件 和 IntelliJ IDEA 2021.1.1 (Ultimate Edition) Build #IU-211.7142.45, built on April 30, 2021 这个版本的IDEA不兼容，会报错

`com.intellij.diagnostic.PluginException:  [Plugin: cn.yiiguxing.plugin.translate]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:250)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:220)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:551)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1601)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:14)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:240)
	... 23 more
Caused by: java.lang.NoSuchMethodError: 'java.util.Locale com.intellij.DynamicBundle.getLocale()'
	at cn.yiiguxing.plugin.translate.TranslationBundle$adaptedBundle$2.invoke(TranslationBundle.kt:15)
	at cn.yiiguxing.plugin.translate.TranslationBundle$adaptedBundle$2.invoke(TranslationBundle.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at cn.yiiguxing.plugin.translate.TranslationBundle.getAdaptedBundle(TranslationBundle.kt)
	at cn.yiiguxing.plugin.translate.TranslationBundle.getAdaptedMessage(TranslationBundle.kt:41)
	at cn.yiiguxing.plugin.translate.TranslationBundleKt.adaptedMessage(TranslationBundle.kt:51)
	at cn.yiiguxing.plugin.translate.action.TranslateQuickDocSelectionAction.<init>(TranslateQuickDocSelectionAction.kt:20)
	... 28 more
````

**Comment by YiiGuxing** [comment]
merged: #747
