### ISSUE TITLE
问一下谷歌翻译限制频率大概多少？

### ISSUE THREAD

**Issue by AnsuzTrent** [YiiGuxing/TranslationPlugin#758]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
手打英文翻译了个长句子之后再翻译会报“翻译失败: 请求过多，请稍候再试”，所以想问一下谷歌翻译的频率限制

### 环境 & 错误日志
精简一下就是

`Google 翻译 :: 翻译失败: 请求过多，请稍候再试`
` Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.google.cn`

完整的是

翻译失败: 请求过多，请稍候再试

        >Plugin v3.1.1
        >IntelliJ IDEA 2021.1.1
        >内部版本号 #IU-211.7142.45，April 30, 2021 构建
        >运行时版本: 11.0.10+9-b1341.41 amd64
        >VM: Dynamic Code Evolution 64-Bit Server VM，JetBrains s.r.o.
        >OS: Windows 10 10.0

        ```
        cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 请求过多，请稍候再试
        at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
        at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
        at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
        at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.google.cn/translate_a/single?sl=auto&tl=zh-CN&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dj=1&ie=UTF-8&oe=UTF-8&hl=zh-CN&tk=935403.564182
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
        at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:429)
        at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
        at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
        at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:531)
        at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
        at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
        at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
        at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
        ... 12 more
        ```
```

**Comment by YiiGuxing** [comment]
这个倒不清楚，有时间我测一下吧。

**Comment by CcYZzz** [comment]
![image](https://user-images.githubusercontent.com/47567074/122328613-934d6680-cf62-11eb-84c0-cc6003e716f9.png)
![image](https://user-images.githubusercontent.com/47567074/122328707-aeb87180-cf62-11eb-9733-b78366311f3b.png)

不管翻译什么都提示: 翻译失败: 请求过多，请稍候再试


具体信息:
`
翻译失败: 请求过多，请稍候再试

>Plugin v3.1.1  
>IntelliJ IDEA 2020.3.4  
>Build #IU-203.8084.24, built on April 27, 2021  
>Runtime version: 11.0.10+8-b1145.96 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 请求过多，请稍候再试
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.google.cn/translate_a/single?sl=auto&tl=en&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dj=1&ie=UTF-8&oe=UTF-8&hl=zh-CN&tk=507261.89974
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:391)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:461)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 12 more
```
`

**Comment by YiiGuxing** [comment]
由于谷歌翻译API使用的是公共API，所以对端终的访问频率的限制并不会有有效的改善。所以，如果遇到该异常，目前还没有有效的解决办法，这时可以先暂时使用其他的翻译引擎。
