### ISSUE TITLE
翻译失败

### ISSUE THREAD

**Issue by Piean** [YiiGuxing/TranslationPlugin#771]
### 问题描述
有时候会翻译失败，插件报：未知错误
之后使用翻译失败的词语，就一直翻译失败
换其它词可以翻译成功

### 环境 & 错误日志
- 插件版本: v3.1.1
- IDE版本: IntelliJ IDEA 2021.1.2
- 操作系统版本: Windows 10
- 错误日志:
翻译失败: 未知错误

>Plugin v3.1.1  
>IntelliJ IDEA 2021.1.2  
>Build #IU-211.7442.40, built on June 1, 2021  
>Runtime version: 11.0.11+9-b1341.57 amd64  
>VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 有道翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.LinkageError: loader constraint violation: loader com.intellij.ide.plugins.cl.PluginClassLoader @3de06fd8 wants to load interface kotlin.text.MatchResult. A different interface with the same name was previously loaded by com.intellij.util.lang.PathClassLoader @49dc7102. (kotlin.text.MatchResult is in unnamed module of loader com.intellij.util.lang.PathClassLoader @49dc7102, parent loader 'platform')
	at cn.yiiguxing.plugin.translate.trans.text.YoudaoDictDocument$Factory.blocks(YoudaoDictDocument.kt:294)
	at cn.yiiguxing.plugin.translate.trans.text.YoudaoDictDocument$Factory.getDocument(YoudaoDictDocument.kt:144)
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslation.toTranslation(YoudaoTranslation.kt:63)
	at cn.yiiguxing.plugin.translate.trans.YoudaoTranslator.parserResult(YoudaoTranslator.kt:109)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:91)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:531)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 12 more
```

**Comment by YiiGuxing** [comment]
请问是翻译什么内容导致的？

**Comment by Piean** [comment]
@YiiGuxing 这个不是固定的，我暂时也没有发下规律
比如翻译“指标”就会报错
![image](https://user-images.githubusercontent.com/11806405/120633721-09e76000-c49d-11eb-8cc6-900e97daa207.png)
加个其它字就可以，比如：“新指标”
![image](https://user-images.githubusercontent.com/11806405/120633807-26839800-c49d-11eb-9bef-cd19044b8e5f.png)
翻译：saleroom 也报错
![image](https://user-images.githubusercontent.com/11806405/120633869-38fdd180-c49d-11eb-85d2-995bb83f8305.png)

**Comment by YiiGuxing** [comment]
可以到插件的设置页把本地缓存清除了试试

**Comment by Piean** [comment]
好的，我清除缓存再试试。
另外设置里的“最大历史记录长度”修改无效，会自动变回50

**Comment by YiiGuxing** [comment]
![Dingtalk_20210604092832](https://user-images.githubusercontent.com/10737066/120732768-6f2c6700-c518-11eb-9013-c796da32b341.jpg)

主要是我这边无法复现。。。。这个应该是接口当时返回了异常的内容，解析的时候出错了，这个内容又被插件缓存到了本地，所以你后续的翻译也报异常了。
可以到插件的设置页把本地缓存清除了再试试：
![Dingtalk_20210604094208](https://user-images.githubusercontent.com/10737066/120733148-27f2a600-c519-11eb-9ab6-7752a9e7a676.jpg)

**Comment by YiiGuxing** [comment]
![Dingtalk_20210604092832](https://user-images.githubusercontent.com/10737066/120732768-6f2c6700-c518-11eb-9013-c796da32b341.jpg)

主要是我这边无法复现。。。。这个应该是接口当时返回了异常的内容，解析的时候出错了，这个内容又被插件缓存到了本地，所以你后续的翻译也报异常了。
可以到插件的设置页把本地缓存清除了再试试：
![Dingtalk_20210604094208](https://user-images.githubusercontent.com/10737066/120733148-27f2a600-c519-11eb-9ab6-7752a9e7a676.jpg)

**Comment by Piean** [comment]
是用着用着突然就有词语翻译失败，错误日志都是一样的，我重启之后之前失败的词也能成功，总之就是不确定什么词会失败，什么时候会失败，确实难搞。
另外我初步怀疑有可能和我禁用了Kotlin插件有关系，我先启用然后再使用一段时间看看，谢谢

**Comment by YiiGuxing** [comment]
> 是用着用着突然就有词语翻译失败，错误日志都是一样的，我重启之后之前失败的词也能成功，总之就是不确定什么词会失败，什么时候会失败，确实难搞。
> 另外我初步怀疑有可能和我禁用了Kotlin插件有关系，我先启用然后再使用一段时间看看，谢谢

可能真的是这个问题哦，错误信息说有两相同的接口被尝试加载，所以抛了异常。。。

**Comment by tonels** [comment]
我这里也遇到了翻译异常

翻译失败: 未知错误

>Plugin v3.1.1  
>IntelliJ IDEA 2020.3.3  
>Build #IU-203.7717.56, built on March 15, 2021  
>Runtime version: 11.0.10+8-b1145.96 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:391)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:461)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 12 more
```

**Comment by tonels** [comment]
> 我这里也遇到了翻译异常
> 
> 翻译失败: 未知错误
> 
> > Plugin v3.1.1
> > IntelliJ IDEA 2020.3.3
> > Build #IU-203.7717.56, built on March 15, 2021
> > Runtime version: 11.0.10+8-b1145.96 amd64
> > VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> > OS: Windows 10 10.0
> 
> ```
> cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
> 	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
> 	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
> 	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
> 	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:391)
> 	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:461)
> 	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:104)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
> 	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
> 	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
> 	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
> 	... 12 more
> ```

第二天早上又好了，可能是当天谷歌翻译允许请求数超了，不给用了
