### ISSUE TITLE
idea运行时插件有报错

### ISSUE THREAD

**Issue by ljynfo** [YiiGuxing/TranslationPlugin#778]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by YiiGuxing** [comment]
麻烦提供一下异常信息，谢谢！

**Comment by ljynfo** [comment]
java.sql.SQLException: [SQLITE_NOTADB]  File opened that is not a database file (file is not a database) Query: CREATE TABLE IF NOT EXISTS wordbook (
    "_id"            INTEGER  PRIMARY KEY,
    word            TEXT     COLLATE NOCASE NOT NULL,
    source_language TEXT                    NOT NULL,
    target_language TEXT                    NOT NULL,
    phonetic        TEXT,
    explanation     TEXT,
    tags            TEXT,
    created_at      DATETIME                NOT NULL
) Parameters: []
	at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:527)
	at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:531)
	at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:461)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.initTable(WordBookService.kt:173)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.initialize(WordBookService.kt:64)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.<init>(WordBookService.kt:53)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:488)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService$Companion.getInstance(WordBookService.kt:416)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookToolWindowFactory.init$lambda-3(WordBookToolWindowFactory.kt:53)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ljynfo** [comment]
> java.sql.SQLException: [SQLITE_NOTADB] File opened that is not a database file (file is not a database) Query: CREATE TABLE IF NOT EXISTS wordbook (
> "_id" INTEGER PRIMARY KEY,
> word TEXT COLLATE NOCASE NOT NULL,
> source_language TEXT NOT NULL,
> target_language TEXT NOT NULL,
> phonetic TEXT,
> explanation TEXT,
> tags TEXT,
> created_at DATETIME NOT NULL
> ) Parameters: []
> at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:527)
> at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:531)
> at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:461)
> at cn.yiiguxing.plugin.translate.wordbook.WordBookService.initTable(WordBookService.kt:173)
> at cn.yiiguxing.plugin.translate.wordbook.WordBookService.initialize(WordBookService.kt:64)
> at cn.yiiguxing.plugin.translate.wordbook.WordBookService.(WordBookService.kt:53)
> at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
> at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
> at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
> at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
> at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:37)
> at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
> at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
> at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:488)
> at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
> at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
> at cn.yiiguxing.plugin.translate.wordbook.WordBookService$Companion.getInstance(WordBookService.kt:416)
> at cn.yiiguxing.plugin.translate.wordbook.WordBookToolWindowFactory.init$lambda-3(WordBookToolWindowFactory.kt:53)
> at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
> at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
> at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)
> at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> at java.base/java.security.AccessController.doPrivileged(Native Method)
> at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> at java.base/java.lang.Thread.run(Thread.java:829)


IntelliJ IDEA 2021.1.2 (Ultimate Edition)
内部版本号 #IU-211.7442.40，June 1, 2021 构建
插件版本：3.1.1

idea启动后提示有错误日志

**Comment by YiiGuxing** [comment]
你的系统是什么系统？
到用户目录下删除`.translation`目录后再试试还报错不。

**Comment by ljynfo** [comment]
> 你的系统是什么系统？
> 到用户目录下删除`.translation`目录后再试试还报错不。

W10，删除.translation目录之后正常了，感谢
