### ISSUE TITLE
翻译引擎重启失效

### ISSUE THREAD

**Issue by SLiGe** [YiiGuxing/TranslationPlugin#799]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

  配置翻译引擎为有道，并填好应用id和密钥，使用没问题。重启IDEA后会自动重置为谷歌翻译，选择有道后，还需要填写应用程序ID，密钥有记录不需要填写
![image](https://user-images.githubusercontent.com/44280242/127945888-3afad302-6516-40fa-b8a4-4b526d1af4e8.png)

### 环境 & 错误日志
- 插件版本: 3.1-201
- IDE版本: IDEA 2021.2(Ultimate Edition)
- 操作系统版本: Windows 10

- 错误日志:
```
com.intellij.diagnostic.PluginException: Cyclic service initialization: ServiceAdapter(descriptor=ServiceDescriptor(interface='null', serviceImplementation='cn.yiiguxing.plugin.translate.Settings', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=Translation, id=cn.yiiguxing.plugin.translate, descriptorPath=plugin.xml, path=E:\DevTool\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.4746.92.plugins\TranslationPlugin, version=3.1-201, package=null))
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:92)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:590)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:19)
	at cn.yiiguxing.plugin.translate.Settings$Companion.getInstance(Settings.kt:167)
	at cn.yiiguxing.plugin.translate.ui.settings.TranslationEngine.isConfigured(TranslationEngine.kt:95)
	at cn.yiiguxing.plugin.translate.action.TranslatorAction.isAvailable(TranslatorAction.kt:16)
	at cn.yiiguxing.plugin.translate.action.TranslatorAction$Companion.availableActions(TranslatorAction.kt:25)
	at cn.yiiguxing.plugin.translate.ui.TranslatorWidgetFactory.isAvailable(TranslatorWidgetFactory.kt:37)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.updateWidget(StatusBarWidgetsManager.java:89)
	at cn.yiiguxing.plugin.translate.ui.TranslatorWidgetFactory$updateWidgetsInAllProjects$$inlined$readAction$1.invoke(KotlinPositionManager.kt:344)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt$sam$com_intellij_openapi_util_Computable$0.compute(ApplicationUtils.kt)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:841)
	at org.jetbrains.kotlin.idea.util.application.ApplicationUtilsKt.runReadAction(ApplicationUtils.kt:14)
	at cn.yiiguxing.plugin.translate.ui.TranslatorWidgetFactory.updateWidgetsInAllProjects(TranslatorWidgetFactory.kt:74)
	at cn.yiiguxing.plugin.translate.ui.TranslatorWidgetFactory.access$updateWidgetsInAllProjects(TranslatorWidgetFactory.kt:19)
	at cn.yiiguxing.plugin.translate.ui.TranslatorWidgetFactory$subscribeToSettingsChange$1.onTranslatorChanged(TranslatorWidgetFactory.kt:57)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:624)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy88.onTranslatorChanged(Unknown Source)
	at cn.yiiguxing.plugin.translate.Settings$$special$$inlined$observable$1.afterChange(Delegates.kt:72)
	at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:41)
	at cn.yiiguxing.plugin.translate.Settings.setTranslator(Settings.kt)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.serialization.PropertyAccessor.set(PropertyAccessor.java:97)
	at com.intellij.util.xmlb.XmlSerializerImpl.doSet(XmlSerializerImpl.java:221)
	at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:120)
	at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:55)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:246)
	at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:200)
	at com.intellij.util.xmlb.BeanBinding.deserialize(BeanBinding.java:143)
	at com.intellij.configurationStore.JdomSerializerImpl.deserialize(xmlSerializer.kt:91)
	at com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:29)
	at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:35)
	at com.intellij.configurationStore.StateGetterImpl.getState(StorageBaseEx.kt:57)
	at com.intellij.configurationStore.ComponentStoreImpl.doInitComponent(ComponentStoreImpl.kt:423)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:373)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:124)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:525)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:36)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:590)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:19)
	at cn.yiiguxing.plugin.translate.Settings$Companion.getInstance(Settings.kt:167)
	at cn.yiiguxing.plugin.translate.ui.settings.TranslationEngine.isConfigured(TranslationEngine.kt:95)
	at cn.yiiguxing.plugin.translate.action.TranslatorAction.isAvailable(TranslatorAction.kt:16)
	at cn.yiiguxing.plugin.translate.action.TranslatorAction$Companion.availableActions(TranslatorAction.kt:25)
	at cn.yiiguxing.plugin.translate.ui.TranslatorWidgetFactory.isAvailable(TranslatorWidgetFactory.kt:37)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.updateWidget(StatusBarWidgetsManager.java:89)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetsManager.updateAllWidgets(StatusBarWidgetsManager.java:63)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.installDefaultProjectStatusBarWidgets(ProjectFrameHelper.java:397)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper.setProject(ProjectFrameHelper.java:383)
	at com.intellij.openapi.wm.impl.WindowManagerImpl.assignFrame(WindowManagerImpl.kt:281)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$projectLoaded$1.run(ProjectFrameAllocator.kt:171)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:755)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:487)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by YiiGuxing** [comment]
这是一个bug，不过已经修复了的，请升级插件到最新版本。

**Comment by SLiGe** [comment]
升级到最新版本可以了，好吧，idea没提醒我更新，我也没到官网看最新版本 :sweat_smile:
