### ISSUE TITLE
谷歌翻译引擎 翻译次数到达上限

### ISSUE THREAD

**Issue by yangwudong** [YiiGuxing/TranslationPlugin#814]
* [ X ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ X ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
通过翻译插件进行文件内容翻译，翻译大约20-30次左右后就无法在进行更多翻译了。会报下面的错误。

### 问题描述
根据内容看，应该是到了Google的限制上限，换了IP也不管用。应该是限制了mac地址或者app key什么的？但是看源码，google的配置是没有app key的。不知道有什么办法可以通过配置自有的app key和secret来绕开这个问题。
![image](https://user-images.githubusercontent.com/987610/131944468-13a3890a-dfd9-49ec-9ee0-7a6a30586ce7.png)

### 环境 & 错误日志
- 插件版本: 3.1.1
- IDE版本: IDEA 2021.2
- 操作系统版本: macOS 11.5.2

- 错误日志:
```
Translation failed: Too many requests, please try again later  
>Plugin v3.1.1   >IntelliJ IDEA 2021.2   >Build #IU-212.4746.92, built on July 27, 2021   
>Runtime version: 11.0.11+9-b1504.13 x86_64   >VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.   
>OS: macOS 11.5.2  ``` cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: Translation failed: Too many requests, please try again later 	
at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129) 	
at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184) 	
at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265) 	
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) 	
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668) 	
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665) 	
at java.base/java.security.AccessController.doPrivileged(Native Method) 	
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665) 	
at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.googleapis.com/translate_a/single?sl=auto&tl=en&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dj=1&ie=UTF-8&oe=UTF-8&hl=vi&tk=833493.679567 	
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924) 	
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) 	
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) 	
at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365) 	
at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415) 	
at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102) 	
at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90) 	
at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517) 	
at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499) 	
at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332) 	
at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88) 	

at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100) 	
... 11 more ```
```

**Comment by YiiGuxing** [comment]
应该是翻译过于频繁了，这个要第二天才可以再次使用，先暂时用其他翻译引擎的吧。

**Comment by yangwudong** [comment]
> 应该是翻译过于频繁了，这个要第二天才可以再次使用，先暂时用其他翻译引擎的吧。

我需要翻译一些特殊语种，比如越南语。但是，用百度和有道都无法正确翻译，
有道选择越南语，结果翻译出来的是中文的。设置如下：
![image](https://user-images.githubusercontent.com/987610/131955006-ae1a3375-bae4-4e60-98cf-1570c3c10823.png)
翻译的结果：
![image](https://user-images.githubusercontent.com/987610/131955017-4b75ed03-8cf8-4829-b4d2-b75b43572f30.png)
百度的是账号配置过，但是报错：
`
Translation failed: Invalid account - <a href="#TRANSLATOR_CONFIGURATION">Check configuration</a>

>Plugin v3.1.1  
>IntelliJ IDEA 2021.2  
>Build #IU-212.4746.92, built on July 27, 2021  
>Runtime version: 11.0.11+9-b1504.13 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: macOS 11.5.2

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Baidu Translate :: Translation failed: Invalid account - <a href="#TRANSLATOR_CONFIGURATION">Check configuration</a>
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: Baidu Translate :: Translate failed: 52003
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:120)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:91)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 11 more
```
`

**Comment by yangwudong** [comment]
> 应该是翻译过于频繁了，这个要第二天才可以再次使用，先暂时用其他翻译引擎的吧。

另外，多问一下，有没有什么办法，给google的，配置个人独立的翻译配额？Google的限制是根据你申请的app还是根据IP或者mac地址的啊？

**Comment by YiiGuxing** [comment]
> > 应该是翻译过于频繁了，这个要第二天才可以再次使用，先暂时用其他翻译引擎的吧。
> 
> 我需要翻译一些特殊语种，比如越南语。但是，用有道无法正确翻译，
> 有道选择越南语，结果翻译出来的是中文的。设置如下：
> ![image](https://user-images.githubusercontent.com/987610/131955006-ae1a3375-bae4-4e60-98cf-1570c3c10823.png)
> 翻译的结果：
> ![image](https://user-images.githubusercontent.com/987610/131955017-4b75ed03-8cf8-4829-b4d2-b75b43572f30.png)
> 
> 百度的是对的，是我账号开通服务的问题。

这里的处理逻辑有点问题，下个版本我优化一下。

**Comment by YiiGuxing** [comment]
> > 应该是翻译过于频繁了，这个要第二天才可以再次使用，先暂时用其他翻译引擎的吧。
> 
> 另外，多问一下，有没有什么办法，给google的，配置个人独立的翻译配额？Google的限制是根据你申请的app还是根据IP或者mac地址的啊？

现在使用的是公共配额，翻译频率不能太高，不然会被限制一天。google翻译是有公共配额的，但是在国内使用门坎比较高的，需要有VISA信用卡才行，我没有，所以到现在我也没有开发相应的功能，因为没有办法调试。

**Comment by YiiGuxing** [comment]
关于翻译次数到达上限问题，目前没有有效的优化办法。谷歌翻译使用的是公共的版本，有翻译频率的限制，翻译频率过高会被限制使用，被限制使用之后需要过24小时后才能再次使用。有高频率翻译需求的，请考虑使用百度、有道等其他翻译引擎，它们没有这方面的限制。
