### ISSUE TITLE
翻译失败的另一可能性

### ISSUE THREAD

**Issue by mysmlz** [YiiGuxing/TranslationPlugin#817]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ] (https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。
* [x] 找到了相似问题

## 问题详情

**已按[issue#771](./771)清理了缓存**

翻译失败,可能是,调用百度等接口的`from`参数问题(自动检测语言机制)
按报错信息来看,可能因自动检测设置了`from=auto`,返回内容中包含了`"from":"gle"`,但未在[Languages.kt](https://github.com/YiiGuxing/TranslationPlugin/blob/master/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/Languages.kt)发现`爱尔兰语`

### 问题描述

1. 在翻译这个`backported`这个词时,出现了报错,
![image](https://user-images.githubusercontent.com/38951157/132153866-1471eac8-abc4-4a94-bb46-7e0f3f955362.png)
2. 经测试,在百度翻译首页,翻译时,出现了`你是不是要找`提示,并且检测到`爱尔兰语`
![image](https://user-images.githubusercontent.com/38951157/132156357-2808ddb6-4c7e-47c1-b9dc-28e16586ddf6.png)
3. 使用`from=auto`调用api时,返回结果中包含了`"from":"gle"`
![image](https://user-images.githubusercontent.com/38951157/132156901-44d2c5d2-b5e7-4c7e-a967-ca71ca81fe42.png)
4. 在设置`from=en`调用api时,返回结果中包含的是`"from":"en"`.
![image](https://user-images.githubusercontent.com/38951157/132153792-acfcf814-263f-4a52-a403-9ba4f5667476.png)

### 环境 & 错误日志

翻译失败: 未知错误

>Plugin v3.1.1  
>IntelliJ IDEA 2021.2.1  
>内部版本号 #IU-212.5080.55，August 24, 2021 构建  
>运行时版本: 11.0.11+9-b1504.16 amd64  
>VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 百度翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Unknown language code:gle
	at cn.yiiguxing.plugin.translate.trans.Lang$Companion.valueOfBaiduCode(Languages.kt:389)
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslation.toTranslation(BaiduTranslation.kt:25)
	at cn.yiiguxing.plugin.translate.trans.BaiduTranslator.parserResult(BaiduTranslator.kt:122)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:91)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 11 more
```

**Comment by mysmlz** [comment]
![image](https://user-images.githubusercontent.com/38951157/132157186-547b1f93-ef14-4333-a307-4bd2dbb81842.png)

**建议再增加部分语言常量或修改下逻辑**
