### ISSUE TITLE
大量使用后 出现了翻译失败: 未知错误 

### ISSUE THREAD

**Issue by GyyEcho** [YiiGuxing/TranslationPlugin#821]
翻译失败: 未知错误

>Plugin v3.1.1  
>IntelliJ IDEA 2021.2  
>Build #IU-212.4746.92, built on July 27, 2021  
>Runtime version: 11.0.11+9-b1504.13 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 11 more
```

**Comment by yorhasaber** [comment]
我也是出现翻译失败: 未知错误

**Comment by gitzwt** [comment]
今天出现的,相同的情况

**Comment by LJJ802311** [comment]
同上 翻译失败:未知错误

**Comment by AtomRun** [comment]
我也一样

**Comment by Amanda827** [comment]
俺也一样

**Comment by zw-git** [comment]
翻译无效问题，需要在设置里面把"翻译引擎"后面的√打上(使用translate.google.com)

**Comment by AtomRun** [comment]
> 翻译无效问题，需要在设置里面把"翻译引擎"后面的√打上(使用translate.google.com)

亲测可以解决问题

**Comment by LJJ802311** [comment]
> > 翻译无效问题，需要在设置里面把"翻译引擎"后面的√打上(使用translate.google.com)
> 
> 亲测可以解决问题

改为之后现在报 
![image](https://user-images.githubusercontent.com/35536498/133364656-b23f47bb-58ae-4891-838c-92125e3eaf15.png)

**Comment by Mibloom** [comment]
![image](https://user-images.githubusercontent.com/34772629/133364689-229e9298-5d2e-4ec8-aecf-f4f7200749f8.png)

**Comment by LJJ802311** [comment]
translate.google.com 这个网址要翻墙啊

**Comment by YiiGuxing** [comment]
我很担心，这可能是谷歌翻译无法继续白嫖的征兆，希望事情不是这样的。。。。。

**Comment by YiiGuxing** [comment]
> translate.google.com 这个网址要翻墙啊

@LJJ802311  这个早些时候就不需要翻墙了的。

**Comment by YiiGuxing** [comment]
可能是CN的服务的问题，等一会儿吧。。。

**Comment by GyyEcho** [comment]
我看回复说的是 勾选translate.google.com确实有一段时间可以了 我Google一下 发现是Google翻译给锁IP了

**Comment by gitzwt** [comment]
translate.google.cn网页使用目前是正常,勾选translate.google.com只能使用一段时间,后面就不行了

**Comment by Ucaen** [comment]
坐等解决，解决好了 麻烦亲们@我下

**Comment by YiiGuxing** [comment]
> 我看回复说的是 勾选translate.google.com确实有一段时间可以了 我Google一下 发现是Google翻译给锁IP了

> translate.google.cn网页使用目前是正常,勾选translate.google.com只能使用一段时间,后面就不行了

@gitzwt  @GyyEcho 

谷歌翻译使用的是公共的版本，有翻译频率的限制，翻译频率过高会被限制使用，被限制使用之后需要过24小时后才能再次使用。有高频率翻译需求的，请考虑使用百度、有道等其他翻译引擎，它们没有这方面的限制。

**Comment by kbill4345** [comment]
申请一个有道appid，可以用了

**Comment by YiiGuxing** [comment]
> 申请一个有道appid，可以用了，但是期望能有配置梯子选项，谢谢作者的辛勤付出！

@kbill4345 配置梯子请在“HTTP Proxy”那点配置：

**Comment by caopenghehe** [comment]
**设置>工具>翻译 勾选使用translate.google.com 就可以继续使用了**

**Comment by wudimenghuan** [comment]
> > 我看回复说的是 勾选translate.google.com确实有一段时间可以了 我Google一下 发现是Google翻译给锁IP了
> 
> > translate.google.cn网页使用目前是正常,勾选translate.google.com只能使用一段时间,后面就不行了
> 
> @gitzwt @GyyEcho
> 
> 谷歌翻译使用的是公共的版本，有翻译频率的限制，翻译频率过高会被限制使用，被限制使用之后需要过24小时后才能再次使用。有高频率翻译需求的，请考虑使用百度、有道等其他翻译引擎，它们没有这方面的限制。

谷歌提供接口服务吗，像别的引擎一样可以配置一下个人appid

**Comment by shilohooo** [comment]
> 翻译无效问题，需要在设置里面把"翻译引擎"后面的√打上(使用translate.google.com)

多谢老板

**Comment by SmailChildren** [comment]
[
![image](https://user-images.githubusercontent.com/74518372/133560674-a3ef0d7b-4b37-471f-9dd9-a6cc88fa54a2.png)
](url)

**Comment by YiiGuxing** [comment]
> > > 我看回复说的是 勾选translate.google.com确实有一段时间可以了 我Google一下 发现是Google翻译给锁IP了
> > 
> > 
> > > translate.google.cn网页使用目前是正常,勾选translate.google.com只能使用一段时间,后面就不行了
> > 
> > 
> > @gitzwt @GyyEcho
> > 谷歌翻译使用的是公共的版本，有翻译频率的限制，翻译频率过高会被限制使用，被限制使用之后需要过24小时后才能再次使用。有高频率翻译需求的，请考虑使用百度、有道等其他翻译引擎，它们没有这方面的限制。
> 
> 谷歌提供接口服务吗，像别的引擎一样可以配置一下个人appid

谷歌翻译是有的，但是需要VISA信用卡才能申请，所以到目前为止我没有相关资源进行开发测试。

**Comment by PDPENG** [comment]
已解决该项问题，勾选Google，亲测有效

**Comment by zhoufeng-success** [comment]
我的是鼠标悬停可以翻译成功，但是弹出框或者选中单词翻译的时候会失败

>Plugin v2.9.2  
>IntelliJ IDEA 2019.3.1  
>Build #IU-193.5662.46, built on December 16, 2019  
>Runtime version: 11.0.5+10-b520.17 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:101)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:186)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2704)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2690)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1849)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:385)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:440)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:105)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:75)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:518)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:500)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:73)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:80)
	... 7 more
```

**Comment by ztLLL** [comment]
同样的问题：

翻译失败: 未知错误

>Plugin v2.9.2  
>IntelliJ IDEA 2019.3.4  
>Build #IU-193.6911.18, built on March 17, 2020  
>Runtime version: 11.0.6+8-b520.43 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:101)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:186)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2704)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2690)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1849)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:385)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:440)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:105)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:75)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:518)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:500)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:73)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:80)
	... 7 more
```
将translate.google.com打上对勾后报错如下：
>Plugin v2.9.2  
>IntelliJ IDEA 2019.3.4  
>Build #IU-193.6911.18, built on March 17, 2020  
>Runtime version: 11.0.6+8-b520.43 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: 翻译失败: 网络连接超时，请检查网络连接
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:101)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:186)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: cn.yiiguxing.plugin.translate.trans.NetworkException: connect timed out. host=translate.google.com
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.onError(GoogleTranslator.kt:117)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:18)
	... 8 more
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1227)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1337)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:118)
	at com.intellij.util.io.HttpRequests$Request.write(HttpRequests.java:112)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:74)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:518)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:500)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:350)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:73)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:80)
	... 7 more
```
求大佬解决！

**Comment by renoyuan** [comment]
> 翻译失败: 未知错误
> 
> > Plugin v3.1.1
> > IntelliJ IDEA 2021.2
> > Build #IU-212.4746.92, built on July 27, 2021
> > Runtime version: 11.0.11+9-b1504.13 amd64
> > VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> > OS: Windows 10 10.0
> 
> ```
> cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
> 	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
> 	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
> 	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415)
> 	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
> 	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
> 	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
> 	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
> 	... 11 more
> ```
我也遇到了

**Comment by zhuhelong** [comment]
如果插件的 Google 翻译不可用，不介意的话，可以使用我开发的另外一款 Windows 桌面小软件先顶一顶，我也遇到了 Google 翻译不可用问题，现在解决了，欢迎大家支持！地址：https://github.com/zhuhelong/Translator

**Comment by YiiGuxing** [comment]
@zhoufeng-success @ztLLL @renoyuan 请按此处理方法处理：#827，感谢伙伴们的支持！

**Comment by sjnmzsl** [comment]
okk
