### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by Zero-1412** [YiiGuxing/TranslationPlugin#824]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## >Plugin v3.1.1  
>Android Studio Arctic Fox | 2020.3.1  
>Build #AI-203.7717.56.2031.7583922, built on July 27, 2021  
>Runtime version: 11.0.10+0-b96-7249189 amd64  
>VM: OpenJDK 64-Bit Server VM by Oracle Corporation  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:276)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:391)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:461)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 12 more
```

**Comment by Zero-1412** [comment]
未知错误，是因为开代理的原因吗，但之前也开了

**Comment by YiiGuxing** [comment]
merged: #821
