### ISSUE TITLE
Translation stopped working.

### ISSUE THREAD

**Issue by kv4** [YiiGuxing/TranslationPlugin#828]
Translation failed: Unknown error

>Plugin v3.1.1  
>PhpStorm 2021.2  
>Build #PS-212.4746.100, built on July 28, 2021  
>Runtime version: 11.0.11+9-b1504.13 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Linux 5.11.0-34-generic

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google Translate :: Translation failed: Unknown error
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 11 more
```

Please help me fix the problem.

**Comment by YiiGuxing** [comment]
As a temporary solution, you can check the `Use translate.google.com` option on the plugin settings page.

**Comment by kv4** [comment]
Thank you for such a quick response! It really works. 
And thank you for this plugin - it's great.

**Comment by schrek1** [comment]
awsome trick :)

**Comment by darkjinnee** [comment]
Thanks for the help

**Comment by frankyxcs** [comment]
Hi guys

i have this problem now with Android Studio Artic Fox ...any idea how to fix this ..there is no settings page for the plugin

**Comment by didiosn** [comment]
> Hi guys
> 
> i have this problem now with Android Studio Artic Fox ...any idea how to fix this ..there is no settings page for the plugin

There is : Go to settings, in left pane, expand Tools menu and select TRANSLATION

![image](https://user-images.githubusercontent.com/15895051/133885321-dd404bc4-86fc-4018-895b-2704f8a206b2.png)

**Comment by frankyxcs** [comment]
Ahh thanx have overseen this. 
Greets
Frank

**Comment by Vladimir25** [comment]
> As a temporary solution, you can check the `Use translate.google.com` option on the plugin settings page.

thx a lot

**Comment by unkarjedy** [comment]
same here, workaround helped
