### ISSUE TITLE
idea插件暂停工作

### ISSUE THREAD

**Issue by gclm** [YiiGuxing/TranslationPlugin#845]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
正常使用过程中突然异常报错

### 环境 & 错误日志
- 插件版本: 3.1.1
- IDE版本:  2021.2.2 
- 操作系统版本: macos 11.6
- 错误日志:
```
com.intellij.diagnostic.PluginException: Key cn.yiiguxing.plugin.translate.service.TranslationUIManager duplicated [Plugin: cn.yiiguxing.plugin.translate]
	at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:492)
	at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:250)
	at com.intellij.openapi.project.impl.DefaultProjectImpl.init(DefaultProject.java:317)
	at com.intellij.openapi.project.impl.DefaultProject$1.init(DefaultProject.java:54)
	at com.intellij.openapi.project.impl.DefaultProjectTimed.get(DefaultProjectTimed.java:33)
	at com.intellij.openapi.project.impl.DefaultProject.getDelegate(DefaultProject.java:138)
	at com.intellij.openapi.project.impl.DefaultProject.getMessageBus(DefaultProject.java:246)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:207)
	at com.intellij.openapi.wm.impl.welcomeScreen.FlatWelcomeFrame.getProject(FlatWelcomeFrame.java:516)
	at com.intellij.openapi.wm.IdeFocusManager.findByComponent(IdeFocusManager.java:179)
	at com.intellij.openapi.wm.IdeFocusManager.findInstanceByComponent(IdeFocusManager.java:172)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:478)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:457)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:416)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:887)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:874)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeBalloonLayoutImpl.showPopup(WelcomeBalloonLayoutImpl.java:136)
	at com.intellij.openapi.wm.impl.welcomeScreen.WelcomeScreenComponentFactory$4.actionPerformed(WelcomeScreenComponentFactory.java:300)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:441)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:428)
	at com.intellij.ui.components.labels.ActionLink$1.linkSelected(ActionLink.java:51)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:177)
	at com.intellij.ui.components.labels.ActionLink.doClick(ActionLink.java:60)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:363)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by YiiGuxing** [comment]
请问如何才能复现这个问题？

**Comment by gclm** [comment]
1. 我安装插件
2. 配置有道翻译
3. 正常使用就直接报这个错误了。
@YiiGuxing

**Comment by YiiGuxing** [comment]
复现不了啊，通过错误信息分析应该是IDE的问题（成功甩锅~）

**Comment by gclm** [comment]
OK。我换个翻译源试试

**Comment by bestrow** [comment]
插件版本: 3.1.1
IDE版本: 2021.2.2
操作系统版本: macos 11.0.1
出现相同错误

**Comment by YiiGuxing** [comment]
> 插件版本: 3.1.1
> IDE版本: 2021.2.2
> 操作系统版本: macos 11.0.1
> 出现相同错误

请问怎么出现的？可能安步骤重现吗？

**Comment by bestrow** [comment]
> > 插件版本: 3.1.1
> > IDE版本: 2021.2.2
> > 操作系统版本: macos 11.0.1
> > 出现相同错误
> > @bestrow 请问怎么出现的？可能安步骤重现吗？

看了其他issues ，勾选使用translate.google.com,能够正常使用，无法复现
![image](https://user-images.githubusercontent.com/30656702/134482012-a4531b54-a11c-415b-92e8-eaa9994fea7c.png)

**Comment by YiiGuxing** [comment]
> > > 插件版本: 3.1.1
> > > IDE版本: 2021.2.2
> > > 操作系统版本: macos 11.0.1
> > > 出现相同错误
> > > @bestrow 请问怎么出现的？可能安步骤重现吗？
> 
> 看了其他issues ，勾选使用translate.google.com,能够正常使用，无法复现
> ![image](https://user-images.githubusercontent.com/30656702/134482012-a4531b54-a11c-415b-92e8-eaa9994fea7c.png)

那这个就不是同一个问题了。

**Comment by yuxiao97** [comment]
以下是我的错误信息，用的好好的，突然就出现了，已经好几天了，是不是挂了？

翻译失败: 未知错误

>Plugin v3.1.1  
>IntelliJ IDEA 2021.2  
>Build #IU-212.4746.92, built on July 27, 2021  
>Runtime version: 11.0.11+9-b1504.13 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: macOS 11.6

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 11 more
```

**Comment by YiiGuxing** [comment]
> 以下是我的错误信息，用的好好的，突然就出现了，已经好几天了，是不是挂了？
> 
> 翻译失败: 未知错误
> 
> >Plugin v3.1.1  
> >IntelliJ IDEA 2021.2  
> >Build #IU-212.4746.92, built on July 27, 2021  
> >Runtime version: 11.0.11+9-b1504.13 x86_64  
> >VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
> >OS: macOS 11.6
> 
> ```
> cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
> 	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
> 	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
> 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
> 	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
> 	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415)
> 	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
> 	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
> 	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
> 	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
> 	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
> 	... 11 more
> ```
> 

@yuxiao97 请按照 #827 的方法处理

**Comment by thatCbin** [comment]
Settings -> Tools -> Translation 
使用 translate.google.com

**Comment by gclm** [comment]
换了一个翻译源还是不行，同样的错误

**Comment by YiiGuxing** [comment]
> 换了一个翻译源还是不行，同样的错误

卸载重新安装试试？

是更新IDE版本以后出现的吗？

**Comment by gclm** [comment]
> 卸载重新安装试试？
已经试过了，还是不行。
> 是更新IDE版本以后出现的吗？
是的

**Comment by YiiGuxing** [comment]
是在哪个界面出现的？能否请您录制一个操作过程我看一下？

**Comment by gclm** [comment]
我正在回退idea版本，估计没办法给你录制了。他是在窗口右下角有个弹窗显示异常。等我下班了，我录制号继续发到这里

**Comment by YiiGuxing** [comment]
> 我正在回退idea版本，�估计没办法给你录制了。他是在窗口右下角有个弹窗显示异常。�等我下班了，我录制号继续发到这里

好的，感谢！

**Comment by YiiGuxing** [comment]
@gclm 可否请您帮忙测试一下这个版本（[TranslationPlugin-3.2-SNAPSHOT.zip](https://github.com/YiiGuxing/TranslationPlugin/files/7230668/TranslationPlugin-3.2-SNAPSHOT.zip)）能不能在2021.2.2版本上使用，还会不会报异常。我尝试修复了一下这个问题，但是我没有Mac电脑测试。麻烦您了，感谢您的支持！

**Comment by gclm** [comment]
## 信息反馈
1. 我上次回退版本到2021.2.1版本后再使用插件没出现过类似问题
2.目前我已经升到2021.2.2版本使用测试包进行测试，这次没有直接出现上次的错误，我在试用1天左右，看还会不会出现上次的问题，到时候我及时反馈到该issues 中

**Comment by YiiGuxing** [comment]
> ## 信息反馈
> 1. 我上次回退版本到2021.2.1版本后再使用插件没出现过类似问题
> 2. 目前我已经升到2021.2.2版本使用测试包进行测试，这次没有直接出现上次的错误，我在试用1天左右，看还会不会出现上次的问题，到时候我及时反馈到该issues 中

好的，谢谢！

**Comment by gclm** [comment]
试用三天了。没有出现任何问题

**Comment by YiiGuxing** [comment]
> 试用三天了。没有出现任何问题

好的，感谢
