### ISSUE TITLE
没有 translate.google.com 这个选项

### ISSUE THREAD

**Issue by ThankyouEverybody** [YiiGuxing/TranslationPlugin#849]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ✅] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ✅] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
![image](https://user-images.githubusercontent.com/38928746/134635549-db9ff53c-ee8a-4537-a183-bb2e54b2e69b.png)

### 问题描述
1.没有 translate.google.com 这个选项
2.升级无效
3.卸载重安装无效

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本: 

更新TTK失败，请检查网络连接

>Plugin v2.9.3-192  
>IntelliJ IDEA 2019.2.4  
>Build #IU-192.7142.36, built on October 29, 2019  
>Runtime version: 11.0.4+10-b304.77 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: macOS 10.15.7

```
cn.yiiguxing.plugin.translate.trans.NetworkException: connect timed out. host=translate.googleapis.com
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:87)
	at cn.yiiguxing.plugin.translate.trans.TKK.update(TK.kt:54)
	at cn.yiiguxing.plugin.translate.trans.TKK.getValue(TK.kt:44)
	at cn.yiiguxing.plugin.translate.trans.TKKt.tk$default(TK.kt:106)
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.getTranslateUrl(GoogleTranslator.kt:75)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:60)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:72)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:205)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$Companion.getTranslatedDocumentation(TranslateDocumentationAction.kt:176)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider$Companion$TranslationTask$$special$$inlined$runAsync$1.run(promise.kt:242)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1227)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:626)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:389)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:398)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:453)
	at com.intellij.util.io.RequestBuilder.lambda$readString$3(RequestBuilder.java:86)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:537)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:61)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:363)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:86)
	at cn.yiiguxing.plugin.translate.trans.TKK.updateFromGoogle(TK.kt:67)
	... 12 more
```

**Comment by ThankyouEverybody** [comment]
![image](https://user-images.githubusercontent.com/38928746/134635870-b6e9ec76-e42e-48c4-ad63-9d5a2a4b3cc7.png)

**Comment by YiiGuxing** [comment]
你这个是网络的问题哈，网络的问题就找网络哈~~~

**Comment by YiiGuxing** [comment]
请另阅： #454

**Comment by ThankyouEverybody** [comment]
> 请另阅： #454

网络是好的呀 两周之前插件是好使的 就这段时间不行了 升级前翻译文档可以 翻译单个单词就不行, 升级后都不行了...   感谢 我想想别的办法
