### ISSUE TITLE
请求过多，请稍后再试

### ISSUE THREAD

**Issue by ericwu0930** [YiiGuxing/TranslationPlugin#858]
## 检查清单

* [x]  我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x]  我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
可以翻译doc，但是选词翻译以及输词翻译的时候会报请求过多，请稍后再试的错误
### 环境 & 错误日志

翻译失败: 请求过多，请稍候再试

>Plugin v3.1.1  
>IntelliJ IDEA 2021.2  
>Build #IU-212.4746.92, built on July 27, 2021  
>Runtime version: 11.0.11+9-b1504.13 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: macOS 11.5.2

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 请求过多，请稍候再试
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: https://translate.googleapis.com/translate_a/single?sl=auto&tl=en&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dj=1&ie=UTF-8&oe=UTF-8&hl=eo&tk=944505.557746
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate$lambda-3(AbstractTranslator.kt:90)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 11 more
```

**Comment by YiiGuxing** [comment]
请另阅： #859
