### ISSUE TITLE
在控制台中 选中文字后，使用 ctrl + T 会出现 "InvocationTargetException: java.nio.channels.ClosedByInterruptException null" 异常

### ISSUE THREAD

**Issue by longzl2015** [YiiGuxing/TranslationPlugin#87]
InvocationTargetException: java.nio.channels.ClosedByInterruptException null
org.picocontainer.defaults.PicoInvocationTargetInitializationException: InvocationTargetException: java.nio.channels.ClosedByInterruptException null
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:110)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
	at com.intellij.ide.passwordSafe.PasswordSafe.getInstance(PasswordSafe.java:28)
	at cn.yiiguxing.plugin.translate.compat.PasswordSafeCompat.getPassword(PasswordSafeCompat.java:31)
	at cn.yiiguxing.plugin.translate.Settings.getAppPrivateKey(Settings.java:151)
	at cn.yiiguxing.plugin.translate.Translator.getQueryUrl(Translator.java:90)
	at cn.yiiguxing.plugin.translate.Translator.access$000(Translator.java:20)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
	at java.nio.file.Files.readAllBytes(Files.java:3154)
	at com.intellij.util.io.PathKt.readBytes(path.kt:137)
	at com.intellij.credentialStore.MasterKeyFileStorage.get(KeePassCredentialStore.kt:247)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:70)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:44)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.computeProvider(PasswordSafeImpl.kt:38)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt:46)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	... 19 more
Caused by:

java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
	at java.nio.file.Files.readAllBytes(Files.java:3154)
	at com.intellij.util.io.PathKt.readBytes(path.kt:137)
	at com.intellij.credentialStore.MasterKeyFileStorage.get(KeePassCredentialStore.kt:247)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:70)
	at com.intellij.credentialStore.KeePassCredentialStore.<init>(KeePassCredentialStore.kt:44)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImplKt.computeProvider(PasswordSafeImpl.kt:38)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt:46)
	at com.intellij.ide.passwordSafe.impl.PasswordSafeImpl.<init>(PasswordSafeImpl.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:220)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:239)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:206)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:38)
	at com.intellij.ide.passwordSafe.PasswordSafe.getInstance(PasswordSafe.java:28)
	at cn.yiiguxing.plugin.translate.compat.PasswordSafeCompat.getPassword(PasswordSafeCompat.java:31)
	at cn.yiiguxing.plugin.translate.Settings.getAppPrivateKey(Settings.java:151)
	at cn.yiiguxing.plugin.translate.Translator.getQueryUrl(Translator.java:90)
	at cn.yiiguxing.plugin.translate.Translator.access$000(Translator.java:20)
	at cn.yiiguxing.plugin.translate.Translator$QueryRequest.run(Translator.java:121)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by longzl2015** [comment]
和 #71 显示的一样，签名异常到没有出现

**Comment by YiiGuxing** [comment]
谢谢反馈，我大概知道是怎么个回事了，有时间我修复一下。

**Comment by YiiGuxing** [comment]
commit [bd6ef2b0ad61853cc9ccbd14d4e157428c381a94](https://github.com/YiiGuxing/TranslationPlugin/commit/bd6ef2b0ad61853cc9ccbd14d4e157428c381a94)
