### ISSUE TITLE
百度翻译 :: 翻译失败: 未知错误

### ISSUE THREAD

**Issue by run0817** [YiiGuxing/TranslationPlugin#871]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本:

**Comment by KoakiMiku** [comment]
3.2版本，同一个问题，有道、阿里 也是这个报错。

>Plugin v3.2  
>JetBrains Rider 2021.2.1  
>Build #RD-212.5080.71, built on August 26, 2021  
>Runtime version: 11.0.11+9-b1504.16 amd64  
>VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 阿里翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:194)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoClassDefFoundError: kotlinx/collections/immutable/ExtensionsKt
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter$codeMapping$2.invoke(LanguageAdapter.kt:26)
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter$codeMapping$2.invoke(LanguageAdapter.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter.getCodeMapping(LanguageAdapter.kt:25)
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter.access$getCodeMapping(LanguageAdapter.kt:23)
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter$langMapping$2.invoke(LanguageAdapter.kt:30)
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter$langMapping$2.invoke(LanguageAdapter.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter.getLangMapping(LanguageAdapter.kt:29)
	at cn.yiiguxing.plugin.translate.trans.BaseLanguageAdapter.getLanguageCode(LanguageAdapter.kt:43)
	at cn.yiiguxing.plugin.translate.trans.ali.AliLanguageAdapterKt.getAliLanguageCode(AliLanguageAdapter.kt:20)
	at cn.yiiguxing.plugin.translate.trans.ali.AliTranslator.call(AliTranslator.kt:133)
	at cn.yiiguxing.plugin.translate.trans.ali.AliTranslator.access$call(AliTranslator.kt:23)
	at cn.yiiguxing.plugin.translate.trans.ali.AliTranslator$doTranslate$1.invoke(AliTranslator.kt:95)
	at cn.yiiguxing.plugin.translate.trans.ali.AliTranslator$doTranslate$1.invoke(AliTranslator.kt:97)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.ali.AliTranslator.doTranslate(AliTranslator.kt:97)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:19)
	... 12 more
```

**Comment by YiiGuxing** [comment]
请问3.1.1版本有同样的问题吗？

**Comment by run0817** [comment]
@YiiGuxing 没有问题

**Comment by KoakiMiku** [comment]
> 请问3.1.1版本有同样的问题吗？

上个版本是正常的

**Comment by dnslin** [comment]
上个版本 无问题 今天更新的最新版本出现了网易 百度都用不了的情况 只有谷歌才可以使用
我的idea 和 Translation都是最新版本
