### ISSUE TITLE
M1的Idea更新到最新版Translation之后，插件

### ISSUE THREAD

**Issue by XuBoZhangQvQ** [YiiGuxing/TranslationPlugin#877]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
M1的Idea更新到最新版Translation之后，报错
### 环境 & 错误日志
- 插件版本: 2.3.0.1
- IDE版本: IDEA 2021.2.2 
- 操作系统版本: M1芯片的MacOs

- 错误日志:
```
java.lang.ClassCastException: class cn.yiiguxing.plugin.translate.documentation.TranslatedDocComments cannot be cast to class cn.yiiguxing.plugin.translate.documentation.TranslatedDocComments (cn.yiiguxing.plugin.translate.documentation.TranslatedDocComments is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @32eb480d; cn.yiiguxing.plugin.translate.documentation.TranslatedDocComments is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @27c98e1f)
	at cn.yiiguxing.plugin.translate.documentation.TranslatedDocComments$Companion.service(TranslatedDocComments.kt:40)
	at cn.yiiguxing.plugin.translate.documentation.TranslatedDocComments$Companion.translatedDocs(TranslatedDocComments.kt:42)
	at cn.yiiguxing.plugin.translate.documentation.TranslatedDocComments$Companion.isTranslated(TranslatedDocComments.kt:25)
	at cn.yiiguxing.plugin.translate.provider.TranslatingDocumentationProvider.generateRenderedDoc(TranslatingDocumentationProvider.kt:39)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateRenderedDoc(CompositeDocumentationProvider.java:163)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory.calcText(DocRenderPassFactory.java:91)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory.lambda$calculateItemsToRender$0(DocRenderPassFactory.java:82)
	at com.intellij.lang.java.JavaDocumentationProvider.collectDocComment(JavaDocumentationProvider.java:634)
	at com.intellij.lang.java.JavaDocumentationProvider.collectDocComments(JavaDocumentationProvider.java:626)
	at com.intellij.lang.java.JavaDocumentationProvider.collectDocComments(JavaDocumentationProvider.java:613)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.collectDocComments(CompositeDocumentationProvider.java:175)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory.calculateItemsToRender(DocRenderPassFactory.java:79)
	at com.intellij.codeInsight.documentation.render.DocRenderPassFactory$DocRenderPass.doCollectInformation(DocRenderPassFactory.java:64)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:414)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1078)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:407)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:406)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:174)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:380)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by YiiGuxing** [comment]
这个是因为IDE的动态加载的问题，重启IDE即可。
