### ISSUE TITLE
我的webstorm win10专业版 2021.1.3 无法安装翻译的 wordbook 驱动程序问题

### ISSUE THREAD

**Issue by springandme** [YiiGuxing/TranslationPlugin#886]
以下是异常信息

java.util.concurrent.ExecutionException: java.io.IOException: Failed to download driver file
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.downloadDriverAndInitializeService(WordBookService.kt:110)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.access$downloadDriverAndInitializeService(WordBookService.kt:35)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService$downloadDriver$1.run(WordBookService.kt:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Failed to download driver file
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.downloadDriverFile(WordBookService.kt:153)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.downloadDriverAndInitializeService$lambda-3(WordBookService.kt:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 7 more
Caused by: javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:349)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:292)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:287)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:144)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:609)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:356)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.downloadDriverFile$lambda-8(WordBookService.kt:124)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.wordbook.WordBookService.downloadDriverFile(WordBookService.kt:123)
	... 10 more
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:380)
		... 30 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
	... 27 more

**Comment by YiiGuxing** [comment]
从异常信息上看，这个是网络的问题㖿~

**Comment by YiiGuxing** [comment]
实在不行的话你可以自己下载然后存放到指定的目录下：
1. 下载sqlite的jar包`sqlite-jdbc-3.34.0.jar`（需要3.34.0版本以上哈）；
2. 将jar包存放到用户目录下：`C:\Users\{{你的用户名}}\.translation`；
3. 将jar重命名为`driver-3.34.0.jar`（只能是这个文件名哈，不能变）；
4. 重启IDE。

**Comment by springandme** [comment]
环境重新说明一下, 我当前环境处于公司的网络, 网络确实有点小问题, 我自己的笔记本连热点, 同样的`webstorm`版本是正常下载这个文件的, 正常使用workbook的功能,  但我还是有疑问, 公司的 `IDEA` 的 2020.1.2版本, workbook能正常使用

我已经按着你的要求把这个 jar包放到指定目录, 

![Snipaste_2021-11-02_16-33-32](https://user-images.githubusercontent.com/44739137/139812429-1dc3c089-721e-495c-b271-2e1538d9c44a.png)

但是我重启 webstorm IDE 之后, 翻译单词, 点击收藏, 继续出现那个下载驱动程序文件, 但是下载还是失败了, 异常信息跟上面的一模一样, 
这个 `caches` 目录下  出现一个 `UUID` 文件
这是里面的内容

![Snipaste_2021-11-02_16-38-15](https://user-images.githubusercontent.com/44739137/139813117-c77c90c8-c8e6-401f-ac84-8542d9f985c7.png)

```json
{
    "sentences": [
        {
            "trans": "href",
            "orig": "href",
            "backend": 3,
            "model_specification": [
                {}
            ],
            "translation_engine_debug_info": [
                {
                    "model_tracking": {
                        "checkpoint_md5": "10557117644f7a91d109812a56f5d3fe",
                        "launch_doc": "en_zh_2021q1.md"
                    }
                }
            ]
        },
        {
            "translit": "Href"
        }
    ],
    "src": "en",
    "confidence": 0.6745098,
    "spell": {},
    "ld_result": {
        "srclangs": [
            "en"
        ],
        "srclangs_confidences": [
            0.6745098
        ],
        "extended_srclangs": [
            "en"
        ]
    }
}
```

**Comment by springandme** [comment]
json 文件的信息可以忽略一下哈, 我才发现就是 翻译单词的日志缓存  尴尬了 -_-

**Comment by YiiGuxing** [comment]
这就奇怪了，那插件你安装的是哪个版本的？

**Comment by springandme** [comment]
TranslationPlugin-3.2.0.1  这个版本

**Comment by springandme** [comment]
idea 是 3.1.1  webstorm是 3.2.0.1

**Comment by YiiGuxing** [comment]
我的锅，文件名应该是 `driver-v3.34.0.jar`

**Comment by springandme** [comment]
感谢作者, 成功解决问题  ^-^
