### ISSUE TITLE
翻译的时候报错58003 

### ISSUE THREAD

**Issue by wangguohui0726** [YiiGuxing/TranslationPlugin#890]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [X] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
使用百度翻译 配置好了之后翻译的时候报错58003 
![image](https://user-images.githubusercontent.com/33613004/143411053-1a05ec5e-97af-47e0-89df-478a3ad64957.png)

### 问题描述
使用百度翻译 配置好了之后翻译的时候报错58003 
![image](https://user-images.githubusercontent.com/33613004/143411053-1a05ec5e-97af-47e0-89df-478a3ad64957.png)

### 环境 & 错误日志
- 插件版本: 3.2.0.1
- IDE版本: 2021.2.3
- 操作系统版本:mac

- 错误日志:
```
翻译文档失败: 翻译失败: 未知错误[58003]

>Plugin v3.2.0.1  
>IntelliJ IDEA 2021.2.3  
>Build #IU-212.5457.46, built on October 12, 2021  
>Runtime version: 11.0.12+7-b1504.40 x86_64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: macOS 11.3.1

```

```
cn.yiiguxing.plugin.translate.trans.TranslateException: 百度翻译 :: 翻译失败: 未知错误[58003]
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:152)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:49)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:194)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: cn.yiiguxing.plugin.translate.trans.TranslateResultException: 百度翻译 :: Translate failed: 58003
	at cn.yiiguxing.plugin.translate.trans.baidu.BaiduTranslator.parseTranslation(BaiduTranslator.kt:199)
	at cn.yiiguxing.plugin.translate.trans.baidu.BaiduTranslator.access$parseTranslation(BaiduTranslator.kt:22)
	at cn.yiiguxing.plugin.translate.trans.baidu.BaiduTranslator$doTranslate$2.invoke(BaiduTranslator.kt:168)
	at cn.yiiguxing.plugin.translate.trans.baidu.BaiduTranslator$doTranslate$2.invoke(BaiduTranslator.kt:168)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
	at cn.yiiguxing.plugin.translate.trans.baidu.BaiduTranslator.doTranslate(BaiduTranslator.kt:168)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:19)
	... 13 more
```
-->

**Comment by YiiGuxing** [comment]
请查阅官方文档常见问题部分：

http://api.fanyi.baidu.com/doc/21
