### ISSUE TITLE
谷歌翻译被禁用了，有添加代理的功能吗？

### ISSUE THREAD

**Issue by zhangxxyz** [YiiGuxing/TranslationPlugin#895]

**Comment by YiiGuxing** [comment]
没有被禁啊。。。。   

要使用代理的话就在IDE的代理配置页面上配置就行了。

**Comment by zhangxxyz** [comment]
啊？你确定吗？我这里都被禁了，只有翻墙才能用，另外，我今天注册了百度翻译，确定appid与秘钥都没错，但是提示账号无效

**Comment by YiiGuxing** [comment]
> 啊？你确定吗？我这里都被禁了，只有翻墙才能用，另外，我今天注册了百度翻译，确定appid与秘钥都没错，提示账号无效，但是能翻译

谷歌的我这边一直都能用的，应该是没有被禁的。你可以在Chrome，Edge等浏览器安装谷歌官方自家的翻译插件：
https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

如果它能翻译，那么这个插件也应该没问题。
如果都不能，那么应该就是你网络环境的问题了。

**Comment by YiiGuxing** [comment]
百度账号可能是有点延迟

**Comment by songjinhe** [comment]
我的插件里选择Google翻译也是一直提示更新 TKK 失败，请检查网络连接。
稳定用了几年了，前几天Google翻译出现辱华言论以后就不能用了。
打开其他外网地址都可以，https://translate.google.com也能正常访问。

**Comment by YiiGuxing** [comment]
> 我的插件里选择Google翻译也是一直提示更新 TKK 失败，请检查网络连接。
> 稳定用了几年了，前几天Google翻译出现辱华言论以后就不能用了。
> 打开其他外网地址都可以，https://translate.google.com      也能正常访问。
> 

那就不用了吧，用阿里、百度、有道的

**Comment by hello-piper** [comment]
更新 TKK 失败，请检查网络连接

>Plugin v3.2.0.1  
>IntelliJ IDEA 2020.3.4  
>Build #IC-203.8084.24, built on April 27, 2021  
>Runtime version: 11.0.10+8-b1145.96 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.NetworkException: connect timed out. host=translate.googleapis.com
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.updateFromGoogle(TK.kt:85)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.update(TK.kt:56)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.getValue(TK.kt:46)
	at cn.yiiguxing.plugin.translate.trans.google.TKKt.tk$default(TK.kt:103)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:92)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$1.invoke(GoogleTranslator.kt:57)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$1.invoke(GoogleTranslator.kt:55)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:381)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:390)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:461)
	at com.intellij.util.io.RequestBuilder.lambda$readString$3(RequestBuilder.java:78)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:78)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.updateFromGoogle(TK.kt:69)
	... 20 more
```

**Comment by Fliegend4545** [comment]
确实特别不稳定了，之前的版本使用谷歌翻译的旁边不是有个单选框？勾上那个好点，最新版没有了。

**Comment by YiiGuxing** [comment]
> 确实特别不稳定了，之前的版本使用谷歌翻译的旁边不是有个单选框？勾上那个好点，最新版没有了。

@Fliegend4545 那个已经不能使用了，你要么使用代理，要么用其他引擎

**Comment by omaidb** [comment]
大佬,我司只能访问google.com进行翻译,不能访问google.cn进行翻译,怎么修改谷歌翻译的地址啊

**Comment by YiiGuxing** [comment]
> 大佬,我司只能访问google.com进行翻译,不能访问google.cn进行翻译,怎么修改谷歌翻译的地址啊

没有修改翻译地址的地方，google翻译现在只有一个接口了，其他接口无法使用了。

**Comment by dobyjin** [comment]
> 大佬,我司只能访问google.com进行翻译,不能访问google.cn进行翻译,怎么修改谷歌翻译的地址啊

我和你相反，我能访问https://translate.google.cn，com不行。
今天报错
**cn.yiiguxing.plugin.translate.trans.NetworkException: connect timed out. host=translate.googleapis.com**

**Comment by srk24** [comment]
目前API地址，translate.googleapis.com，自己加一下分流吧

**Comment by Swork9527** [comment]
> 目前API地址，translate.googleapis.com，tun模式下自己加一下分流吧

可以把电脑网络的dns设置成8.8.8.8试一下

**Comment by lovelyelfpop** [comment]
谷歌翻译 代理

**Comment by acrossTheGreatWall1024** [comment]
https://hcfy.app/blog/2022/09/28/ggg 解决办法
