### ISSUE TITLE
谷歌翻译有时候可以有时候不行

### ISSUE THREAD

**Issue by foxwhite25** [YiiGuxing/TranslationPlugin#900]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [X] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述
有时候用着用着，前一秒可以，下一秒就不行了。
我虽然觉得是超过速率限制了，但是报错是未知错误，咱也不懂Java，就来看看有没有解决方法。
我的网络所有流量都经过代理，浏览器也能访问 https://translate.google.com/ ，查看记录也发现 IDE 的确有
![image](https://user-images.githubusercontent.com/39846845/145452097-e0d87093-61f4-4339-9e72-cc60767fa7df.png)

### 环境 & 错误日志
- 插件版本: 3.2.0.1
- IDE版本: 2021.3
- 操作系统版本: Win 10
- 错误日志:
```
翻译失败: 未知错误

>Plugin v3.2.0.1  
>PyCharm 2021.3  
>Build #PY-213.5744.248, built on November 30, 2021  
>Runtime version: 11.0.13+7-b1751.19 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3103)
	at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
	at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLengthLong(HttpsURLConnectionImpl.java:398)
	at com.intellij.util.io.HttpRequests$RequestImpl.doReadBytes(HttpRequests.java:435)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:424)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:101)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom$lambda-0(Http.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom(Http.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:96)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:19)
	... 11 more
```

**Comment by YiiGuxing** [comment]
你的IP应该是被限制了，暂时没有权限访问
