### ISSUE TITLE
更新 TKK 失败，请检查网络连接  (translate.googleapis.com 无法访问)

### ISSUE THREAD

**Issue by hello-piper** [YiiGuxing/TranslationPlugin#904]
更新 TKK 失败，请检查网络连接

>Plugin v3.2.0.1  
>IntelliJ IDEA 2020.3.4  
>Build #IC-203.8084.24, built on April 27, 2021  
>Runtime version: 11.0.10+8-b1145.96 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.NetworkException: connect timed out. host=translate.googleapis.com
	at cn.yiiguxing.plugin.translate.trans.NetworkException$Companion.wrapIfIsNetworkException(Exceptions.kt:37)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.updateFromGoogle(TK.kt:85)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.update(TK.kt:56)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.getValue(TK.kt:46)
	at cn.yiiguxing.plugin.translate.trans.google.TKKt.tk$default(TK.kt:103)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:92)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$1.invoke(GoogleTranslator.kt:57)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$1.invoke(GoogleTranslator.kt:55)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:62)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:630)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:381)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:390)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:461)
	at com.intellij.util.io.RequestBuilder.lambda$readString$3(RequestBuilder.java:78)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:541)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:523)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:355)
	at com.intellij.util.io.RequestBuilder.readString(RequestBuilder.java:78)
	at cn.yiiguxing.plugin.translate.trans.google.TKK.updateFromGoogle(TK.kt:69)
	... 20 more
```

**Comment by hello-piper** [comment]
translate.googleapis.com 网站无法访问  我直接浏览器开着代理也访问不了  
能否改成 translate.google.com

**Comment by YiiGuxing** [comment]
> translate.googleapis.com 网站无法访问 我直接浏览器开着代理也访问不了 能否改成 translate.google.com

`translate.googleapis.com` 是通用接口地址，不会被修改成其他的，这个不是接口地址的问题。

**Comment by hello-piper** [comment]
那这个问题怎么解决呢 我这里翻译没法使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 上午9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] 更新 TKK 失败，请检查网络连接  (translate.googleapis.com 无法访问) (Issue #904)





  
translate.googleapis.com 网站无法访问 我直接浏览器开着代理也访问不了 能否改成 translate.google.com
  
translate.googleapis.com 是通用接口地址，不会被修改成其他的，这个不是接口地址的问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YiiGuxing** [comment]
可以使用其他的翻译引擎

**Comment by superjinge** [comment]
使用站长工具ping检测,然后配置host
https://ping.chinaz.com/translate.googleapis.com
@hello-piper   
可以在插件里面说明下tkk网络问题
@YiiGuxing

**Comment by YiiGuxing** [comment]
@superjinge 这个工具不错，感谢推荐！

后面只要是翻译失败，会添加一个使用其他翻译引擎的引导。
