### ISSUE TITLE
翻译失败: 未知错误

### ISSUE THREAD

**Issue by 12num** [YiiGuxing/TranslationPlugin#909]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [ ] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [ ] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
翻译失败: 未知错误
### 问题描述

![pycharm64_hkwjxijKUg](https://user-images.githubusercontent.com/33015062/146503628-8aed1bb7-9882-44dc-9a89-dabbcfa80e2b.png)

### 环境 & 错误日志
- 插件版本: 3.2.1 
- IDE版本:  IDEA 2021.2 
- 操作系统版本: Windows 10 
<!-- (版本崩溃时请提供)
- 错误日志:> PyCharm 2021.2.2 (Professional Edition)  
> 内部版本号 #PY-212.5284.44，September 15, 2021 构建  
> Licensed to PyCharm Evaluator  
> 到期日期: January 16, 2022  
> 运行时版本: 11.0.12+7-b1504.28 amd64  
> VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.  
> Windows 10 10.0  
> GC: G1 Young Generation, G1 Old Generation  
> Memory: 1010M  
> Cores: 4  
> Non-Bundled Plugins: io.zhile.research.ide-eval-resetter (2.3.5), com.intellij.zh (212.325), cn.yiiguxing.plugin.translate (3.2.1)

```

```
在此粘贴错误日志
```
-->```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:151)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:265)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:415)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom$lambda-0(Http.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:517)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom(Http.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:96)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:19)
	... 11 more

<!-- 获取环境与错误日志: http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb -->

**Comment by YiiGuxing** [comment]
IP已被谷歌服务限制访问了
