### ISSUE TITLE
不知道为什么这两天偶尔会出现翻译失败的警告，我也并没有进行翻译，有时候可能是把鼠标移到代码上显示文档，我也不太确定

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [YiiGuxing/TranslationPlugin#929]
翻译文档失败: 翻译失败: 未知错误

> Android Studio Arctic Fox | 2020.3.1 Patch 4  
> 内部版本号 #AI-203.7717.56.2031.7935034，November 21, 2021 构建  
> 运行时版本: 11.0.10+0-b96-7249189 amd64  
> VM: OpenJDK 64-Bit Server VM，Oracle Corporation  
> Windows 10 10.0  
> GC: G1 Young Generation, G1 Old Generation  
> Memory: 4096M  
> Cores: 12  
> Registry: external.system.auto.import.disabled=true, ide.settings.move.mouse.on.default.button=true, debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true, ide.tree.collapse.recursively=false  
> Non-Bundled Plugins: com.dengzii.plugin.adb, com.intellij.zh, com.wuyr.google_library_query, net.seesharpsoft.intellij.plugins.file-preview, net.vektah.codeglance, some.awesome, org.jetbrains.kotlin, com.mistamek.drawablepreview.drawable-preview, me.majiajie.ideaplugin.findviewforandroid, cn.yiiguxing.plugin.translate, org.norbye.tor.kdocformatter, siosio.kodkod, izhangzhihao.rainbow.brackets, org.intellij.plugins.markdown

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:158)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:125)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:62)
	... 10 more
```

**Comment by YiiGuxing** [comment]
烦请提供一下日志文件（idea.log），谢谢：

![image](https://user-images.githubusercontent.com/10737066/148722998-8dba9950-6f13-4b95-98a9-e3be637d2590.png)

**Comment by SaltedFish-Extreme** [comment]
> 烦请提供一下日志文件（idea.log），谢谢：
> 
> ![image](https://user-images.githubusercontent.com/10737066/148722998-8dba9950-6f13-4b95-98a9-e3be637d2590.png)

[idea.log](https://github.com/YiiGuxing/TranslationPlugin/files/7836991/idea.log)

**Comment by YiiGuxing** [comment]
如果IDE版本为2021.3以上的可以暂时使用这个包来消除这个错误：
https://github.com/YiiGuxing/TranslationPlugin/suites/4880376515/artifacts/139623233
