### ISSUE TITLE
大佬我发现一个bug，可能是网络问题，使用的谷歌翻译

### ISSUE THREAD

**Issue by xuMingHai1** [YiiGuxing/TranslationPlugin#940]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

## 问题详情
翻译方法文档的时候出现的，过一会儿就又可以翻译了，我是用的谷歌翻译，应该是网络的问题吧

### 环境 & 错误日志
- 插件版本: 3.2.1-213
- IDE版本:  IntelliJ IDEA 2021.3.1 (Ultimate Edition)
- 操作系统版本:  Windows 10 

- 错误日志:
```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:158)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:125)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:62)
	... 10 more
```

**Comment by xuMingHai1** [comment]
翻译方法文档的时候出现的，过一会儿就又可以翻译了，我是用的谷歌翻译，应该是网络的问题吧

cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:158)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:125)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:62)
	... 10 more``

插件版本:最新版的
IDE版本:最新的
操作系统版本:Win10

**Comment by YiiGuxing** [comment]
duplicate: #929
