### ISSUE TITLE
翻译BUG

### ISSUE THREAD

**Issue by zhanghuizong** [YiiGuxing/TranslationPlugin#941]
![image](https://user-images.githubusercontent.com/4384876/150720035-51608ad3-394b-459b-9f23-2765e3962bf7.png)

java.lang.NoClassDefFoundError: com/sun/javadoc/SeeTag
	at ch.raffael.mddoclet.integrations.idea.MarkdownDocumentationProvider.generateDoc(MarkdownDocumentationProvider.java:127)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:141)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$1$doc$1.compute(TranslateDocumentationAction.kt:62)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$1$doc$1.compute(TranslateDocumentationAction.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:852)
	at cn.yiiguxing.plugin.translate.action.TranslateDocumentationAction$doTranslate$$inlined$executeOnPooledThread$1.run(Applications.kt:150)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: com.sun.javadoc.SeeTag PluginClassLoader(plugin=PluginDescriptor(name=Markdown Doclet for IDEA, id=ch.raffael.mddoclet.integrations.idea.MarkdownDocletIdea, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2021.3\plugins\markdown-doclet-idea-plugin, version=1.4-0, package=null, isBundled=false), packagePrefix=null, instanceId=118, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)

**Comment by YiiGuxing** [comment]
请问如何才能提现这个问题？

**Comment by YiiGuxing** [comment]
从错误信息上看，这个并不是翻译插件的问题。

**Comment by zhanghuizong** [comment]
![image](https://user-images.githubusercontent.com/4384876/151090006-89a4fb38-a21b-4e79-a56d-1ec77fd6ad6c.png)

目前来看. 我使用最新版本. 就会出现这个问题. 之前的老版本未出现这个问题

翻译单个单词正常. 鼠标右键选择: `翻译文档`. 则会出现上面问题

**Comment by YiiGuxing** [comment]
你是不是安装了 `Markdown Doclet for IDEA` 这个插件，这个错误并不是翻译插件的。

**Comment by zhanghuizong** [comment]
确实是这个插件导致的. 关了吧
