### ISSUE TITLE
IDEA 2020.1.3 文档翻译 报错

### ISSUE THREAD

**Issue by zeroxsama** [YiiGuxing/TranslationPlugin#952]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 环境 & 错误日志
- 插件版本: 
- IDE版本: 
- 操作系统版本: 
<!-- (版本崩溃时请提供)
- 错误日志:
```
翻译文档失败: 翻译失败: 未知错误

>Plugin v3.1-201.1  
>IntelliJ IDEA 2020.1.3  
>Build #IU-201.8538.31, built on July 7, 2020  
>Runtime version: 11.0.7+10-b765.64 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:135)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$$special$$inlined$runAsync$1.run(promise.kt:401)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at cn.yiiguxing.plugin.translate.trans.GoogleTranslator.parserResult(GoogleTranslator.kt:105)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:91)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translateDocumentation(AbstractTranslator.kt:104)
	... 6 more

```
-->

<!-- 获取环境与错误日志: http://yiiguxing.github.io/TranslationPlugin/start.html#faq-fb -->

**Comment by YiiGuxing** [comment]
请更新插件到最新版本

**Comment by zeroxsama** [comment]
升级最新的插件版本话&nbsp; 那还要升级 idea版本啊 ...


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月7日(星期一) 上午9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] IDEA 2020.1.3 文档翻译 报错 (Issue #952)





 
请更新插件到最新版本
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YiiGuxing** [comment]
现在可以升级了插件了

**Comment by zeroxsama** [comment]
感谢&nbsp; 明天试试去！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YiiGuxing/TranslationPlugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月7日(星期一) 晚上10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YiiGuxing/TranslationPlugin] IDEA 2020.1.3 文档翻译 报错 (Issue #952)





 
现在可以升级了插件了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
