### ISSUE TITLE
谷歌翻译报错：翻译失败：未知错误

### ISSUE THREAD

**Issue by samumist** [YiiGuxing/TranslationPlugin#953]
## 检查清单
*请确保通过将 [ ] 替换为 [x] 来完成以下步骤*

* [x] 我已经阅读了 [README](https://github.com/YiiGuxing/TranslationPlugin) 中的 [FAQ](https://github.com/YiiGuxing/TranslationPlugin#faq) ，但仍然无法解决我的问题。
* [x] 我已经搜索过与我要提交的问题相匹配的问题，但没有找到。

### 问题描述

使用谷歌翻译大概40分钟后，突然就报错了（见下方错误日志）
<img width="935" alt="截屏2022-02-07 10 38 21" src="https://user-images.githubusercontent.com/3883086/152716082-338845f6-aef5-44b9-8d11-54739936e5cc.png">

### 环境 & 错误日志
- 插件版本: 3.2.2-213
- IDE版本: webstorm 2021.3 
- 操作系统版本: MacOS 11.6 
- 错误日志:
```
翻译失败: 未知错误

> WebStorm 2021.3  
> Build #WS-213.5744.224, built on November 27, 2021  
> Runtime version: 11.0.13+7-b1751.19 x86_64  
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
> macOS 11.6.3  
> GC: G1 Young Generation, G1 Old Generation  
> Memory: 2048M  
> Cores: 8  
> Non-Bundled Plugins:  
>     org.nik.presentation-assistant (1.0.9)  
>     com.markskelton.one-dark-theme (5.5.0)  
>     com.intellij.zh (213.284)  
>     Key Promoter X (2021.3)  
>     com.intellij.lang.jsgraphql (3.1.2)  
>     Dart (213.5744.122)  
>     cn.yiiguxing.plugin.translate (3.2.2-213)  
>     AceJump (3.8.5)  
>     IdeaVIM (1.9.3)  
>     org.jetbrains.IdeaVim-EasyMotion (1.7)  
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:151)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2713)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2699)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1854)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3103)
	at java.base/java.net.URLConnection.getHeaderFieldLong(URLConnection.java:636)
	at java.base/java.net.URLConnection.getContentLengthLong(URLConnection.java:508)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLengthLong(HttpsURLConnectionImpl.java:398)
	at com.intellij.util.io.HttpRequests$RequestImpl.doReadBytes(HttpRequests.java:435)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:424)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:101)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom$lambda-0(Http.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:333)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom(Http.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:96)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:19)
	... 11 more

```

**Comment by YiiGuxing** [comment]
这种情况一般是你的IP被限制了，请过一会再尝试

**Comment by samumist** [comment]
好的，多谢。
我先改用百度的，明天再试回谷歌的。如果恢复了，我会回来报告并关闭issue。

**Comment by samumist** [comment]
刚又试回谷歌，已经恢复了。
@YiiGuxing 谢谢您的帮助🤝
