### ISSUE TITLE
翻译文档失败

### ISSUE THREAD

**Issue by hhhyde** [YiiGuxing/TranslationPlugin#955]
翻译文档失败: 翻译失败: 未知错误

> IntelliJ IDEA 2021.3 (Ultimate Edition)  
> Build #IU-213.5744.223, built on November 27, 2021  
> You have a perpetual fallback license for this version.  
> Runtime version: 11.0.13+7-b1751.19 aarch64  
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.  
> macOS 12.2  
> GC: G1 Young Generation, G1 Old Generation  
> Memory: 1264M  
> Cores: 10  
> Registry:  
>     ide.balloon.shadow.size=0  
>   
> Non-Bundled Plugins:  
>     idea.plugin.protoeditor (213.5744.224)  
>     com.intellij.javafx (1.0.3)  
>     org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)  
>     com.alibaba.p3c.smartfox (2.1.1)  
>     mobi.hsz.idea.gitignore (4.3.0)  
>     com.mallowigi (54.1.0)  
>     cn.wuzhizhan.plugin.mybatis (2020.12.18)  
>     com.chrisrm.idea.MaterialThemeUI (6.12.2)  
>     cn.yiiguxing.plugin.translate (3.2.1-213)  
>   
> Kotlin: 213-1.6.10-release-923-IJ5744.223

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:158)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:110)
	at cn.yiiguxing.plugin.translate.documentation.HtmlTranslatorKt.getTranslatedDocumentation(HtmlTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.documentation.TranslateDocumentationTask$special$$inlined$runAsync$1.run(promise.kt:402)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.parseDocTranslation(GoogleTranslator.kt:125)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$parseDocTranslation(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$translateDocumentation$1$client$2.invoke(GoogleTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.parse(SimpleTranslateClient.kt:19)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:51)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.translateDocumentation(GoogleTranslator.kt:62)
	... 10 more
```

**Comment by YiiGuxing** [comment]
#954
