### ISSUE TITLE
老哥，又翻译出错了，我也没翻译，不知道是不是之前的问题😂

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [YiiGuxing/TranslationPlugin#960]
翻译失败: 未知错误

> Android Studio Bumblebee | 2021.1.1 Patch 1  
> 内部版本号 #AI-211.7628.21.2111.8139111，February 2, 2022 构建  
> 运行时版本: 11.0.11+9-b60-7590822 amd64  
> VM: OpenJDK 64-Bit Server VM，Oracle Corporation  
> Windows 10 10.0  
> GC: G1 Young Generation, G1 Old Generation  
> Memory: 4096M  
> Cores: 12  
> Registry: external.system.auto.import.disabled=true, ide.settings.move.mouse.on.default.button=true, debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true, ide.tree.collapse.recursively=false  
> Non-Bundled Plugins: com.dengzii.plugin.adb (2022.1.22), com.intellij.zh (211.311), com.wuyr.google_library_query (3.3), net.seesharpsoft.intellij.plugins.file-preview (1.6.4), net.vektah.codeglance (1.5.4), org.intellij.gitee (2021.1.0), some.awesome (1.14), wu.seal.tool.jsontokotlin (3.7.2), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), com.mistamek.drawablepreview.drawable-preview (1.1.5), me.majiajie.ideaplugin.findviewforandroid (1.3.1), cn.yiiguxing.plugin.translate (3.2.2), org.norbye.tor.kdocformatter (1.3.3), siosio.kodkod (2.0.4), izhangzhihao.rainbow.brackets (6.21), org.intellij.plugins.markdown (211.7142.37)

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.onError(AbstractTranslator.kt:47)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.onError(GoogleTranslator.kt:131)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.access$onError(AbstractTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:58)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:151)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:271)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: https://translate.googleapis.com/translate_a/single?sl=auto&tl=zh-CN&client=gtx&dt=t&dt=bd&dt=rm&dt=qca&dt=ex&dj=1&ie=UTF-8&oe=UTF-8&hl=zh-CN&tk=284308.175887
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:365)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:429)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:102)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom$lambda-0(Http.kt:18)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:531)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:513)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:332)
	at cn.yiiguxing.plugin.translate.util.Http.postDataFrom(Http.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.call(GoogleTranslator.kt:96)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.access$call(GoogleTranslator.kt:16)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:48)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator$doTranslate$1.invoke(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.SimpleTranslateClient.doExecute(SimpleTranslateClient.kt:15)
	at cn.yiiguxing.plugin.translate.trans.TranslateClient.execute(TranslateClient.kt:50)
	at cn.yiiguxing.plugin.translate.trans.google.GoogleTranslator.doTranslate(GoogleTranslator.kt:50)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:19)
	... 12 more
```
[idea.log](https://github.com/YiiGuxing/TranslationPlugin/files/8124027/idea.log)

**Comment by YiiGuxing** [comment]
这个是服务器有问题，现在应该好了吧？

**Comment by SaltedFish-Extreme** [comment]
> 这个是服务器有问题，现在应该好了吧？

嗯，后面就好了，我也不清楚是啥问题就问问，打扰老哥了😂
